### ISSUE TITLE
Error annotating from Canvas tracks

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1077]
FYI @monicacecilia  Something else we need to remember to test for.    

These work fine for HTMLFeatures when doing a right-click.

When annotating a human canvas track (similar results for Volvox):

http://icebox.lbl.gov/Apollo-staging

Some types work and some types do not:

- [x] gene  / mRNA
- [x]  pseudogene / transcript
- [x] tRNA, snRNA, etc. 
- [x] repeat_region
- [x] transposable_elements

The errors generated (below) are the first for pseudogene /transcript (observed) and the second for repeat region.  

```
2016-05-28 10:44:07,304 [clientInboundChannel-3] ERROR springwebsocket.GrailsSimpAnnotationMethodMessageHandler  - Unhandled exception
java.lang.reflect.InvocationTargetException
	at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4$_closure5$_closure6.doCall(AnnotationEditorController.groovy:1096)
	at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4$_closure5.doCall(AnnotationEditorController.groovy:1095)
	at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4.doCall(AnnotationEditorController.groovy:1091)
	at groovyx.gpars.group.PGroup$3.call(PGroup.java:289)
	at groovyx.gpars.group.PGroup$4.run(PGroup.java:313)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.NoSuchElementException
	at java.util.ArrayList$Itr.next(ArrayList.java:854)
	at org.bbop.apollo.FeatureService.$tt__addFeature(FeatureService.groovy:2803)
	at org.bbop.apollo.RequestHandlingService.$tt__addFeature(RequestHandlingService.groovy:1691)
	... 8 more
2016-05-28 10:44:12,858 [clientInboundChannel-2] ERROR 
```

```
springwebsocket.GrailsSimpAnnotationMethodMessageHandler  - Unhandled exception
java.lang.reflect.InvocationTargetException
	at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4$_closure5$_closure6.doCall(AnnotationEditorController.groovy:1096)
	at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4$_closure5.doCall(AnnotationEditorController.groovy:1095)
	at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4.doCall(AnnotationEditorController.groovy:1091)
	at groovyx.gpars.group.PGroup$3.call(PGroup.java:289)
	at groovyx.gpars.group.PGroup$4.run(PGroup.java:313)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.NoSuchElementException
	at java.util.ArrayList$Itr.next(ArrayList.java:854)
	at org.bbop.apollo.FeatureService.$tt__addFeature(FeatureService.groovy:2803)
	at org.bbop.apollo.RequestHandlingService.$tt__addFeature(RequestHandlingService.groovy:1691)
	... 8 more
```

**Comment by nathandunn** [comment]
Found when testing: https://github.com/TAMU-CPT/galaxy-apollo/issues/2

**Comment by deepakunni3** [comment]
@nathandunn This was because the method call in `WebApolloCanvasFeatures.js` for pseudogene, repeat region and transposable element are different from `DraggableHTMLFeatures.js`. This resulted in a wrongly formatted JSON object being sent to the server.

PR #1079 addresses this issue.

**Comment by nathandunn** [comment]
Awesome thanks.

**Comment by nathandunn** [comment]
To Test: Annotate a Canvas Track (see Human) for all of the above types and see that they work properly.

**Comment by monicacecilia** [comment]
💃
