### ISSUE TITLE
mysql error when getting timestamps

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1161]
```
Jul 04, 2016 6:18:30 PM org.apache.coyote.AbstractProtocol pause
INFO: Pausing ProtocolHandler ["http-bio-8080"]
Jul 04, 2016 6:18:30 PM org.apache.catalina.core.StandardService stopInternal
INFO: Stopping service Catalina
Jul 04, 2016 6:18:31 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/apollo] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to stop it. This is very likely to create a memory leak.
Jul 04, 2016 6:18:31 PM org.apache.coyote.AbstractProtocol stop
INFO: Stopping ProtocolHandler ["http-bio-8080"]
Jul 04, 2016 6:18:31 PM org.apache.coyote.AbstractProtocol destroy
INFO: Destroying ProtocolHandler ["http-bio-8080"]
Please use CMSClassUnloadingEnabled in place of CMSPermGenSweepingEnabled in the future
Jul 04, 2016 6:18:48 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat7/common/classes], exists: [false], isDirectory: [false], canRead: [false]
Jul 04, 2016 6:18:48 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat7/common], exists: [false], isDirectory: [false], canRead: [false]
Jul 04, 2016 6:18:49 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat7/server/classes], exists: [false], isDirectory: [false], canRead: [false]
Jul 04, 2016 6:18:49 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat7/server], exists: [false], isDirectory: [false], canRead: [false]
Jul 04, 2016 6:18:49 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat7/shared/classes], exists: [false], isDirectory: [false], canRead: [false]
Jul 04, 2016 6:18:49 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat7/shared], exists: [false], isDirectory: [false], canRead: [false]
Jul 04, 2016 6:18:50 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-bio-8080"]
Jul 04, 2016 6:18:50 PM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 1181 ms
Jul 04, 2016 6:18:50 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Catalina
Jul 04, 2016 6:18:50 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.52 (Ubuntu)
Jul 04, 2016 6:18:50 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /var/lib/tomcat7/webapps/apollo.war
Jul 04, 2016 6:19:10 PM org.apache.catalina.startup.TaglibUriRule body
INFO: TLD skipped. URI: http://www.springframework.org/tags is already defined
Jul 04, 2016 6:19:10 PM org.apache.catalina.startup.TaglibUriRule body
INFO: TLD skipped. URI: http://www.springframework.org/tags/form is already defined
log4j:WARN No appenders could be found for logger (org.codehaus.groovy.grails.commons.cfg.ConfigurationHelper).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

Configuring Shiro ...

Shiro Configured
Jul 04, 2016 6:20:13 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /var/lib/tomcat7/webapps/apollotest.war
Jul 04, 2016 6:20:25 PM org.apache.catalina.startup.TaglibUriRule body
INFO: TLD skipped. URI: http://www.springframework.org/tags is already defined
Jul 04, 2016 6:20:25 PM org.apache.catalina.startup.TaglibUriRule body
INFO: TLD skipped. URI: http://www.springframework.org/tags/form is already defined
log4j:WARN No appenders could be found for logger (org.codehaus.groovy.grails.commons.cfg.ConfigurationHelper).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

Configuring Shiro ...

Shiro Configured
Jul 04, 2016 6:21:11 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /var/lib/tomcat7/webapps/ROOT
Jul 04, 2016 6:21:12 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8080"]
Jul 04, 2016 6:21:12 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 142001 ms
2016-07-04 18:22:24,430 [http-bio-8080-exec-7] ERROR spi.SqlExceptionHelper  - Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp
2016-07-04 18:22:24,430 [http-bio-8080-exec-8] ERROR spi.SqlExceptionHelper  - Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp
2016-07-04 18:22:24,430 [http-bio-8080-exec-10] ERROR spi.SqlExceptionHelper  - Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp
2016-07-04 18:22:24,446 [http-bio-8080-exec-7] ERROR apollo.UserController  - org.springframework.dao.TransientDataAccessResourceException: Hibernate operation: could not execute query; SQL [select this_.id as id1_54_0_, this_.version as version2_54_0_, this_.client_token as client_t3_54_0_, this_.date_created as date_cre4_54_0_, this_.domain as domain5_54_0_, this_.last_updated as last_upd6_54_0_, this_.name as name7_54_0_, this_.preferences_string as preferen8_54_0_, this_.user_id as user_id10_54_0_, this_.current_organism as current11_54_0_, this_.endbp as endbp12_54_0_, this_.native_track_list as native_13_54_0_, this_.organism_id as organis14_54_0_, this_.sequence_id as sequenc15_54_0_, this_.startbp as startbp16_54_0_ from preference this_ where this_.class='org.bbop.apollo.UserOrganismPreference' and this_.user_id=? and this_.current_organism=? order by this_.last_updated desc]; Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp; nested exception is java.sql.SQLException: Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp
2016-07-04 18:22:24,514 [http-bio-8080-exec-8] ERROR apollo.GroupController  - {error=Hibernate operation: could not execute query; SQL [select this_.id as id1_54_0_, this_.version as version2_54_0_, this_.client_token as client_t3_54_0_, this_.date_created as date_cre4_54_0_, this_.domain as domain5_54_0_, this_.last_updated as last_upd6_54_0_, this_.name as name7_54_0_, this_.preferences_string as preferen8_54_0_, this_.user_id as user_id10_54_0_, this_.current_organism as current11_54_0_, this_.endbp as endbp12_54_0_, this_.native_track_list as native_13_54_0_, this_.organism_id as organis14_54_0_, this_.sequence_id as sequenc15_54_0_, this_.startbp as startbp16_54_0_ from preference this_ where this_.class='org.bbop.apollo.UserOrganismPreference' and this_.user_id=? and this_.current_organism=? order by this_.last_updated desc]; Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp; nested exception is java.sql.SQLException: Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp}
2016-07-04 18:22:24,813 [http-bio-8080-exec-10] ERROR errors.GrailsExceptionResolver  - SQLException occurred when processing request: [POST] /apollotest/sequence/getSequences/
Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp. Stacktrace follows:
java.sql.SQLException: Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1086)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:989)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:975)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:920)
	at com.mysql.jdbc.ResultSetRow.getTimestampFast(ResultSetRow.java:1101)
	at com.mysql.jdbc.ByteArrayRow.getTimestampFast(ByteArrayRow.java:126)
	at com.mysql.jdbc.ResultSetImpl.getTimestampInternal(ResultSetImpl.java:6588)
	at com.mysql.jdbc.ResultSetImpl.getTimestamp(ResultSetImpl.java:6188)
	at com.mysql.jdbc.ResultSetImpl.getTimestamp(ResultSetImpl.java:6226)
	at org.grails.datastore.gorm.GormStaticApi$_methodMissing_closure2.doCall(GormStaticApi.groovy:102)
	at org.bbop.apollo.PreferenceService.$tt__getCurrentOrganismPreference(PreferenceService.groovy:130)
	at org.bbop.apollo.PreferenceService.$tt__getOrganismFromPreferences(PreferenceService.groovy:173)
	at org.bbop.apollo.PreferenceService.$tt__getCurrentOrganismForCurrentUser(PreferenceService.groovy:17)
	at org.bbop.apollo.SequenceController.$tt__getSequences(SequenceController.groovy:165)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2016-07-04 18:22:25,451 [http-bio-8080-exec-3] ERROR spi.SqlExceptionHelper  - Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp
2016-07-04 18:22:25,462 [http-bio-8080-exec-3] ERROR errors.GrailsExceptionResolver  - SQLException occurred when processing request: [GET] /apollotest/annotator/getAppState
Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp. Stacktrace follows:
java.sql.SQLException: Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1086)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:989)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:975)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:920)
	at com.mysql.jdbc.ResultSetRow.getTimestampFast(ResultSetRow.java:1101)
	at com.mysql.jdbc.ByteArrayRow.getTimestampFast(ByteArrayRow.java:126)
	at com.mysql.jdbc.ResultSetImpl.getTimestampInternal(ResultSetImpl.java:6588)
	at com.mysql.jdbc.ResultSetImpl.getTimestamp(ResultSetImpl.java:6188)
	at com.mysql.jdbc.ResultSetImpl.getTimestamp(ResultSetImpl.java:6226)
	at org.grails.datastore.gorm.GormStaticApi$_methodMissing_closure2.doCall(GormStaticApi.groovy:102)
	at org.bbop.apollo.PreferenceService.$tt__getCurrentOrganismPreference(PreferenceService.groovy:130)
	at org.bbop.apollo.PreferenceService.$tt__getCurrentOrganismPreference(PreferenceService.groovy:181)
	at org.bbop.apollo.AnnotatorService.$tt__getAppState(AnnotatorService.groovy:46)
	at org.bbop.apollo.AnnotatorController.$tt__getAppState(AnnotatorController.groovy:371)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2016-07-04 18:27:08,621 [http-bio-8080-exec-5] ERROR apollo.PermissionService  - Problem authenticating: org.apache.shiro.authc.AccountException: Null usernames are not allowed by this realm.
2016-07-04 18:27:08,625 [http-bio-8080-exec-9] ERROR apollo.PermissionService  - Problem authenticating: org.apache.shiro.authc.AccountException: Null usernames are not allowed by this realm.
2016-07-04 18:27:08,627 [http-bio-8080-exec-9] ERROR apollo.UserController  - {error=Cannot cast object 'false' with class 'java.lang.Boolean' to class 'org.codehaus.groovy.grails.web.json.JSONObject'}
2016-07-04 18:27:08,634 [http-bio-8080-exec-5] ERROR apollo.GroupController  - {error=Cannot cast object 'false' with class 'java.lang.Boolean' to class 'org.codehaus.groovy.grails.web.json.JSONObject'}
2016-07-04 18:27:15,848 [http-bio-8080-exec-7] ERROR spi.SqlExceptionHelper  - Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp
2016-07-04 18:27:15,866 [http-bio-8080-exec-7] ERROR errors.GrailsExceptionResolver  - SQLException occurred when processing request: [POST] /apollotest/sequence/getSequences/
Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp. Stacktrace follows:
java.sql.SQLException: Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1086)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:989)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:975)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:920)
	at com.mysql.jdbc.ResultSetRow.getTimestampFast(ResultSetRow.java:1101)
	at com.mysql.jdbc.ByteArrayRow.getTimestampFast(ByteArrayRow.java:126)
	at com.mysql.jdbc.ResultSetImpl.getTimestampInternal(ResultSetImpl.java:6588)
	at com.mysql.jdbc.ResultSetImpl.getTimestamp(ResultSetImpl.java:6188)
	at com.mysql.jdbc.ResultSetImpl.getTimestamp(ResultSetImpl.java:6226)
	at org.grails.datastore.gorm.GormStaticApi$_methodMissing_closure2.doCall(GormStaticApi.groovy:102)
	at org.bbop.apollo.PreferenceService.$tt__getCurrentOrganismPreference(PreferenceService.groovy:130)
	at org.bbop.apollo.PreferenceService.$tt__getOrganismFromPreferences(PreferenceService.groovy:173)
	at org.bbop.apollo.PreferenceService.$tt__getCurrentOrganismForCurrentUser(PreferenceService.groovy:17)
	at org.bbop.apollo.SequenceController.$tt__getSequences(SequenceController.groovy:165)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2016-07-04 18:27:15,938 [http-bio-8080-exec-2] ERROR spi.SqlExceptionHelper  - Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp
2016-07-04 18:27:15,938 [http-bio-8080-exec-2] ERROR apollo.UserController  - org.springframework.dao.TransientDataAccessResourceException: Hibernate operation: could not execute query; SQL [select this_.id as id1_54_0_, this_.version as version2_54_0_, this_.client_token as client_t3_54_0_, this_.date_created as date_cre4_54_0_, this_.domain as domain5_54_0_, this_.last_updated as last_upd6_54_0_, this_.name as name7_54_0_, this_.preferences_string as preferen8_54_0_, this_.user_id as user_id10_54_0_, this_.current_organism as current11_54_0_, this_.endbp as endbp12_54_0_, this_.native_track_list as native_13_54_0_, this_.organism_id as organis14_54_0_, this_.sequence_id as sequenc15_54_0_, this_.startbp as startbp16_54_0_ from preference this_ where this_.class='org.bbop.apollo.UserOrganismPreference' and this_.user_id=? and this_.current_organism=? order by this_.last_updated desc]; Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp; nested exception is java.sql.SQLException: Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp
2016-07-04 18:27:15,941 [http-bio-8080-exec-9] ERROR spi.SqlExceptionHelper  - Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp
2016-07-04 18:27:15,950 [http-bio-8080-exec-9] ERROR apollo.GroupController  - {error=Hibernate operation: could not execute query; SQL [select this_.id as id1_54_0_, this_.version as version2_54_0_, this_.client_token as client_t3_54_0_, this_.date_created as date_cre4_54_0_, this_.domain as domain5_54_0_, this_.last_updated as last_upd6_54_0_, this_.name as name7_54_0_, this_.preferences_string as preferen8_54_0_, this_.user_id as user_id10_54_0_, this_.current_organism as current11_54_0_, this_.endbp as endbp12_54_0_, this_.native_track_list as native_13_54_0_, this_.organism_id as organis14_54_0_, this_.sequence_id as sequenc15_54_0_, this_.startbp as startbp16_54_0_ from preference this_ where this_.class='org.bbop.apollo.UserOrganismPreference' and this_.user_id=? and this_.current_organism=? order by this_.last_updated desc]; Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp; nested exception is java.sql.SQLException: Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp}
2016-07-04 18:27:16,202 [http-bio-8080-exec-1] ERROR spi.SqlExceptionHelper  - Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp
2016-07-04 18:27:16,210 [http-bio-8080-exec-1] ERROR errors.GrailsExceptionResolver  - SQLException occurred when processing request: [GET] /apollotest/annotator/getAppState
Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp. Stacktrace follows:
java.sql.SQLException: Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1086)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:989)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:975)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:920)
	at com.mysql.jdbc.ResultSetRow.getTimestampFast(ResultSetRow.java:1101)
	at com.mysql.jdbc.ByteArrayRow.getTimestampFast(ByteArrayRow.java:126)
	at com.mysql.jdbc.ResultSetImpl.getTimestampInternal(ResultSetImpl.java:6588)
	at com.mysql.jdbc.ResultSetImpl.getTimestamp(ResultSetImpl.java:6188)
	at com.mysql.jdbc.ResultSetImpl.getTimestamp(ResultSetImpl.java:6226)
	at org.grails.datastore.gorm.GormStaticApi$_methodMissing_closure2.doCall(GormStaticApi.groovy:102)
	at org.bbop.apollo.PreferenceService.$tt__getCurrentOrganismPreference(PreferenceService.groovy:130)
	at org.bbop.apollo.PreferenceService.$tt__getCurrentOrganismPreference(PreferenceService.groovy:181)
	at org.bbop.apollo.AnnotatorService.$tt__getAppState(AnnotatorService.groovy:46)
	at org.bbop.apollo.AnnotatorController.$tt__getAppState(AnnotatorController.groovy:371)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by nathandunn** [comment]
I think its because there are null dates in the preference table, which might be due to the script or just MySQL in general (haven’t seen this with PostgreSQL).    Looking here:

http://stackoverflow.com/a/36963716/1739366

I think you can set the sql_mode different and it might fix it. 

```
SET SESSION sql_mode = '';
```

If you could verify that the lastUpdated / dateCreated is null (my theory) that would help:

If you could run this:

    select last_updated,count(*) from preference group by last_updated  ; 

and this:

    select count(*) from preference where last_updated is null  ; 

that would be helpful.   It might be that these are nullable (they should be inserted automatically), or we need to set something specific in MySQL.  

==== 

Here is some more information (for an internal note). 

There error is realized here:

https://github.com/GMOD/Apollo/blob/2.0.3/grails-app/services/org/bbop/apollo/PreferenceService.groovy#L130

```
        userOrganismPreference = UserOrganismPreference.findByUserAndCurrentOrganism(user, true,[max: 1, sort: "lastUpdated", order: "desc"])
```

where it is trying to sort by lastUpdated.  



You could replace this line (getting rid of the sort), though it would need to be done in many other places:

```
        userOrganismPreference = UserOrganismPreference.findByUserAndCurrentOrganism(user, true,[max: 1])
```

**Comment by nathandunn** [comment]
Tested locally with MySQL and I didn't run into any problems.

**Comment by nathandunn** [comment]
Possibly the script (or extended use) leads to additional problems.  I had tested with mac on homebrew: 

    mysql  Ver 14.14 Distrib 5.7.12, for osx10.11 (x86_64) using  EditLine wrapper

**Comment by nathandunn** [comment]
Against master.

**Comment by nathandunn** [comment]
Deleting contents of preference table worked.
