### ISSUE TITLE
Connection problems lead to stalling edits.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#14]
1. 
Users are experiencing problems when trying to change an exon boundary. 
The behaviour includes: 
- the boundary bounces back and remains unchanged
- after refreshing (cleaning cache) the boundary can be changed
- after refreshing (cleaning cache) the boundary is ALREADY changed

The problem may be the result of latency issues, connection timeouts, or connection lag. It could be also the result of intermittent connections on WiFi, resulting in users attempting to connect to a no-longer-existent session. 

2.
Users are experiencing a similar problem when trying to delete an exon. 
The behaviour includes: 
- deleting the exon with the right-click menu, but seeing the exon still displayed on the screen
- attempting to delete the exon for a second (and subsequent) times leads to error messages from Web Apollo stating that the exon cannot be deleted because it does not exist.

Example error log from user: 
(from localhost.2014-07-14.log):

Jul 14, 2014 10:35:57 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [org.bbop.apollo.web.AnnotationEditorService] in context with path [/cimlec] threw exception
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1904)
        at org.bbop.apollo.editor.AnnotationEditor.setTranslationStart(AnnotationEditor.java:352)
        at org.bbop.apollo.editor.AnnotationEditor.setTranslationStart(AnnotationEditor.java:313)
        at org.bbop.apollo.editor.AnnotationEditor.calculateCDS(AnnotationEditor.java:466)
        at org.bbop.apollo.web.AnnotationEditorService.calculateCDS(AnnotationEditorService.java:2078)
        at org.bbop.apollo.web.AnnotationEditorService.calculateCDS(AnnotationEditorService.java:2073)
        at org.bbop.apollo.web.AnnotationEditorService.setExonBoundaries(AnnotationEditorService.java:2556)
        at org.bbop.apollo.web.AnnotationEditorService.doPost(AnnotationEditorService.java:561)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)

**Comment by nathandunn** [comment]
should be a non-issue in 2.0
