### ISSUE TITLE
projection: boundary disappears sometimes

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1403]
![screen shot 2017-01-03 at 12 04 30 pm](https://cloud.githubusercontent.com/assets/751274/21621219/da1a6472-d1ac-11e6-9e22-08f83b27eb71.png)

and then after I zoom it is all correct:

![screen shot 2017-01-03 at 12 05 16 pm](https://cloud.githubusercontent.com/assets/751274/21621239/ed2a9d52-d1ac-11e6-833d-9ce5652bdab3.png)

Looks like the "overall" is miscalculated.

**Comment by nathandunn** [comment]
Zooming in and out fixes this absolutely.  Its really just the initial zoom for the top-bar is somehow incorrect.

**Comment by nathandunn** [comment]
I get this error typically when I double-click on a "combined" type and its associated with this, rendering -1 to -1 (min/max):

```
VM7382 Browser.js:1906 TypeError: Cannot read property 'toLowerCase' of undefined TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.regularizeReferenceName (http://localhost:8080/apollo/17061810341064355775/jbrowse/src/JBrowse/Browser.js:638:22)
    at Object.compareReferenceNames (http://localhost:8080/apollo/17061810341064355775/jbrowse/src/JBrowse/Browser.js:620:17)
    at Object.findReferenceSequence (http://localhost:8080/apollo/17061810341064355775/jbrowse/src/JBrowse/Browser.js:2359:25)
    at Object.callLocation (http://localhost:8080/apollo/17061810341064355775/jbrowse/src/JBrowse/Browser.js:2324:25)
    at http://localhost:8080/apollo/17061810341064355775/jbrowse/src/JBrowse/Browser.js:2306:19
    at http://localhost:8080/apollo/17061810341064355775/jbrowse/src/JBrowse/Browser.js:1904:29
    at signalListener (http://localhost:8080/apollo/17061810341064355775/jbrowse/src/dojo/Deferred.js:37:21)
    at signalWaiting (http://localhost:8080/apollo/17061810341064355775/jbrowse/src/dojo/Deferred.js:28:4)
    at Deferred.resolve (http://localhost:8080/apollo/17061810341064355775/jbrowse/src/dojo/Deferred.js:192:5)
    at Object.<anonymous> (http://localhost:8080/apollo/17061810341064355775/jbrowse/src/JBrowse/Browser.js:967:30) TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.regularizeReferenceName (VM7382 Browser.js:638)
    at Object.compareReferenceNames (VM7382 Browser.js:620)
    at Object.findReferenceSequence (VM7382 Browser.js:2359)
    at Object.callLocation (VM7382 Browser.js:2324)
    at VM7382 Browser.js:2306
    at VM7382 Browser.js:1904
    at signalListener (VM7393 Deferred.js:37)
    at signalWaiting (VM7393 Deferred.js:28)
    at Deferred.resolve (VM7393 Deferred.js:192)
    at Object.<anonymous> (VM7382 Browser.js:967)
```

So somehow the 'findReference' sequence name is failing.  

Once we zoom in or out it then works. 

It is probably interrupting the JS portion doing the outline.

**Comment by nathandunn** [comment]
This above error is fixed in the projection_v2_server branch.

**Comment by nathandunn** [comment]
From #1413. 
> This is lower priority, but overall this should be moved to be a non-rest function if possible.

Basically, if a block region has a boundary in it, we render a vertical line with the appropriate jazz at the appropriate place

**Comment by nathandunn** [comment]
e.g.:

    http://localhost:8080/apollo/annotator/loadLink?loc=%5B%7B%22name%22:%22Group11.4%22,%20%22start%22:10057,%20%22end%22:18796,%20%22reverse%22:false,%20%22feature%22:%7B%22parent_id%22:%22Group11.4%22,%20%22name%22:%22GB52238-RA%22,%20%22start%22:10057,%20%22end%22:18796%7D%7D,%7B%22name%22:%22GroupUn87%22,%20%22start%22:29196,%20%22end%22:30529,%20%22reverse%22:false,%20%22feature%22:%7B%22parent_id%22:%22GroupUn87%22,%20%22name%22:%22GB53498-RA%22,%20%22start%22:29196,%20%22end%22:30529%7D%7D%5D:8232..9162&organism=21&tracks=Official%20Gene%20Set%20v3.2,ProjectionGrid,ProjectionBoundary
