### ISSUE TITLE
projection: adjusting annotator panel losses "selected" attribute

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1405]
(minor)

- [x] used indicator is dropped
- ~~initial sort is incorrect~~ there is no initial sort
- ~~fix TypeError: Cannot read property 'toLowerCase' of undefined~~ moved to #1412

Initially loads selected "used" correctly:

![screen shot 2017-01-03 at 12 26 31 pm](https://cloud.githubusercontent.com/assets/751274/21621889/e5b62e94-d1af-11e6-86d7-7e21e3464a9c.png)

Adjusting the frame creates a "redraw" I think, which drops the indicator:

![screen shot 2017-01-03 at 12 26 40 pm](https://cloud.githubusercontent.com/assets/751274/21621904/f77feef8-d1af-11e6-9732-470a2c602520.png)

Clicking off and on the filter fixes this.

**Comment by nathandunn** [comment]
The usedSequences somehow goes to 0 and there are no more matches.

Also I get this:

```
plugin HideTracksButton constructor
VM30842 Browser.js:1906TypeError: Cannot read property 'toLowerCase' of undefined TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.regularizeReferenceName (http://localhost:8080/apollo/24753634519727370841420802568/jbrowse/src/JBrowse/Browser.js:638:22)
    at Object.compareReferenceNames (http://localhost:8080/apollo/24753634519727370841420802568/jbrowse/src/JBrowse/Browser.js:620:17)
    at Object.findReferenceSequence (http://localhost:8080/apollo/24753634519727370841420802568/jbrowse/src/JBrowse/Browser.js:2359:25)
    at Object.callLocation (http://localhost:8080/apollo/24753634519727370841420802568/jbrowse/src/JBrowse/Browser.js:2324:25)
    at http://localhost:8080/apollo/24753634519727370841420802568/jbrowse/src/JBrowse/Browser.js:2306:19
    at http://localhost:8080/apollo/24753634519727370841420802568/jbrowse/src/JBrowse/Browser.js:1904:29
    at signalListener (http://localhost:8080/apollo/24753634519727370841420802568/jbrowse/src/dojo/Deferred.js:37:21)
    at signalWaiting (http://localhost:8080/apollo/24753634519727370841420802568/jbrowse/src/dojo/Deferred.js:28:4)
    at Deferred.resolve (http://localhost:8080/apollo/24753634519727370841420802568/jbrowse/src/dojo/Deferred.js:192:5)
    at Object.<anonymous> (http://localhost:8080/apollo/24753634519727370841420802568/jbrowse/src/JBrowse/Browser.js:967:30) TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.regularizeReferenceName (VM30842 Browser.js:638)
    at Object.compareReferenceNames (VM30842 Browser.js:620)
    at Object.findReferenceSequence (VM30842 Browser.js:2359)
    at Object.callLocation (VM30842 Browser.js:2324)
    at VM30842 Browser.js:2306
```
