### ISSUE TITLE
projection: evidence name search now fails

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1412]
evidence name search fails, where it was working previously

**Comment by nathandunn** [comment]
on load we get:

```
plugin HideTracksButton constructor
VM30842 Browser.js:1906TypeError: Cannot read property 'toLowerCase' of undefined TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.regularizeReferenceName (http://localhost:8080/apollo/24753634519727370841420802568/jbrowse/src/JBrowse/Browser.js:638:22)
    at Object.compareReferenceNames (http://localhost:8080/apollo/24753634519727370841420802568/jbrowse/src/JBrowse/Browser.js:620:17)
    at Object.findReferenceSequence (http://localhost:8080/apollo/24753634519727370841420802568/jbrowse/src/JBrowse/Browser.js:2359:25)
    at Object.callLocation (http://localhost:8080/apollo/24753634519727370841420802568/jbrowse/src/JBrowse/Browser.js:2324:25)
    at http://localhost:8080/apollo/24753634519727370841420802568/jbrowse/src/JBrowse/Browser.js:2306:19
    at http://localhost:8080/apollo/24753634519727370841420802568/jbrowse/src/JBrowse/Browser.js:1904:29
    at signalListener (http://localhost:8080/apollo/24753634519727370841420802568/jbrowse/src/dojo/Deferred.js:37:21)
    at signalWaiting (http://localhost:8080/apollo/24753634519727370841420802568/jbrowse/src/dojo/Deferred.js:28:4)
    at Deferred.resolve (http://localhost:8080/apollo/24753634519727370841420802568/jbrowse/src/dojo/Deferred.js:192:5)
    at Object.<anonymous> (http://localhost:8080/apollo/24753634519727370841420802568/jbrowse/src/JBrowse/Browser.js:967:30) TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.regularizeReferenceName (VM30842 Browser.js:638)
    at Object.compareReferenceNames (VM30842 Browser.js:620)
    at Object.findReferenceSequence (VM30842 Browser.js:2359)
    at Object.callLocation (VM30842 Browser.js:2324)
    at VM30842 Browser.js:2306
```

**Comment by nathandunn** [comment]
this seems to be working now

**Comment by nathandunn** [comment]
may not have been caching properly
