### ISSUE TITLE
Can't delete a gene

### ISSUE THREAD

**Issue by abretaud** [GMOD/Apollo#1484]
I get this error while trying to delete a gene from the annotation track:

```
apollo_1         | 2017-02-09 13:34:42,479 [clientInboundChannel-1] ERROR springwebsocket.GrailsSimpAnnotationMethodMessageHandler  - Unhandled exception
apollo_1         | java.lang.reflect.InvocationTargetException
apollo_1         | 	at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4$_closure5$_closure6.doCall(AnnotationEditorController.groovy:1144)
apollo_1         | 	at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4$_closure5.doCall(AnnotationEditorController.groovy:1143)
apollo_1         | 	at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4.doCall(AnnotationEditorController.groovy:1139)
apollo_1         | 	at groovyx.gpars.group.PGroup$3.call(PGroup.java:289)
apollo_1         | 	at groovyx.gpars.group.PGroup$4.run(PGroup.java:313)
apollo_1         | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
apollo_1         | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
apollo_1         | 	at java.lang.Thread.run(Thread.java:745)
apollo_1         | Caused by: org.springframework.dao.InvalidDataAccessApiUsageException: deleted object would be re-saved by cascade (remove deleted object from associations): [org.bbop.apollo.FeatureRelationship#10606]; nested exception is org.hibernate.ObjectDeletedException: deleted object would be re-saved by cascade (remove deleted object from associations): [org.bbop.apollo.FeatureRelationship#10606]
apollo_1         | 	at org.bbop.apollo.ExonService.$tt__deleteExon(ExonService.groovy:142)
apollo_1         | 	at org.bbop.apollo.FeatureService.$tt__deleteFeature(FeatureService.groovy:1883)
apollo_1         | 	at org.bbop.apollo.RequestHandlingService.$tt__deleteFeature(RequestHandlingService.groovy:1771)
apollo_1         | 	... 8 more
apollo_1         | Caused by: org.hibernate.ObjectDeletedException: deleted object would be re-saved by cascade (remove deleted object from associations): [org.bbop.apollo.FeatureRelationship#10606]
apollo_1         | 	... 11 more
```

Does it evoke something to you?

**Comment by nathandunn** [comment]
I'm not seeing this on production.  A couple of questions:

- If you refresh are you still getting this error? 
- If you create another annotation are you still getting this error when you attempt to delete?
- Are you running the release version or newer? ba0694195baf7094bc336ec3ca4b0227eca55c1b

**Comment by abretaud** [comment]
Strange problem...
I created the gene with 2.0.5, then upgraded to 2.0.6.
In the meantime I also deactivated NeatFeature and changed track type.
And it happened on 2 different apollo instances.
Finally I managed to remove the gene with "Make intron" then "Delete".
I don't have anymore the problem with new genes I add now...

**Comment by nathandunn** [comment]
Agreed.  That is very strange.  My guess is that 2.0.6 is a bit more aggressive in cleaning up data.      Should I go ahead and close this?

**Comment by abretaud** [comment]
Yep, I close this, I'll let you know if I see this error again in the future
