### ISSUE TITLE
REMOTE_USER metadata authentication

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#1539]
```
04-Apr-2017 23:23:25.909 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 53905 ms
2017-04-04 23:27:29,676 [http-apr-8080-exec-6] WARN  authenticator.RemoteUserAuthenticatorService  - Remote user found [user@example.com]
2017-04-04 23:27:29,679 [http-apr-8080-exec-6] WARN  authenticator.RemoteUserAuthenticatorService  - User exists null ? 
2017-04-04 23:27:29,679 [http-apr-8080-exec-6] WARN  authenticator.RemoteUserAuthenticatorService  - for username: user@example.com
2017-04-04 23:27:29,679 [http-apr-8080-exec-6] WARN  authenticator.RemoteUserAuthenticatorService  - User does not exist so creating new user.
2017-04-04 23:27:29,732 [http-apr-8080-exec-6] WARN  authenticator.RemoteUserAuthenticatorService  - User created org.bbop.apollo.User : 20
2017-04-04 23:27:29,763 [http-apr-8080-exec-6] ERROR authenticator.RemoteUserAuthenticatorService  - Problem authenticating: org.apache.shiro.authc.AuthenticationException: Authentication failed for token submission [org.apache.shiro.authc.UsernamePasswordToken - user@example.com, rememberMe=false].  Possible unexpected error? (Typical or expected login exceptions should extend from AuthenticationException).
2017-04-04 23:27:29,763 [http-apr-8080-exec-6] ERROR authenticator.RemoteUserAuthenticatorService  - Failed to authenticate user user@example.com, resaving password and forcing
2017-04-04 23:27:29,842 [http-apr-8080-exec-6] ERROR errors.GrailsExceptionResolver  - MissingMethodException occurred when processing request: [GET] /user/checkLogin
No signature of method: org.bbop.apollo.User.put() is applicable for argument types: (java.lang.String, java.lang.String) values: [INTERNAL_PASSWORD, 9567317461141129409221158399]
Possible solutions: putAt(java.lang.String, java.lang.Object), wait(), count(), last(), list(), dump(). Stacktrace follows:
groovy.lang.MissingMethodException: No signature of method: org.bbop.apollo.User.put() is applicable for argument types: (java.lang.String, java.lang.String) values: [INTERNAL_PASSWORD, 9567317461141129409221158399]
Possible solutions: putAt(java.lang.String, java.lang.Object), wait(), count(), last(), list(), dump()
        at org.bbop.apollo.authenticator.RemoteUserAuthenticatorService.$tt__authenticate(RemoteUserAuthenticatorService.groovy:93)
        at org.bbop.apollo.PermissionService.$tt__authenticateWithToken(PermissionService.groovy:558)
        at org.bbop.apollo.UserController.$tt__checkLogin(UserController.groovy:159)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

seems to be from 2e7d897b

My `docker-compose.yml`:

```
version: '2'
services:
  remote_user:
    image: quay.io/tamu_cpt/remote-user-proxy:latest
    links:
      - apollo:target
    ports:
      - "9998:80"
    environment:
      BACKEND_URL: "http://target:8080"
      REMOTE_USER: user@example.com
  apollo:
    image: quay.io/erasche/apollo:cpt
    links:
      - db
      - chado
    ports:
      - "8080:8080"
    environment:
      CONTEXT_PATH: ROOT
      WEBAPOLLO_DB_USERNAME: postgres
      WEBAPOLLO_DB_PASSWORD: password
      WEBAPOLLO_DB_DRIVER: "org.postgresql.Driver"
      WEBAPOLLO_DB_DIALECT: "org.hibernate.dialect.PostgresPlusDialect"
      WEBAPOLLO_DB_URI: "jdbc:postgresql://db/postgres"
      WEBAPOLLO_CHADO_DB_USERNAME: postgres
      WEBAPOLLO_CHADO_DB_PASSWORD: password
      WEBAPOLLO_CHADO_DB_DRIVER: "org.postgresql.Driver"
      WEBAPOLLO_CHADO_DB_DIALECT: "org.hibernate.dialect.PostgresPlusDialect"
      WEBAPOLLO_CHADO_DB_URI: "jdbc:postgresql://chado/postgres"
      # Optional, allow image to 'wait'
      WEBAPOLLO_DB_HOST: db
      WEBAPOLLO_DB_PORT: 5432
      WEBAPOLLO_DB_NAME: postgres
      WEBAPOLLO_CHADO_DB_HOST: chado
      WEBAPOLLO_CHADO_DB_PORT: 5432
      WEBAPOLLO_CHADO_DB_NAME: postgres
    volumes:
      - "./data:/data"
  db:
    image: erasche/chado:1.31-jenkins97-pg9.5
    environment:
      POSTGRES_PASSWORD: password
      INSTALL_CHADO_SCHEMA: "0"
  chado:
    image: erasche/chado:1.31-jenkins97-pg9.5
    environment:
      - POSTGRES_PASSWORD=password
      # The default chado image would try to install the schema on first run
      #- INSTALL_CHADO_SCHEMA=0
    volumes:
      - /var/lib/postgresql/9.4/
```

**Comment by nathandunn** [comment]
Interesting, it should probably be using metadata on the user object.  I'll take a look.

**Comment by nathandunn** [comment]
@erasche  This should be fixed now.   Using JSON versus full column tables versus denormalized is a bit interesting.   Please close if working.  Thanks.

**Comment by erasche** [comment]
Compiling/testing now, thanks for getting this out so quickly.

**Comment by erasche** [comment]
I'm afraid I'm not sure that that fixes it either. I'm poking at the code but not quite sure what to do with it.

```
2017-04-05 02:30:41,945 [http-apr-8080-exec-1] WARN  authenticator.RemoteUserAuthenticatorService  - Remote user found [user@example.com]
2017-04-05 02:30:41,947 [http-apr-8080-exec-1] WARN  authenticator.RemoteUserAuthenticatorService  - User exists null ? 
2017-04-05 02:30:41,947 [http-apr-8080-exec-1] WARN  authenticator.RemoteUserAuthenticatorService  - for username: user@example.com
2017-04-05 02:30:41,947 [http-apr-8080-exec-1] WARN  authenticator.RemoteUserAuthenticatorService  - User does not exist so creating new user.
2017-04-05 02:30:41,968 [http-apr-8080-exec-1] WARN  authenticator.RemoteUserAuthenticatorService  - User created org.bbop.apollo.User : 23
2017-04-05 02:30:41,969 [http-apr-8080-exec-1] ERROR authenticator.RemoteUserAuthenticatorService  - Problem authenticating: org.apache.shiro.authc
.AuthenticationException: Authentication failed for token submission [org.apache.shiro.authc.UsernamePasswordToken - user@example.com, rememberMe=f
alse].  Possible unexpected error? (Typical or expected login exceptions should extend from AuthenticationException).
2017-04-05 02:30:41,969 [http-apr-8080-exec-1] ERROR authenticator.RemoteUserAuthenticatorService  - Failed to authenticate user user@example.com, 
resaving password and forcing
2017-04-05 02:30:41,970 [http-apr-8080-exec-1] WARN  authenticator.RemoteUserAuthenticatorService  - reset password and saving: null
2017-04-05 02:30:41,971 [http-apr-8080-exec-1] WARN  authenticator.RemoteUserAuthenticatorService  - logging in again
2017-04-05 02:30:41,989 [http-apr-8080-exec-1] ERROR errors.GrailsExceptionResolver  - NullPointerException occurred when processing request: [GET]
 /user/checkLogin
Stacktrace follows:
java.lang.NullPointerException
        at org.apache.shiro.crypto.hash.SimpleHash.hash(SimpleHash.java:229)
        at org.apache.shiro.crypto.hash.SimpleHash.<init>(SimpleHash.java:178)
        at org.apache.shiro.authc.credential.HashedCredentialsMatcher.hashProvidedCredentials(HashedCredentialsMatcher.java:445)
        at org.apache.shiro.authc.credential.HashedCredentialsMatcher.hashProvidedCredentials(HashedCredentialsMatcher.java:412)
        at org.apache.shiro.authc.credential.HashedCredentialsMatcher.doCredentialsMatch(HashedCredentialsMatcher.java:379)
        at org.bbop.apollo.DbRealm.authenticate(DbRealm.groovy:37)
        at org.apache.shiro.grails.RealmWrapper.getAuthenticationInfo(RealmWrapper.groovy:59)
        at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doSingleRealmAuthentication(ModularRealmAuthenticator.java:180)
        at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doAuthenticate(ModularRealmAuthenticator.java:267)
        at org.apache.shiro.authc.AbstractAuthenticator.authenticate(AbstractAuthenticator.java:198)
        at org.apache.shiro.mgt.AuthenticatingSecurityManager.authenticate(AuthenticatingSecurityManager.java:106)
        at org.apache.shiro.mgt.DefaultSecurityManager.login(DefaultSecurityManager.java:270)
        at org.apache.shiro.subject.support.DelegatingSubject.login(DelegatingSubject.java:256)
        at org.bbop.apollo.authenticator.RemoteUserAuthenticatorService.$tt__authenticate(RemoteUserAuthenticatorService.groovy:99)
        at org.bbop.apollo.PermissionService.$tt__authenticateWithToken(PermissionService.groovy:558)
        at org.bbop.apollo.UserController.$tt__checkLogin(UserController.groovy:159)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by erasche** [comment]
Looks like the user metadata isn't being set / saved.

**Comment by erasche** [comment]
I think this fixes it, but not 100% sure yet and it circumvents

```diff
             user.passwordHash = passwordHash
             log.warn("reset password and saving: " + user.getMetaData(INTERNAL_PASSWORD))
             user.save(flush: true, failOnError: true, insert: false)
-            authToken.password = user.getMetaData(INTERNAL_PASSWORD)
+            authToken.password = randomPassword
             log.warn("logging in again")
             subject.login(authToke44n)
```

should  `user.addMetaData` do something to mutate the user's `metadata` attribute? Not quite sure how to do that since it's a jsonobject, but I'm guessing it is something like:

```diff
      JSONObject addMetaData(String key,String value){                                                                                             
          validateMetaData()                                                                                                                       
          JSONObject jsonObject = JSON.parse(metadata) as JSONObject
          jsonObject.put(key,value)
+         metadata = jsonObject                                                                                                                    
          return jsonObject                                                                                                                        
      }                                                                                                                                            
```

**Comment by nathandunn** [comment]
Yeah, you are right.  I think I should add a unit test for this, but I think that this fixes it.

**Comment by nathandunn** [comment]
@erasche  Take a look at my latest PR.    I added a test, but your second fix is correct, though your first test is redundant (I hope):

```diff
             user.passwordHash = passwordHash
             log.warn("reset password and saving: " + user.getMetaData(INTERNAL_PASSWORD))
             user.save(flush: true, failOnError: true, insert: false)
+ // this was identical to the call below
            authToken.password = user.getMetaData(INTERNAL_PASSWORD)
             log.warn("logging in again")
             subject.login(authToken)
```

should  `user.addMetaData` do something to mutate the user's `metadata` attribute? Not quite sure how to do that since it's a jsonobject, but I'm guessing it is something like:

```diff
      JSONObject addMetaData(String key,String value){                                                                                             
          validateMetaData()                                                                                                                       
          JSONObject jsonObject = JSON.parse(metadata) as JSONObject
          jsonObject.put(key,value)
+         metadata = jsonObject.toString()                                                                                                                    
          return jsonObject                                                                                                                        
      }                                                                                                                                            
```

**Comment by erasche** [comment]
Confirmed, https://github.com/GMOD/Apollo/pull/1541 works perfectly. Thank you!

**Comment by nathandunn** [comment]
Perfect.  Thanks for debugging it.  Shame on me for not adding a test earlier!
