### ISSUE TITLE
Users with view but not write don't get notification that they cnnot create annotations

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#1643]
* Search [mailing list](http://gmod.827538.n3.nabble.com/Apollo-f815553.html) or email list ```apollo@lists.lbl.gov``` if a general setup question. 

* Provide what you were doing and what you expected to see.  Screenshots, directory, config files are a plus if relevant.
 ```text
I am testing user permission use cases.  This test was for a user with view but not write.  
As expected, the user could see but not create annotations. The interface allows click to highlight 
and right click to create (and the option to drag to the User-Created Annotations panel).  Since the 
options are visible and not greyed out, the impression is that the user should be able to perform 
the action.  

My expectation is that if a user has view but not write, they should be able to see the User-Created 
Annotations track, but options to create annotations, either through clicking and dragging or right 
clicking should not be available. 
```
* Provide the javascript console log output generated from the action. 
```text
 No errors present in console or in the Apollo interface
```
* Provide the server log output generated from the action (typically ```catalina.out```).
 ```shell
2017-06-13 11:37:35,022 [clientInboundChannel-3] ERROR springwebsocket.GrailsSimpAnnotationMethodMessageHandler  - Unhandled exception
java.lang.reflect.InvocationTargetException
	at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4$_closure5$_closure6.doCall(AnnotationEditorController.groovy:1145)
	at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4$_closure5.doCall(AnnotationEditorController.groovy:1144)
	at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4.doCall(AnnotationEditorController.groovy:1140)
	at groovyx.gpars.group.PGroup$3.call(PGroup.java:289)
	at groovyx.gpars.group.PGroup$4.run(PGroup.java:313)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.bbop.apollo.AnnotationException: You have insufficient permissions [read < write] to perform this operation
	at org.bbop.apollo.PermissionService.$tt__checkPermissions(PermissionService.groovy:340)
	at org.bbop.apollo.RequestHandlingService.$tt__addTranscript(RequestHandlingService.groovy:624)
	... 8 more
```

**Comment by nathandunn** [comment]
👍  for following directions ;)

Yeah, that should get bubbled up.

**Comment by childers** [comment]
@nathandunn Was this pulled into master already? I see the same behavior, where it looks like I can annotate, but silently fails with only an update in catalina.out.  Is this the expected behavior?

```shell
2017-06-14 17:17:06,861 [clientInboundChannel-2] ERROR springwebsocket.GrailsSimpAnnotationMethodMessageHandler  - Unhandled exception
java.lang.reflect.InvocationTargetException
	at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4$_closure5$_closure6.doCall(AnnotationEditorController.groovy:1146)
	at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4$_closure5.doCall(AnnotationEditorController.groovy:1145)
	at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4.doCall(AnnotationEditorController.groovy:1141)
	at groovyx.gpars.group.PGroup$3.call(PGroup.java:289)
	at groovyx.gpars.group.PGroup$4.run(PGroup.java:313)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.bbop.apollo.AnnotationException: You have insufficient permissions [read < write] to perform this operation
	at org.bbop.apollo.PermissionService.$tt__checkPermissions(PermissionService.groovy:340)
	at org.bbop.apollo.RequestHandlingService.$tt__addTranscript(RequestHandlingService.groovy:623)
	... 8 more
```

**Comment by nathandunn** [comment]
If you open your developer tab and go to the network tab and type “disable cache”:

1 - does it now work after reload?
2 - If not, what do you see in the console?  
3 - if nothing, what do you see in the web service (ws) network console under the frames tab?

**Comment by nathandunn** [comment]
Never mind.  I’m seeing the same thing.   

It *was* working perfectly and the bug fix seems to be in there.   I’ll try to see what is going on.

**Comment by nathandunn** [comment]
Retested using run-local and it runs perfectly.   Failed on icebox, though.  Retesting by deploying locally.

**Comment by nathandunn** [comment]
Confirmed when deployed as a war file into tomcat it produces the error above.   Looking into fix.
