### ISSUE TITLE
Broken 'Region Sequence' display in information displayer for HTMLFeatures and CanvasFeatures

### ISSUE THREAD

**Issue by deepakunni3** [GMOD/Apollo#1650]
For evidence tracks, if I right click on a feature and 'View Details' (HTMLFeatures) or click on a feature (CanvasFeatures) the information displayer popup fails to show sequences for features and sub-features.

![screen shot 2017-06-15 at 2 53 27 pm](https://user-images.githubusercontent.com/4530272/27199097-6ace57d2-51da-11e7-8d28-46493ceaea61.png)

The console had the following stack trace:
```
:8090/apollo/401799428141777716028978702/jbrowse/src/dojo/promise/instrumentation.js:20 TypeError: Cannot read property 'indexOf' of undefined
    at Object.renderRefSeqName (:8090/apollo/401799428141777716028978702/jbrowse/src/JBrowse/Util.js:36)
    at Object.renderText (:8090/apollo/401799428141777716028978702/jbrowse/plugins/WebApollo/js/View/Projection/FASTA.js:36)
    at Object.renderHTML (:8090/apollo/401799428141777716028978702/jbrowse/src/JBrowse/View/FASTA.js:33)
    at Object.<anonymous> (:8090/apollo/401799428141777716028978702/jbrowse/plugins/WebApollo/js/View/Track/DraggableHTMLFeatures.js:196)
    at :8090/apollo/401799428141777716028978702/jbrowse/src/dojo/_base/lang.js:375
    at :8090/apollo/401799428141777716028978702/jbrowse/src/JBrowse/Store/SeqFeature.js:182
    at signalListener (:8090/apollo/401799428141777716028978702/jbrowse/src/dojo/Deferred.js:37)
    at signalWaiting (:8090/apollo/401799428141777716028978702/jbrowse/src/dojo/Deferred.js:28)
    at Deferred.resolve (:8090/apollo/401799428141777716028978702/jbrowse/src/dojo/Deferred.js:192)
    at :8090/apollo/401799428141777716028978702/jbrowse/src/dojo/promise/all.js:68 "TypeError: Cannot read property 'indexOf' of undefined
    at Object.renderRefSeqName (http://localhost:8090/apollo/401799428141777716028978702/jbrowse/src/JBrowse/Util.js:36:23)
    at Object.renderText (http://localhost:8090/apollo/401799428141777716028978702/jbrowse/plugins/WebApollo/js/View/Projection/FASTA.js:36:33)
    at Object.renderHTML (http://localhost:8090/apollo/401799428141777716028978702/jbrowse/src/JBrowse/View/FASTA.js:33:25)
    at Object.<anonymous> (http://localhost:8090/apollo/401799428141777716028978702/jbrowse/plugins/WebApollo/js/View/Track/DraggableHTMLFeatures.js:196:34)
    at http://localhost:8090/apollo/401799428141777716028978702/jbrowse/src/dojo/_base/lang.js:375:55
    at http://localhost:8090/apollo/401799428141777716028978702/jbrowse/src/JBrowse/Store/SeqFeature.js:182:31
    at signalListener (http://localhost:8090/apollo/401799428141777716028978702/jbrowse/src/dojo/Deferred.js:37:21)
    at signalWaiting (http://localhost:8090/apollo/401799428141777716028978702/jbrowse/src/dojo/Deferred.js:28:4)
    at Deferred.resolve (http://localhost:8090/apollo/401799428141777716028978702/jbrowse/src/dojo/Deferred.js:192:5)
    at http://localhost:8090/apollo/401799428141777716028978702/jbrowse/src/dojo/promise/all.js:68:16
    ----------------------------------------
    rejected at signalDeferred (http://localhost:8090/apollo/401799428141777716028978702/jbrowse/src/dojo/Deferred.js:84:15)
    at signalListener (http://localhost:8090/apollo/401799428141777716028978702/jbrowse/src/dojo/Deferred.js:55:5)
    at signalWaiting (http://localhost:8090/apollo/401799428141777716028978702/jbrowse/src/dojo/Deferred.js:28:4)
    at Deferred.resolve (http://localhost:8090/apollo/401799428141777716028978702/jbrowse/src/dojo/Deferred.js:192:5)
    at http://localhost:8090/apollo/401799428141777716028978702/jbrowse/src/dojo/promise/all.js:68:16
    at signalListener (http://localhost:8090/apollo/401799428141777716028978702/jbrowse/src/dojo/Deferred.js:37:21)
    at signalWaiting (http://localhost:8090/apollo/401799428141777716028978702/jbrowse/src/dojo/Deferred.js:28:4)
    at Deferred.resolve (http://localhost:8090/apollo/401799428141777716028978702/jbrowse/src/dojo/Deferred.js:192:5)
    at signalListener (http://localhost:8090/apollo/401799428141777716028978702/jbrowse/src/dojo/Deferred.js:37:21)
    at signalWaiting (http://localhost:8090/apollo/401799428141777716028978702/jbrowse/src/dojo/Deferred.js:28:4)
    ----------------------------------------
Error
    at Promise.Deferred.then.promise.then (http://localhost:8090/apollo/401799428141777716028978702/jbrowse/src/dojo/Deferred.js:252:24)
    at Object.getFeatures (http://localhost:8090/apollo/401799428141777716028978702/jbrowse/src/JBrowse/Store/SeqFeature/SequenceChunks.js:108:24)
    at Object.getReferenceSequence (http://localhost:8090/apollo/401799428141777716028978702/jbrowse/src/JBrowse/Store/SeqFeature.js:175:14)
    at Object.<anonymous> (http://localhost:8090/apollo/401799428141777716028978702/jbrowse/plugins/WebApollo/js/View/Track/DraggableHTMLFeatures.js:181:33)
    at http://localhost:8090/apollo/401799428141777716028978702/jbrowse/src/dojo/_base/lang.js:375:55
    at Object.getStore (http://localhost:8090/apollo/401799428141777716028978702/jbrowse/src/JBrowse/Browser.js:1725:9)
    at Object._renderUnderlyingReferenceSequence (http://localhost:8090/apollo/401799428141777716028978702/jbrowse/plugins/WebApollo/js/View/Track/DraggableHTMLFeatures.js:178:27)
    at Object.defaultFeatureDetail (http://localhost:8090/apollo/401799428141777716028978702/jbrowse/src/JBrowse/View/Track/_FeatureDetailMixin.js:80:14)
    at HTMLDivElement.<anonymous> (http://localhost:8090/apollo/401799428141777716028978702/jbrowse/src/dojo/_base/lang.js:373:45)
    at Object._evalConf (http://localhost:8090/apollo/401799428141777716028978702/jbrowse/src/JBrowse/View/Track/BlockBased.js:966:35)"
```

This was observed in both normal orientation as well as reverse complement orientation.

**Comment by nathandunn** [comment]
@deepakunni3   This is fixed, though it was a JBrowse fix.

https://github.com/nathandunn/jbrowse/commit/3a593488b307d7a9a700227b5abf3c2f1a2af499

Let me know if this also fixes it for you.

**Comment by nathandunn** [comment]
@deepakunni3  Also, if you have a better way to do this integration or branch naming.

**Comment by deepakunni3** [comment]
Tested by using https://github.com/nathandunn/Apollo/tree/projection_v2_server as the JBrowse and it works 👍
