### ISSUE TITLE
Unstable instance on 1.0.4-SNAPSHOT

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#170]
The instances on our staging environments are unstable, and catalina.out has the following errors, one for each instance.  Have you seen this before?:
``` bash
2015-02-18 08:07:08,492 ERROR Could not unregister MBeans for org.apache.logging.log4j2:type="WebappClassLoader\n  context: /agrpla\n  delegate: false\n  repositories:\n    /WEB-INF/classes/\n----------> Parent Classloader:\norg.apache.catalina.loader.StandardClassLoader@682ea4b1\n",component=Appenders,name=* javax.management.InstanceNotFoundException: org.apache.logging.log4j2:type="WebappClassLoader\n  context: /agrpla\n  delegate: false\n  repositories:\n    /WEB-INF/classes/\n----------> Parent Classloader:\norg.apache.catalina.loader.StandardClassLoader@682ea4b1\n",component=Appenders,name=Console
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.exclusiveUnregisterMBean(DefaultMBeanServerInterceptor.java:427)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.unregisterMBean(DefaultMBeanServerInterceptor.java:415)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.unregisterMBean(JmxMBeanServer.java:546)
        at org.apache.logging.log4j.core.jmx.Server.unregisterAllMatching(Server.java:312)
        at org.apache.logging.log4j.core.jmx.Server.unregisterAppenders(Server.java:285)
        at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:237)
        at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:217)
        at org.apache.logging.log4j.core.LoggerContext.stop(LoggerContext.java:225)
        at org.apache.logging.log4j.core.LoggerContext$ShutdownThread.run(LoggerContext.java:482)
        at java.lang.Thread.run(Thread.java:724)
```

**Comment by nathandunn** [comment]
I have not seen it but I also don't run jmx.  What version are you using and how is it unstable?  We are on 1.0.4rc2 and will probably have an rc3.

**Comment by childers** [comment]
Sorry, I think this was caused by another out of memory error. I'm looking at RC2 on our staging machine, but am having other problems with it.

**Comment by nathandunn** [comment]
I am available on Skype if need be.

**Comment by nathandunn** [comment]
@childers   I added you back.  Was going to assign you, but no matter.  Just update the status when you are ready.

**Comment by childers** [comment]
Thanks, since this might be resolved already, I'll close it now, and it will hopefully not resurface.

**Comment by nathandunn** [comment]
@childers

Are you still planning on testing RC2 in the staging environment? 

Nathan
