### ISSUE TITLE
Apollo client being initialized twice

### ISSUE THREAD

**Issue by deepakunni3** [GMOD/Apollo#1742]
I see the following on the Apollo 2.0.7 demo:

![screen shot 2017-08-31 at 2 28 50 pm](https://user-images.githubusercontent.com/4530272/29941654-e3281eb0-8e58-11e7-92ac-db9c23089672.png)

Note how there are redundant options in the View menu.

The console gives the following error:
```
Browser.js:1981 Error: Tried to register widget with id==menubar_powered_by_jbrowse but that id is already registered Error: Tried to register widget with id==menubar_powered_by_jbrowse but that id is already registered
    at Object.add (http://demo.genomearchitect.org/Apollo-staging/4126658216003575441700795384/jbrowse/src/dijit/registry.js:26:11)
    at Object.create (http://demo.genomearchitect.org/Apollo-staging/4126658216003575441700795384/jbrowse/src/dijit/_WidgetBase.js:428:13)
    at Object.postscript (http://demo.genomearchitect.org/Apollo-staging/4126658216003575441700795384/jbrowse/src/dijit/_WidgetBase.js:366:9)
    at new <anonymous> (http://demo.genomearchitect.org/Apollo-staging/4126658216003575441700795384/jbrowse/src/dojo/_base/declare.js:406:7)
    at Object.postCreateMenus (http://demo.genomearchitect.org/Apollo-staging/4126658216003575441700795384/jbrowse/plugins/WebApollo/js/main.js:718:33)
    at http://demo.genomearchitect.org/Apollo-staging/4126658216003575441700795384/jbrowse/plugins/WebApollo/js/main.js:222:23
    at http://demo.genomearchitect.org/Apollo-staging/4126658216003575441700795384/jbrowse/src/JBrowse/Browser.js:1979:29
    at signalListener (http://demo.genomearchitect.org/Apollo-staging/4126658216003575441700795384/jbrowse/src/dojo/Deferred.js:37:21)
    at signalWaiting (http://demo.genomearchitect.org/Apollo-staging/4126658216003575441700795384/jbrowse/src/dojo/Deferred.js:28:4)
    at Deferred.resolve (http://demo.genomearchitect.org/Apollo-staging/4126658216003575441700795384/jbrowse/src/dojo/Deferred.js:192:5) Error: Tried to register widget with id==menubar_powered_by_jbrowse but that id is already registered
    at Object.add (registry.js:26)
    at Object.create (_WidgetBase.js:428)
    at Object.postscript (_WidgetBase.js:366)
    at new <anonymous> (declare.js:406)
    at Object.postCreateMenus (main.js:718)
    at main.js:222
    at Browser.js:1979
    at signalListener (Deferred.js:37)
    at signalWaiting (Deferred.js:28)
    at Deferred.resolve (Deferred.js:192)
```

**Comment by deepakunni3** [comment]
@nathandunn I see this for Volvox but not in Human. So perhaps has to do with the trackList.json configuration?

**Comment by nathandunn** [comment]
@deepakunni3  I'll try a few things.

**Comment by nathandunn** [comment]
Well, that was fast.    The plugins was defined in trackList.json, which was duplicated:

```
   "plugins" : [ 
      "NeatHTMLFeatures", 
      "NeatCanvasFeatures", 
      "HideTrackLabels" 
   ] 
```

**Comment by nathandunn** [comment]
removing it seems to fix the error, but perhaps we should just detect and remove the duplication?

**Comment by nathandunn** [comment]
This should be working though if you look into ```apollo-config.groovy```

**Comment by nathandunn** [comment]
<img width="528" alt="screen shot 2017-08-31 at 1 10 48 pm" src="https://user-images.githubusercontent.com/751274/29943301-e0c8107c-8e4d-11e7-9b02-362d7a83e22f.png">

**Comment by nathandunn** [comment]
I'm guess its the difference between String vs JSON objects confusing something.

**Comment by nathandunn** [comment]
When I don't include "plugins" in the JSON it is fine and includes the other plugins automatically.

<img width="550" alt="screen shot 2017-08-31 at 2 27 37 pm" src="https://user-images.githubusercontent.com/751274/29946041-9075369e-8e58-11e7-8964-38d2688bcf36.png">

When I do, it includes apollo twice, even though its not the one I was trying to include, so somehow its getting triggered.

<img width="512" alt="screen shot 2017-08-31 at 2 26 57 pm" src="https://user-images.githubusercontent.com/751274/29946042-907bbf3c-8e58-11e7-8b89-95f36df2bcad.png">

Oddly, the code returned from trackList.json in JBrowseController looks flawless, so I think it must somehow be getting around it, but its unclear how.

**Comment by nathandunn** [comment]
The "trackList.json" object returned from the server is correct.

**Comment by deepakunni3** [comment]
@nathandunn That might be because `annot.json` is the one that is including the WebApollo plugin.
https://github.com/GMOD/Apollo/blob/master/client/apollo/json/annot.json#L4

**Comment by nathandunn** [comment]
Oh . . right the includes.  We’ll see.  Its very bizarre as I can include *any* plugin in the JBrowse file and I get this behavior.

**Comment by deepakunni3** [comment]
Oh thats odd.

**Comment by nathandunn** [comment]
I think you are right, though.  Its included in `apollo-config.groovy` so it can’t compare the plugin keys.  I think I just need to change the sample files so it doesn’t suggest an overlap.

**Comment by nathandunn** [comment]
Reverified that this is only appearing once:

<img width="365" alt="screen shot 2017-09-01 at 2 10 49 pm" src="https://user-images.githubusercontent.com/751274/29987915-676a1d24-8f1f-11e7-8464-5a37f7f249a6.png">
