### ISSUE TITLE
Problem installing Apollo 2.0.7 - JBrowse panel is blanck - JS error with JSON - run-local

### ISSUE THREAD

**Issue by diriano** [GMOD/Apollo#1790]
Dear all,

I hope someone could help me.

I am trying to install apollo-2.0.7. But I have not been able to successfully have the test server properly running.
It can start, but when I go to http://localhost:8085/apollo, the left side panel wiehte Jbrowse should appear is blank (see attached screenshot) and there is the following error in the js console:

    Uncaught Huf: "Error parsing JSON: SyntaxError: Unexpected token ' in JSON at position 1"g: null__gwt$backingJsError: Error: Error parsing JSON: SyntaxError: Unexpected token ' in JSON at position 1
     at Th.Qh [as Hb] (annotator-0.js:3307:31)
     at Hh (annotator-0.js:837:26)
     at mg (annotator-0.js:1455:25)
     at Hu.tg (annotator-0.js:831:25)
     at Hu.vg (annotator-0.js:697:19)
     at new Hu (annotator-0.js:721:19)
     at Lv (annotator-0.js:720:22)
     at Jv (annotator-0.js:2887:66)
     at Kv (annotator-0.js:2905:114)
     at MIb.OIb [as fc] (annotator-0.js:3311:18263)
     at fs (annotator-0.js:2317:79)
     at ts.us [as dc] (annotator-0.js:3308:3378)
     at XMLHttpRequest.eval (annotator-0.js:2160:65)
     at ah (annotator-0.js:1505:29)
     at eh (annotator-0.js:2037:44)
     at XMLHttpRequest.eval (annotator-0.js:2695:50)message: "Error parsing JSON: SyntaxError: Unexpected token ' in JSON at position 1"stack: "Error: Error parsing JSON: SyntaxError: Unexpected token ' in JSON at position 1↵    at Th.Qh [as Hb] (annotator-0.js:3307:31)↵    at Hh (annotator-0.js:837:26)↵    at mg (annotator-0.js:1455:25)↵    at Hu.tg (annotator-0.js:831:25)↵    at Hu.vg (annotator-0.js:697:19)↵    at new Hu (annotator-0.js:721:19)↵    at Lv (annotator-0.js:720:22)↵    at Jv (annotator-0.js:2887:66)↵    at Kv (annotator-0.js:2905:114)↵    at MIb.OIb [as fc] (annotator-0.js:3311:18263)↵    at fs (annotator-0.js:2317:79)↵    at ts.us [as dc] (annotator-0.js:3308:3378)↵    at XMLHttpRequest.eval (annotator-0.js:2160:65)↵    at ah (annotator-0.js:1505:29)↵    at eh (annotator-0.js:2037:44)↵    at XMLHttpRequest.eval (annotator-0.js:2695:50)"__proto__: Object__proto__: cM: {4: 1, 27: 1, 30: 1, 39: 1}cZ: gjb {k: "com.google.gwt.json.client.JSONException", i: "JSONException", g: "com.google.gwt.json.client", d: "JSONException", b: "com.google.gwt.json.client.JSONException", …}constructor: {cM: {…}, constructor: {…}, cZ: gjb}__proto__: Object

I have installed all pre-requirements following the instructions.

I am using:
Node Version: 6
Npm Version: 3
javac 1.8.0_144

When I run ./apollo run-local 8085, I do not get any errors, only the following warning:

##############

    Warning The [removeIncludedPlugins] action accepts a parameter of type [org.codehaus.groovy.grails.web.json.JSONArray] which has not been marked with @Validateable. Data binding will still be applied to this command object but the instance will not be validateable.

       def removeIncludedPlugins(JSONArray pluginsArray) {
##############

There are no other messages that might cause worry.

The file setup.log, has a message, that does not look good, but I am not sure, why it is appearing, and what could be the cause and the effect:

    Configuring /usr/local/Bioinf/Apollo-2.0.7/web-app/jbrowse ... Can't parse version 'dev'
    Can't parse version 'dev'

I will very much appreciate it if someone can give ma hint about what is going on and hot to fix it.

Best,

Diego
![screen shot 2017-10-17 at 10 42 04 pm](https://user-images.githubusercontent.com/13472703/31695941-72dcb7b6-b38c-11e7-86a2-63ba5c441f16.png)

**Comment by diriano** [comment]
Upgrading to node v8, as suggested in #1756 DOES NOT fix the issue.

**Comment by diriano** [comment]
I also realized that most (perhaps all) of the node modules in "jbrowse-download/node_modules", are not being "deployed" in the web-app under "web-app/jbrowse/src/"

**Comment by deepakunni3** [comment]
@diriano We have had issues with our 2.0.7 release and are in the process of preparing a new release.
In the mean time, you could perhaps clone Apollo from the master branch and make use of the latest changes that we have in there.

**Comment by nathandunn** [comment]
I agree with @deepakunni3 .  

However, also in your `apollo-config.groovy` you need to make sure you're not using the older tag.  If you specify nothing it should be fine.  If you define a tag (e.g., you want to install JBrowse plugins), the config should look like this, defining either the tag or the branch: 

https://github.com/GMOD/Apollo/blob/2.0.7/sample-postgres-apollo-config.groovy#L113

**Comment by diriano** [comment]
Thanks for your reply @deepakunni3  and @nathandunn.

I still have the exact same error.

I tried using Apollo from the master branch, and I am not using apollo-config.groovy yet. In that way jbrowse tag:17111e6da6677085f1aeed41216fb558b63ed7ad was installed.

Using 
Node Version: 8
Npm Version: 5
javac 1.8.0_144 found
sdkman 5.5.12+269
groovy 2.4.12
grails 2.5.5
gradle 2.11

Shall I update groovy/grails/gradle? Which versions are recommended?

Still the js code is not being copied to web-app/jbrowse/src/

Also tried with the older version of Node.js (v6) with same results.

Other ideas?

**Comment by nathandunn** [comment]
So, a couple of things to try.   If you’ve checked out a clean master branch, then let’s stick with that. 

I would:

- Update gradle to use 3.5 (via sdkman) then: ./apollo clean-all && ./apollo deploy

If you want to test it locally first, you can do ./apollo run-local instead of ./apollo deploy.

Also, do you see the same problem AFTER you’ve added an organism?

Nathan

**Comment by diriano** [comment]
Thanks for the suggestion, unfortunately that does not fix the issue.

I used ./apollo deploy with a MySQL DB

I used node 8 and gradle 3.5. Same exact error.

The pic shows the errors that appear when I add organisms.
node modules in "jbrowse-download/node_modules are not being copied to the deployed webapp.

![screen shot 2017-10-18 at 6 19 12 pm](https://user-images.githubusercontent.com/13472703/31740899-6dacffda-b431-11e7-9aa2-03c7b4ce2cb1.png)

**Comment by nathandunn** [comment]
Can you:

1 - ./apollo clean-all
2 - confirm that the target, jrowse-download and web-app/jbrowse directories have all been removed.
3 - do an ./apollo deploy and provide the entire log of the deploy process

We had run into the problem earlier that npm was picking up the system node instead of the nvm installed one.  

It wouldn’t hurt to remove the npm cache, but we can look at your error logs first.

**Comment by nathandunn** [comment]
If this is still a problem, please re-open
