### ISSUE TITLE
Error when annotating more than 20 isoforms.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#18]
From Monical Poelchau: 
"One of our annotators is working on a gene model with ~20 isoforms. When attempting to drag more evidence into the user-created annotations track in the area of this gene model, we get the error 'Error writing transcript:null'. Catalina.out output is pasted below."

java.lang.NullPointerException
        at org.gmod.gbol.bioObject.CDS.overlaps(CDS.java:187)
        at org.bbop.apollo.web.overlap.OrfOverlapper.overlaps(OrfOverlapper.java:28)
        at org.bbop.apollo.web.overlap.OrfOverlapper.overlaps(OrfOverlapper.java:17)
        at org.bbop.apollo.web.AnnotationEditorService.addTranscript(AnnotationEditorService.java:3892)
        at org.bbop.apollo.web.AnnotationEditorService.addTranscript(AnnotationEditorService.java:1202)
        at org.bbop.apollo.web.AnnotationEditorService.addTranscript(AnnotationEditorService.java:1186)
        at org.bbop.apollo.web.AnnotationEditorService.doPost(AnnotationEditorService.java:403)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:129)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:724)

**Comment by nathandunn** [comment]
I believe that this is related to the bug where if there is too many isoforms it becomes impossible to drag in the first place.
