### ISSUE TITLE
problems deleting users. Is it because they are members of a group?

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#1810]
* Search [mailing list](http://gmod.827538.n3.nabble.com/Apollo-f815553.html) or email list ```apollo@lists.lbl.gov``` if a general setup question. 

* Provide what you were doing and what you expected to see.  Screenshots, directory, config files are a plus if relevant.
 Trying to delete a user, both through the Apollo interface and through the terminal.
I think this is due to the schema, based on the dable definition and the error:
```shell 
=> delete from grails_user where username like 'd%';
ERROR:  update or delete on table "grails_user" violates foreign key constraint "fk_jppito7humh6e3v5mjjtutd7h" on table "user_group_users"
DETAIL:  Key (id)=(1356571) is still referenced from table "user_group_users".
```

It looks like the users table has a foreign key constraint, but is not set to cascade on delete, which means that once a user is added to a group, you have to remove the user form the group, then you can delete the user.  This gets old fast if you want to remove more than a few users at once.  When I tried removing a user through the apollo interface, it failed with an error saying it could not delete user null. Reloading and the user is gone. I'm not sure what to make of that.

Catalina.out is at the bottom.

The table definition looks like this:
```shell
\d grails_user;
             Table "public.grails_user"
    Column     |          Type          | Modifiers 
---------------+------------------------+-----------
 id            | bigint                 | not null
 version       | bigint                 | not null
 first_name    | character varying(255) | not null
 last_name     | character varying(255) | not null
 metadata      | character varying(255) | 
 password_hash | character varying(255) | not null
 username      | character varying(255) | not null
Indexes:
    "grails_user_pkey" PRIMARY KEY, btree (id)
    "uk_rdmcxcj6i53kfjmb9j811ta1m" UNIQUE CONSTRAINT, btree (username)
Referenced by:
    TABLE "feature_event" CONSTRAINT "fk_35nc3xd2axx6fwyap4bjkt09u" FOREIGN KEY (editor_id) REFERENCES grails_user(id)
    TABLE "permission" CONSTRAINT "fk_6p3mx8al2w4f7ltqiwf1j88fm" FOREIGN KEY (user_id) REFERENCES grails_user(id)
    TABLE "user_group_users" CONSTRAINT "fk_jppito7humh6e3v5mjjtutd7h" FOREIGN KEY (user_id) REFERENCES grails_user(id)
    TABLE "grails_user_roles" CONSTRAINT "fk_jsuq1rc9mb07tg4kubnqn8yw6" FOREIGN KEY (user_id) REFERENCES grails_user(id)
    TABLE "feature_grails_user" CONSTRAINT "fk_lflwbgxduee8ljjwe5rfbdil2" FOREIGN KEY (user_id) REFERENCES grails_user(id)
    TABLE "preference" CONSTRAINT "fk_ro87rogww8hoobbwya2nn16xk" FOREIGN KEY (user_id) REFERENCES grails_user(id)
```

* Provide the javascript console log output generated from the action. 
 N/A
* Provide the server log output generated from the action (typically ```catalina.out```).
 

Catalina.out looked like this:
```shell
2017-11-14 15:35:01,160 [http-nio-8080-exec-26] INFO  apollo.UserController  - Updating user
2017-11-14 15:35:01,218 [http-nio-8080-exec-26] INFO  apollo.UserController  - Updated user
2017-11-14 16:20:36,976 [http-nio-8080-exec-27] WARN  apollo.PreferenceService  - Multiple preferences found: 2
2017-11-14 16:20:58,769 [http-nio-8080-exec-26] WARN  apollo.PreferenceService  - Multiple preferences found: 2
2017-11-14 16:29:03,579 [http-nio-8080-exec-27] INFO  apollo.UserController  - Removing user
2017-11-14 16:29:03,658 [http-nio-8080-exec-27] ERROR apollo.UserController  - java.util.ConcurrentModificationException
2017-11-14 16:29:12,869 [http-nio-8080-exec-25] INFO  apollo.UserController  - updateTrackListPreference
2017-11-14 16:29:12,871 [http-nio-8080-exec-25] INFO  apollo.UserController  - Added userOrganismPreference false
/opt/apollo/440338-Drosophila ficusphila/extendedTrackList.json
14-Nov-2017 16:30:09.496 INFO [MessageBrokerSockJS-1] org.apache.coyote.AbstractProcessor.setErrorState An error occurred in processing while on a non-container thread. The connection will be closed immediately
 java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:134)
	at org.apache.tomcat.util.net.NioBlockingSelector.write(NioBlockingSelector.java:101)
	at org.apache.tomcat.util.net.NioSelectorPool.write(NioSelectorPool.java:157)
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1267)
	at org.apache.tomcat.util.net.SocketWrapperBase.doWrite(SocketWrapperBase.java:670)
	at org.apache.tomcat.util.net.SocketWrapperBase.flushBlocking(SocketWrapperBase.java:607)
	at org.apache.tomcat.util.net.SocketWrapperBase.flush(SocketWrapperBase.java:597)
	at org.apache.coyote.http11.Http11OutputBuffer.flushBuffer(Http11OutputBuffer.java:581)
	at org.apache.coyote.http11.Http11OutputBuffer.flush(Http11OutputBuffer.java:272)
	at org.apache.coyote.http11.Http11Processor.flush(Http11Processor.java:1560)
	at org.apache.coyote.AbstractProcessor.action(AbstractProcessor.java:283)
	at org.apache.coyote.Response.action(Response.java:173)
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:317)
	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:284)
	at org.apache.catalina.connector.Response.flushBuffer(Response.java:541)
	at org.apache.catalina.connector.ResponseFacade.flushBuffer(ResponseFacade.java:312)
	at org.springframework.http.server.ServletServerHttpResponse.flush(ServletServerHttpResponse.java:91)
	at org.springframework.web.socket.sockjs.transport.session.AbstractHttpSockJsSession.writeFrameInternal(AbstractHttpSockJsSession.java:345)
	at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.writeFrame(AbstractSockJsSession.java:325)
	at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.sendHeartbeat(AbstractSockJsSession.java:249)
	at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession$1.run(AbstractSockJsSession.java:269)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by nathandunn** [comment]
@childers Group membership doesn't make a difference for me.   True, you can't delete directly from the command-line but the API or the interface should work.

This looks like a web-socket error, but I'm unsure if it is causing a problem, unless its having a problem writing to disk.   However, it shouldn't be using web-sockets for this error anyway.

Are there no other errors in the javascript console or the catalina.out?

**Comment by nathandunn** [comment]
@childers  Any movement on this, or can I close it?

**Comment by nathandunn** [comment]
If this is still a problem, please re-open
