### ISSUE TITLE
URL params in new version of JBrowse not working once logged in

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#1840]
* Search [mailing list](http://gmod.827538.n3.nabble.com/Apollo-f815553.html) or email list ```apollo@lists.lbl.gov``` if a general setup question. 
This is a new issue for new functionality.
* Provide what you were doing and what you expected to see.  Screenshots, directory, config files are a plus if relevant.
 I was testing the URL params in the current JBrowse master as a part of the current Apollo master. This works great in the not logged in mode, but fails in different ways if authenticated.   If I click the 'login' button, the request fails with a 404.  

If I log in separately and try to load the URL param link, I get a failure to load the page.

* Provide the javascript console log output generated from the action. 

* Provide the server log output generated from the action (typically ```catalina.out```).
 on clicking login, catalina.out prints this message:
```shell
2018-01-10 16:04:07,711 [http-nio-8080-exec-20] ERROR authenticator.UsernamePasswordAuthenticatorService  - Problem authenticating: java.lang.IllegalArgumentException: Method argumet (authentication token) cannot be null.
2018-01-10 16:04:07,711 [http-nio-8080-exec-20] WARN  apollo.PermissionService  - Failed to authenticate user
2018-01-10 16:04:07,712 [http-nio-8080-exec-20] WARN  apollo.SecurityFilters  - Authentication failed
10-Jan-2018 16:04:07.727 INFO [http-nio-8080-exec-24] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
 java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:476)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:687)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```
If I log in on a different tab, then reload the tab with URL params, catalina.out prints this message:
```shell
2018-01-10 16:05:24,993 [http-nio-8080-exec-22] INFO  apollo.UserController  - Added userOrganismPreference false
2018-01-10 16:05:35,892 [http-nio-8080-exec-21] WARN  apollo.PreferenceService  - Multiple preferences found: 4
10-Jan-2018 16:05:37.915 INFO [http-nio-8080-exec-24] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
 java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:476)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:687)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by nathandunn** [comment]
Closing in favor of #1839
