### ISSUE TITLE
Apollo BUILD FAILED 

### ISSUE THREAD

**Issue by francicco** [GMOD/Apollo#1916]
Hi,

I'm trying to install Apollo, and because the `./apollo run-local` is failing I'm trying to understand why trying `./apollo deploy`, but I don't know how to fix this error.

Any help?
F

```
$ ./apollo deploy

Node Version: 10
Npm Version: 6
javac 1.8.0_172 found
javac installed
JDK 1.8 found: javac 1.8.0_172
cp: apollo-config.groovy: No such file or directory

> Configure project :
No log file found in classpath.
Final JBrowse settings [git:[url:https://github.com/gmod/jbrowse, tag:maint/1.12.5-apollo, alwaysPull:false, alwaysRecheck:false], plugins:[WebApollo:[included:true], RegexSequenceSearch:[included:true], HideTrackLabels:[included:true]]]
Final plugins [WebApollo:[included:true], RegexSequenceSearch:[included:true], HideTrackLabels:[included:true]]
Copying apollo plugin
Handling JBrowse release [git:[url:https://github.com/gmod/jbrowse, tag:maint/1.12.5-apollo, alwaysPull:false, alwaysRecheck:false], plugins:[WebApollo:[included:true], RegexSequenceSearch:[included:true], HideTrackLabels:[included:true]]]
Handling JBrowse [git:[url:https://github.com/gmod/jbrowse, tag:maint/1.12.5-apollo, alwaysPull:false, alwaysRecheck:false], plugins:[WebApollo:[included:true], RegexSequenceSearch:[included:true], HideTrackLabels:[included:true]]]
Setting up JBrowse... 

> Task :installJBrowse
Installing JBrowse [git:[url:https://github.com/gmod/jbrowse, tag:maint/1.12.5-apollo, alwaysPull:false, alwaysRecheck:false], plugins:[WebApollo:[included:true], RegexSequenceSearch:[included:true], HideTrackLabels:[included:true]]]

> Task :installJBrowsePlugins
Installing JBrowse plugins  [WebApollo:[included:true], RegexSequenceSearch:[included:true], HideTrackLabels:[included:true]]
Evaluating plugin WebApollo=[included:true]
Plugin jbrowse-download/plugins/WebApollo exists and appears valid.
Evaluating plugin RegexSequenceSearch=[included:true]
Plugin jbrowse-download/plugins/RegexSequenceSearch exists and appears valid.
Evaluating plugin HideTrackLabels=[included:true]
Plugin jbrowse-download/plugins/HideTrackLabels exists and appears valid.

> Task :copy.apollo.plugin.webapp
[ant:echo] Copying WebApollo plugin to jbrowse webapp ...

> Task :gwtc FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gwtc'.
> Java returned: 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 31s
10 actionable tasks: 9 executed, 1 up-to-date
***************************************
NOTE: Please set the memory for your servlet container (tomcat, jetty, etc.) or Apollo may not start correctly: http://genomearchitect.readthedocs.io/en/latest/Troubleshooting.html#suggested-tomcat-memory-settings
```

**Comment by childers** [comment]
Hi there,

It looks like the error is caused by a missing or misconfigured apollo-config.groovy file.  Can you check that your apollo-config.groovy looks good?  There are several example config files that you can use to set yours up.

**Comment by nathandunn** [comment]
@francicco  Can you use node 8 instead and see what happens?

https://github.com/creationix/nvm

**Comment by nathandunn** [comment]
Please re-open if you need to

**Comment by chibante** [comment]
Hi guys!
Using "./apollo run-local" command I'm having a similar problem (see tail massage below) and I couldn't resolve it with nodejs 8. And the apollo-config.groovy file is the next step from tutorial that I'm following (https://genomearchitect.readthedocs.io/en/2.0.8/Setup.html#production-pre-requisites). 
I try use --stacktrace option to get the stack trace and --info or --debug option to get more log output, but the same massage appeared.
Anyone have any other suggestions to solve this problem?

Thanks!
----------------------------------------------
....
:javac
> BuilFAILED 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gwtc'.
> Java returned: 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 1.761 secs
----------------------------------------------------------

**Comment by nathandunn** [comment]
Are you running 2.0.8?   I would recommend running against the newest release if at all possible.   The database should automatically update.  

Granted, it won’t necessarily fix the problem you are having.  

What do you see if you type:

./gradlew gwtc --stacktrace —info

**Comment by chibante** [comment]
I see the last version in this link `https://genomearchitect.readthedocs.io/en/latest/Setup.html` and seems like same steps up to this step of instalation. I'm in correct link of the last version?
I've tried the command `./gradlew gwtc --stacktrace —info` and the full result was this:
```
[carla@mendel Apollo]$ ./gradlew gwtc --stacktrace —info
No log file found in classpath.
Final JBrowse settings [git:[url:https://github.com/gmod/jbrowse, branch:1.15.4-release, alwaysPull:true, alwaysRecheck:true], plugins:[WebApollo:[included:true], RegexSequenceSearch:[included:true], HideTrackLabels:[included:true]]]
Final plugins [WebApollo:[included:true], RegexSequenceSearch:[included:true], HideTrackLabels:[included:true]]

FAILURE: Build failed with an exception.

* What went wrong:
Task '—info' not found in root project 'nathanApolloMaster'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.execution.TaskSelectionException: Task '—info' not found in root project 'nathanApolloMaster'.
	at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:100)
	at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:75)
	at org.gradle.execution.commandline.CommandLineTaskParser.parseTasks(CommandLineTaskParser.java:42)
	at org.gradle.execution.TaskNameResolvingBuildConfigurationAction.configure(TaskNameResolvingBuildConfigurationAction.java:44)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$000(DefaultBuildConfigurationActionExecuter.java:25)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.proceed(DefaultBuildConfigurationActionExecuter.java:54)
	at org.gradle.execution.DefaultTasksBuildExecutionAction.configure(DefaultTasksBuildExecutionAction.java:44)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$000(DefaultBuildConfigurationActionExecuter.java:25)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.proceed(DefaultBuildConfigurationActionExecuter.java:54)
	at org.gradle.execution.ExcludedTaskFilteringBuildConfigurationAction.configure(ExcludedTaskFilteringBuildConfigurationAction.java:47)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter.select(DefaultBuildConfigurationActionExecuter.java:36)
	at org.gradle.initialization.DefaultGradleLauncher$3.run(DefaultGradleLauncher.java:143)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:140)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:45)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)


BUILD FAILED

Total time: 3.322 secs
```
Thanks!

**Comment by nathandunn** [comment]
Info should have two dashes before it like stack trace.

Nathan

**Comment by chibante** [comment]
Oh, sorry... :)
```
[carla@mendel Apollo]$ ./gradlew gwtc --stacktrace --info
No log file found in classpath.
Final JBrowse settings [git:[url:https://github.com/gmod/jbrowse, branch:1.15.4-release, alwaysPull:true, alwaysRecheck:true], plugins:[WebApollo:[included:true], RegexSequenceSearch:[included:true], HideTrackLabels:[included:true]]]
Final plugins [WebApollo:[included:true], RegexSequenceSearch:[included:true], HideTrackLabels:[included:true]]

FAILURE: Build failed with an exception.

* What went wrong:
Task '—-info' not found in root project 'nathanApolloMaster'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.execution.TaskSelectionException: Task '—-info' not found in root project 'nathanApolloMaster'.
	at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:100)
	at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:75)
	at org.gradle.execution.commandline.CommandLineTaskParser.parseTasks(CommandLineTaskParser.java:42)
	at org.gradle.execution.TaskNameResolvingBuildConfigurationAction.configure(TaskNameResolvingBuildConfigurationAction.java:44)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$000(DefaultBuildConfigurationActionExecuter.java:25)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.proceed(DefaultBuildConfigurationActionExecuter.java:54)
	at org.gradle.execution.DefaultTasksBuildExecutionAction.configure(DefaultTasksBuildExecutionAction.java:44)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$000(DefaultBuildConfigurationActionExecuter.java:25)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.proceed(DefaultBuildConfigurationActionExecuter.java:54)
	at org.gradle.execution.ExcludedTaskFilteringBuildConfigurationAction.configure(ExcludedTaskFilteringBuildConfigurationAction.java:47)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter.select(DefaultBuildConfigurationActionExecuter.java:36)
	at org.gradle.initialization.DefaultGradleLauncher$3.run(DefaultGradleLauncher.java:143)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:140)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:45)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)


BUILD FAILED

Total time: 3.308 secs
```

**Comment by nathandunn** [comment]
Well, the try just

 ./gradlew gwtc

And if that works try:

./gradlew gwtc —stacktrace

**Comment by chibante** [comment]
I tried using `sudo` and it looks like it worked :)
Here, in our bioinformatics lab, we have by default install programs in a specific folder.
Can I install everything using my user or do you suggest installing using `sudo` or another specific user? 

[carla@mendel Apollo]$ `sudo ./gradlew gwtc`
```
Downloading https://services.gradle.org/distributions/gradle-2.11-all.zip
.........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Unzipping /root/.gradle/wrapper/dists/gradle-2.11-all/ace7yl0a7udokebb27mt9s3qr/gradle-2.11-all.zip to /root/.gradle/wrapper/dists/gradle-2.11-all/ace7yl0a7udokebb27mt9s3qr
Set executable permissions for: /root/.gradle/wrapper/dists/gradle-2.11-all/ace7yl0a7udokebb27mt9s3qr/gradle-2.11/bin/gradle
No log file found in classpath.
Final JBrowse settings [git:[url:https://github.com/gmod/jbrowse, branch:1.15.4-release, alwaysPull:true, alwaysRecheck:true], plugins:[WebApollo:[included:true], RegexSequenceSearch:[included:true], HideTrackLabels:[included:true]]]
Final plugins [WebApollo:[included:true], RegexSequenceSearch:[included:true], HideTrackLabels:[included:true]]
:javac
:gwtc

BUILD SUCCESSFUL

Total time: 49.414 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.11/userguide/gradle_daemon.html
```
[carla@mendel Apollo]$ `sudo ./gradlew gwtc --stacktrace`
```
No log file found in classpath.
Final JBrowse settings [git:[url:https://github.com/gmod/jbrowse, branch:1.15.4-release, alwaysPull:true, alwaysRecheck:true], plugins:[WebApollo:[included:true], RegexSequenceSearch:[included:true], HideTrackLabels:[included:true]]]
Final plugins [WebApollo:[included:true], RegexSequenceSearch:[included:true], HideTrackLabels:[included:true]]
:javac
:gwtc

BUILD SUCCESSFUL

Total time: 42.662 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.11/userguide/gradle_daemon.html
```

**Comment by nathandunn** [comment]
Oh, its because your ~/.gradle directory has the wrong permissions:

You’ll want to do something like:

sudo chown -R username:username ~/.gradle 
sudo chown -R username:username ~/.grails
sudo chown -R username:username ~/.groovy


You’ll probably want to do something for your Apollo directory as well:

sudo chown -R username:username *   # from your Apollo download directory 


Where username is francicco (or whatever your local username is).

Nathan

**Comment by chibante** [comment]
Thanks for your help! :)
