### ISSUE TITLE
Failed to load annotations to Apollo2

### ISSUE THREAD

**Issue by dytk2134** [GMOD/Apollo#1938]
Hi all,
I'm trying to load annotations to Apollo2 through add_features_from_gff3_to_annotations.pl, but I got an error and I don't know how to fix this error.

Command:  
```
add_features_from_gff3_to_annotations.pl -U [URL to Apollo instance] -u [username] -p [password] -i "annotations-09-17-2018.gff3" -o "Oncopeltus fasciatus" -a -X
```

error.log  
```
Processing Scaffold101
Processing chunk 1: https://apollo.nal.usda.gov/apollo/annotationEditor/addTranscript
success
Processing Scaffold3908
Processing chunk 1: https://apollo.nal.usda.gov/apollo/annotationEditor/addTranscript
error: Cannot get property 'sequence' on null object
Processing individual features for failed chunks
Processing DF3C26F49657BAB7D81F5A5831E72471: https://apollo.nal.usda.gov/apollo/annotationEditor/addTranscript
error: Cannot get property 'sequence' on null object
Processing Scaffold1288
Processing chunk 1: https://apollo.nal.usda.gov/apollo/annotationEditor/addTranscript
error: Cannot get property 'sequence' on null object
Processing individual features for failed chunks
Processing BE4382A924F2CD3A10653CFCACA1B253: https://apollo.nal.usda.gov/apollo/annotationEditor/addTranscript
error: Cannot get property 'sequence' on null object
Processing Scaffold441
Processing chunk 1: https://apollo.nal.usda.gov/apollo/annotationEditor/addTranscript
success
```

Any one know how to fix this?

**Comment by nathandunn** [comment]
- Can you post the failing GFF3? 
- Can you post the tomcat / Apollo logs from catalina.out?

**Comment by dytk2134** [comment]
failing GFF3  
```
##gff-version 3
##sequence-region Scaffold3423 1 54928
Scaffold3423    WebApollo       gene    34380   35479   .       +       .       owner=acrumiere;ID=068853E9779C8988E4A380CC9963C4E9;date_last_modified=2016-07-24;Name=068853E9779C8988E4A380CC9963C4E9;date_creation=2016-07-24
Scaffold3423    WebApollo       mRNA    34380   35479   .       +       .       owner=acrumiere;symbol=Ubx;Parent=068853E9779C8988E4A380CC9963C4E9;Note=Result from blast,Manual curation;ID=61DD11B161E387F4FAFF9CB23528D197;date_last_modified=2016-09-8;Name=Ultrabithorax - part 1 of 2;Dbxref=Flybase:FBgn0003944;date_creation=2016-07-24
Scaffold3423    WebApollo       exon    34380   35479   .       +       .       owner=acrumiere;Parent=61DD11B161E387F4FAFF9CB23528D197;ID=8740DFC52F143A97AF94740CAFC29B6C;date_last_modified=2016-07-24;Name=8740DFC52F143A97AF94740CAFC29B6C;date_creation=2016-07-24
Scaffold3423    WebApollo       CDS     34633   35373   .       +       0       owner=acrumiere;Parent=61DD11B161E387F4FAFF9CB23528D197;ID=61DD11B161E387F4FAFF9CB23528D197-CDS;date_last_modified=2016-07-24;Name=61DD11B161E387F4FAFF9CB23528D197-CDS;date_creation=2016-07-24
```

catalina.out  (run the command above again but nothing change in catalina.out)

```
2018-09-18 12:30:50,125 [http-nio-8080-exec-17] WARN  apollo.PreferenceService  - Multiple preferences found: 13
2018-09-18 12:31:00,874 [http-nio-8080-exec-22] WARN  apollo.PreferenceService  - Multiple preferences found: 14
2018-09-18 12:31:01,715 [http-nio-8080-exec-19] WARN  apollo.PreferenceService  - Multiple preferences found: 16
2018-09-18 12:31:02,108 [http-nio-8080-exec-23] WARN  apollo.PreferenceService  - Multiple preferences found: 16
2018-09-18 12:31:02,304 [http-nio-8080-exec-21] WARN  apollo.PreferenceService  - Multiple preferences found: 2
2018-09-18 12:31:02,308 [http-nio-8080-exec-21] INFO  apollo.UserController  - updateTrackListPreference
2018-09-18 12:31:02,310 [http-nio-8080-exec-21] INFO  apollo.UserController  - Added userOrganismPreference false
2018-09-18 12:31:12,776 [http-nio-8080-exec-20] WARN  apollo.PreferenceService  - No user present, so using the client token
2018-09-18 12:31:12,807 [http-nio-8080-exec-20] ERROR errors.GrailsExceptionResolver  - NullPointerException occurred when processing request: [GET] /apollo/9214940551168370403472966192/jbrowse/sample_data/json/volvox/successfully_run
Cannot get property 'id' on null object. Stacktrace follows:
java.lang.NullPointerException: Cannot get property 'id' on null object
        at org.bbop.apollo.JbrowseController.passthrough(JbrowseController.groovy:542)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2018-09-18 12:31:13,568 [http-nio-8080-exec-22] WARN  apollo.PreferenceService  - No user present, so using the client token
2018-09-18 12:31:13,588 [http-nio-8080-exec-18] ERROR apollo.PermissionService  - Username not supplied so can not authenticate.
2018-09-18 12:31:13,588 [http-nio-8080-exec-18] ERROR apollo.PermissionService  - User null does not exist in the database.
2018-09-18 12:31:13,602 [http-nio-8080-exec-23] ERROR authenticator.UsernamePasswordAuthenticatorService  - Problem authenticating: java.lang.IllegalArgumentException: Method argumet (authentication token) cannot be null.
2018-09-18 12:31:13,602 [http-nio-8080-exec-23] WARN  apollo.PermissionService  - Failed to authenticate user
2018-09-18 12:31:13,602 [http-nio-8080-exec-23] ERROR apollo.UserController  - Failed to authenticate
2018-09-18 12:31:34,441 [http-nio-8080-exec-23] WARN  apollo.PreferenceService  - No user present, so using the client token
2018-09-18 12:31:36,234 [http-nio-8080-exec-18] WARN  apollo.PreferenceService  - No user present, so using the client token
2018-09-18 12:31:54,090 [http-nio-8080-exec-23] WARN  apollo.PreferenceService  - No user present, so using the client token
2018-09-18 12:41:37,637 [http-nio-8080-exec-18] WARN  apollo.PreferenceService  - No user present, so using the client token
2018-09-18 12:41:41,024 [http-nio-8080-exec-14] WARN  apollo.PreferenceService  - No user present, so using the client token
```

**Comment by nathandunn** [comment]
./add_features_from_gff3_to_annotations.pl    -U http://demo.genomearchitect.org/Apollo2 -u demo@demo.com -p demo -i test3.gff3  -t mRNA -o Honeybee

I used an existing scaffold on a test database and it worked. 

Using: 

```
Group1.1	WebApollo	gene	34380	35479	.	+	.	owner=acrumiere;ID=068853E9779C8988E4A380CC9963C4E9;date_last_modified=2016-07-24;Name=068853E9779C8988E4A380CC9963C4E9;date_creation=2016-07-24
Group1.1	WebApollo	mRNA	34380	35479	.	+	.	owner=acrumiere;symbol=Ubx;Parent=068853E9779C8988E4A380CC9963C4E9;Note=Result from blast,Manual curation;ID=61DD11B161E387F4FAFF9CB23528D197;date_last_modified=2016-09-8;Name=Ultrabithorax - part 1 of 2;Dbxref=Flybase:FBgn0003944;date_creation=2016-07-24
Group1.1	WebApollo	exon	34380	35479	.	+	.	owner=acrumiere;Parent=61DD11B161E387F4FAFF9CB23528D197;ID=8740DFC52F143A97AF94740CAFC29B6C;date_last_modified=2016-07-24;Name=8740DFC52F143A97AF94740CAFC29B6C;date_creation=2016-07-24
Group1.1	WebApollo	CDS	34633	35373	.	+	0	owner=acrumiere;Parent=61DD11B161E387F4FAFF9CB23528D197;ID=61DD11B161E387F4FAFF9CB23528D197-CDS;date_last_modified=2016-07-24;Name=61DD11B161E387F4FAFF9CB23528D197-CDS;date_creation=2016-07-24
```

My guess is it is either:
- bad GFF? (can you validate it individually, make sure right number of tabs, etc.)
- scaffold doesn't exist? 
- random aside . . try removing preferences from the database: ```delete from preference ; ```

**Comment by dytk2134** [comment]
- I download this gff3 file from the apollo1 and this file pass the validation. 
- It seems like this scaffold is existed.
  
![image](https://user-images.githubusercontent.com/12807454/45768187-28806c80-bc0a-11e8-8aca-5120995c1672.png)

- Removed preferences from the database seems to fix part of this issue but I still got error when try to load the gene model above....
    
Is `migrate_annotations1to2.groovy` the normal way to migrate annotation from Apollo1 to Apollo2? ([here](https://genomearchitect.readthedocs.io/en/latest/Migration.html#migrate-annotations))

**Comment by nathandunn** [comment]
@dytk2134  Yes, that's the preferred way, but whatever works.   Also of note, you may have to pull them through at a custom level: https://github.com/GMOD/Apollo/pull/1934   Using the migration script will move things from JSON to JSON, which **may** be less error-prone. 

That being said, if its only stalling on one or two GFF3 genes, I would remove those and then add them manually.  

I was also thinking that it might have been spaces or weird characters in your GFF3, but it didn't end up failing for me, so who knows.

**Comment by dytk2134** [comment]
@nathandunn  Thanks for explanation! 
I've another question which might not relate to this one. Is there any script can migrate annotations between two servers? (e.g. migrate annotations from development server to production server)

**Comment by nathandunn** [comment]
@dytk2134  I would do one of the following depending on your situation:

- create a backup of the development server (e.g., pg_dump) and make that the production database if you don't need annotations on the production database.  This would be very quick if this is your use-case.

- the GFF3 Apollo exports (from the Sequence Panel) is designed to be re-imported by Apollo, so if they are both relatively recent versions of Apollo (in the last year), you should be able to dump and re-import using `add_features_from_gff3_to_annotations.pl`

- there is a script called `transfer_annotations2to2.groovy` I would try this between two dev servers first as it is a couple of years old and I haven't tested it in awhile.

**Comment by dytk2134** [comment]
I see. Thank you!
