### ISSUE TITLE
On GFF3 export if tmp dir non-existent, explicitly fail

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#205]
Currently on requesting GFF3 for the User Annotation track generates an exception if the `tmp` directory doesn't exist.

```
Error writing GFF3
java.lang.NullPointerException
	at org.gmod.gbol.bioObject.io.GFF3Handler.convertToEntry(GFF3Handler.java:249)
	at org.gmod.gbol.bioObject.io.GFF3Handler.convertToEntry(GFF3Handler.java:226)
	at org.gmod.gbol.bioObject.io.GFF3Handler.convertToEntry(GFF3Handler.java:229)
	at org.gmod.gbol.bioObject.io.GFF3Handler.convertToEntry(GFF3Handler.java:229)
	at org.gmod.gbol.bioObject.io.GFF3Handler.convertToEntry(GFF3Handler.java:229)
	at org.gmod.gbol.bioObject.io.GFF3Handler.convertToEntry(GFF3Handler.java:199)
	at org.gmod.gbol.bioObject.io.GFF3Handler.writeFeature(GFF3Handler.java:154)
	at org.gmod.gbol.bioObject.io.GFF3Handler.writeFeatures(GFF3Handler.java:134)
	at org.bbop.apollo.web.dataadapter.gff3.Gff3IO.writeFeatures(Gff3IO.java:29)
	at org.bbop.apollo.web.dataadapter.gff3.Gff3JEDatabaseIO.writeFeatures(Gff3JEDatabaseIO.java:47)
	at org.bbop.apollo.web.dataadapter.gff3.Gff3DataAdapter.write(Gff3DataAdapter.java:169)
	at org.bbop.apollo.web.dataadapter.IOService.doGet(IOService.java:132)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1074)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

It would be nice if Apollo would try to create this on demand, or as part of the `deploy` target for a cleaner solution.

**Comment by nathandunn** [comment]
Eric, I think the correct behavior is to specifically fail.  If it tries to create a directory based on a default, we don't want it create directories and dumping files.   However a NPE is just not good practice.

**Comment by erasche** [comment]
Okay, sounds fine to me. I'll dig into the code and see if I can't have it
return a more useful error.

tor. 26. mar. 2015, 23.45 skrev Nathan Dunn <notifications@github.com>:

**Comment by nathandunn** [comment]
@deepakunni3   Feel free to close if this is no longer relevant or if it is working now.

**Comment by deepakunni3** [comment]
This shouldn't happen the way it is currently implemented, unless the server hard disk has insufficient space.
