### ISSUE TITLE
add group add / delete in bulk and group update in bulk

### ISSUE THREAD

**Issue by abretaud** [GMOD/Apollo#2105]
Hi,
With @mboudet we're working on https://github.com/genouest/ldapollo to synchronize our ldap users/groups with our Apollo configured with REMOTE_USER.
I'm testing it with our 500 users, and I sometimes see this error when assigning users to groups (both newly created):

```
Cannot invoke method getMetaData() on null object. Stacktrace follows:
java.lang.NullPointerException: Cannot invoke method getMetaData() on null object
	at org.bbop.apollo.GroupController.$tt__updateMembership(GroupController.groovy:414)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Do you see what could be the problem? Rerunning the script works, but usually fails on the next empty group.

**Comment by nathandunn** [comment]
I don't see anything obvious.  I guess I would check to see what the dataObject.groupId is when it comes through and to verify that those groups are valid. 

```
diff --git a/grails-app/controllers/org/bbop/apollo/GroupController.groovy b/grails-app/controllers/org/bbop/apollo/GroupController.groovy
index 36b158b6b..aeb3f9531 100644
--- a/grails-app/controllers/org/bbop/apollo/GroupController.groovy
+++ b/grails-app/controllers/org/bbop/apollo/GroupController.groovy
@@ -409,6 +409,8 @@ class GroupController {
     def updateMembership() {
         JSONObject dataObject = permissionService.handleInput(request, params)
         UserGroup groupInstance = UserGroup.findById(dataObject.groupId)
+        println "${dataObject.groupId} ${dataObject as JSON} -> ${groupInstance}"
+        println "${request.JSON} and ${params}"
         // to support webservice, get current user from session or input object
         def currentUser = permissionService.getCurrentUser(dataObject)
```

**Comment by abretaud** [comment]
In fact these exceptions are more frequent, for some of the created users:

```2019-03-28 16:43:18,648 [http-nio-8080-exec-4] ERROR errors.GrailsExceptionResolver  - StaleObjectStateException occurred when processing request: [POST] /user/createUser
Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [org.bbop.apollo.User#386]. Stacktrace follows:
org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [org.bbop.apollo.User#386]
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
or when creating some groups:
```
2019-03-28 16:43:27,561 [http-nio-8080-exec-5] ERROR errors.GrailsExceptionResolver  - StaleObjectStateException occurred when processing request: [POST] /group/createGroup
Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [org.bbop.apollo.User#20]. Stacktrace follows:
org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [org.bbop.apollo.User#20]
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Or when updating membership:
```
2019-03-28 16:48:47,289 [http-nio-8080-exec-10] ERROR errors.GrailsExceptionResolver  - StaleObjectStateException occurred when processing request: [POST] /group/updateMembership
Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [org.bbop.apollo.User#60]. Stacktrace follows:
org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [org.bbop.apollo.User#60]
	at org.bbop.apollo.GroupController.$tt__updateMembership(GroupController.groovy:448)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

It feels like some race condition no?
I'm trying to get more logs with your patch, I'll post it when I get it (rebuilding at the moment...)

**Comment by nathandunn** [comment]
The logs will be helpful.  

I’m wondering if what you need is a bulk end point as running these together really quickly in individual transactions is probably what is causing the problem.

Do you have an outline of your script that is pushing these changes? 

Nathan

**Comment by abretaud** [comment]
Yes, the script is there: https://github.com/genouest/ldapollo/blob/master/ldapollo.py it uses https://github.com/galaxy-genome-annotation/python-apollo (the 2.4 branch)
It gets user and group list from an ldap server, but I think it's easy to change it to load a hardcoded list if you want to test.

For the logs, for some reason I have problems applying the patch on my test setup, it'll have to wait a bit as I'm leaving and will probably be busy next days, sorry :(

**Comment by nathandunn** [comment]
No worries.  Same here. 

Nathan

**Comment by abretaud** [comment]
Finally, the log:

`676 {"password":"admin","clientToken":"ignore","groupId":676,"users":["login@bipaa"],"username":"admin@bipaa"} -> null`

`[password:admin, clientToken:ignore, groupId:676, users:[login@bipaa], username:admin@bipaa] and [controller:group, format:null, action:updateMembership]`

**Comment by nathandunn** [comment]
@abretaud  Can you confirm whether or not that group ID exists?    You can see what comes back from JSON or just look at what is in the user_group table.

**Comment by nathandunn** [comment]
@abretaud  I would call get_groups or institute a pause here: https://github.com/genouest/ldapollo/blob/master/ldapollo.py#L161

My guess is that it starts the next transaction before its finished this one.

**Comment by nathandunn** [comment]
Could I just add a group bulk add function so it does it with a single command?    

Running transactions in a loop is always a problem.

**Comment by abretaud** [comment]
Yes I think it would be simpler, and it would be great if you could also do it for group update (to update all group memberships at once)

**Comment by nathandunn** [comment]
Sure.   Could you provide me a sample groups file or list and a sample group update file so I can have a format to start with? 

If it is roughly like users that would be good, but doesn’t matter so long as its consistent.

**Comment by abretaud** [comment]
I think for creating a list of groups, we could just pass a json list like this to createGroup(s) method in GroupService:
`{"names": ["group1", "group2", "group3"]}`

And for bulk updateMembership:
`{"membership": {<groupId>: ["user1", "user2", "user3"], <another-groupId>: ["user2", "user8"]}}`

What do you think?

**Comment by nathandunn** [comment]
oh, I just did "group1,group2,group3" for names . .  just being lazy, but let me know if that works (in case you want to have a group name with a comma).  Maybe formal JSON would make more sense.

for bulk update I think that looks good

**Comment by abretaud** [comment]
Oh! I had not seen #2130, I will test it!

**Comment by nathandunn** [comment]
Oh, its still in progress, but add_groups should work (note the groovy script) . . but if that was causing a problem in a loop below for adding groups, this should hopefully be fixed.
