### ISSUE TITLE
can not delete a Pseudogene

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#224]
447d-82f6-3726ef7e92c2', sequenceLength=null, status=null, dateCreated=Thu Apr 09 10:15:03 PDT 2015, lastUpdated=Thu Apr 09 10:15:03 PDT 2015}
found the method deleteFeature
researcher roles? ADMIN
2015-04-09 10:15:12,693 [clientInboundChannel-2] ERROR springwebsocket.GrailsSimpAnnotationMethodMessageHandler  - Unhandled exception
java.lang.reflect.InvocationTargetException
	at org.bbop.apollo.AnnotationEditorController$_annotationEditor_closure4_closure5_closure6.doCall(AnnotationEditorController.groovy:586)
	at org.bbop.apollo.AnnotationEditorController$_annotationEditor_closure4_closure5.doCall(AnnotationEditorController.groovy:585)
	at org.bbop.apollo.AnnotationEditorController$_annotationEditor_closure4.doCall(AnnotationEditorController.groovy:581)
	at groovyx.gpars.group.PGroup$3.call(PGroup.java:289)
	at groovyx.gpars.group.PGroup$4.run(PGroup.java:313)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: Cannot invoke method save() on null object
	at org.bbop.apollo.RequestHandlingService.$tt__deleteFeature(RequestHandlingService.groovy:1369)
	... 8 more

**Comment by cmdcolin** [comment]
I was able to delete pseudogene so seems fixed

**Comment by monicacecilia** [comment]
@nathandunn Yes I can! :dancer:
