### ISSUE TITLE
Cannot read property 'firstChild' of null on apollo covid browser

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#2442]
```
1.bundle.js:1 TypeError: Cannot read property 'firstChild' of null
    at Object.t.place (0.bundle.js:1)
    at 1.bundle.js:1
    at 1.bundle.js:1
    at u (0.bundle.js:1)
    at a (0.bundle.js:1)
    at c.resolve (0.bundle.js:1)
    at Object.passMilestone (1.bundle.js:1)
    at 1.bundle.js:1
    at u (0.bundle.js:1)
    at a (0.bundle.js:1) "TypeError: Cannot read property 'firstChild' of null
    at Object.t.place (http://covid19apollo.jbrowse.org/1215507230870521964691178469/jbrowse/dist/0.bundle.js:1:27834)
    at http://covid19apollo.jbrowse.org/1215507230870521964691178469/jbrowse/dist/1.bundle.js:1:1090996
    at http://covid19apollo.jbrowse.org/1215507230870521964691178469/jbrowse/dist/1.bundle.js:1:49755
    at u (http://covid19apollo.jbrowse.org/1215507230870521964691178469/jbrowse/dist/0.bundle.js:1:47332)
```

**Comment by nathandunn** [comment]
Will re-test on RC1 draft.  Couldn't find on latest dev.

**Comment by nathandunn** [comment]
This shows up here:  http://covid19apollo.jbrowse.org/annotator/index

Which  means its probably related to a plugin.   Should probably go there as an error, but we should double-check this codebase to make sure.

**Comment by nathandunn** [comment]
@scottcain  I'm getting this from the Wormbase plugin: 

```
               JBrowse.afterMilestone('completely initialized', function () {
                    var url = location.href;
                    console.log(url);
                    var mod_str = '';
                    var wb_ver = '';
                    var br = '';
                    if (url.match('jbrowse-simple')) {
                        br = '</br>';
                    }
                    wb_ver += '<a target="_blank" href="http://blog.wormbase.org/2019/03/18/getting-dna-sequence-from-jbrowse/"> Want to download FASTA?</a></br>';
                    if (url.match('PRJNA13758')) {
                        mod_str = '<a style="margin: 2px" href="/tools/genome/jbrowse-simple/full.html?data=data%2Fold-modencode">Looking for older modENCODE data?</a></br>';
                    }
                    var parent = document.getElementById('dijit_layout_ContentPane_2'); //track selector pane
                    // ------------------------------------------------------------ 
                    // BELOW THIS LINE 
                    dojo.place(domConstruct.toDom(wb_ver + mod_str + br), parent, "first"); //add version and modencode message
                    // ------------------------------------------------------------
                    // ABOVE THIS LINE 
                    //add logo to menubar
                    var bluebar = browser.menuBar;
                    bluebar.appendChild(domConstruct.toDom('<a href="/"><img src="https://wormbase.org/img/logo/logo_wormbase_gradient.svg" width="100px" style="padding-top: 5px"></a>'));
```

Its based off of mine.  Keep in mind I'm not adding `functions.conf` . ..  I might just write around it.

**Comment by nathandunn** [comment]
Since I'm using my own wormbase Repo for the WormbaseGlyphs, I'll just try rewriting it that way instead

**Comment by nathandunn** [comment]
Yeah, removing that line fixed it: ```                    dojo.place(domConstruct.toDom(wb_ver + mod_str + br), parent, "first"); //add version and modencode message```


Now, when I click it shows up, but I get this:

![image](https://user-images.githubusercontent.com/751274/80038689-036d7300-84ab-11ea-856e-7c0f88ff7248.png)


```
   if (block.containsBp(bpX)) {
                        var renderTooltip = dojo.hitch(this, function () {
                            if (!this.labelTooltip) return;
                            var label = fRect.label || fRect.glyph.makeFeatureLabel(feature);
                            var description = fRect.description || fRect.glyph.makeFeatureDescriptionLabel(feature);

                            if (!label && !description) return;

                            if (!this.ignoreTooltipTimeout) {
                                this.labelTooltip.style.left = evt.clientX + "px";
                                this.labelTooltip.style.top = evt.clientY + 15 + "px";
                            }
                            this.ignoreTooltipTimeout = true;
                            this.labelTooltip.style.display = 'block';
                            var labelSpan = this.labelTooltip.childNodes[0],
                                descriptionSpan = this.labelTooltip.childNodes[1];

                            if (this.config.onClick && this.config.onClick.label) {
                                var context = lang.mixin({ track: this, feature: feature, callbackArgs: [this, feature] });
                                labelSpan.style.display = 'block';
                                labelSpan.style.font = label.font;
                                labelSpan.style.color = label.fill;
                                var t = this.template(feature, this._evalConf(context, this.config.onClick.label, "label"));
                                labelSpan.innerHTML = this.config.unsafeMouseover ? t : Util.escapeHTML(t);
                                return;
                            }
```
