### ISSUE TITLE
calling get CDS or getPeptide sequence fails in some cases

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#2454]
URL is: http://demo.genomearchitect.org/Apollo-staging/annotator/loadLink?loc=Group1.1:89856..92812&organism=3836&tracks=Official%20Gene%20Set%20v3.2,Metazoa_swissprot,Forager%20RNA-Seq%20reads,Apis%20cerana%20RNA-Seq%20reads

```
316/AnnotationEditorService
String index out of range: -121. Stacktrace follows:
java.lang.StringIndexOutOfBoundsException: String index out of range: -121
	at java.lang.String.substring(String.java:1967)
	at org.bbop.apollo.CdsService.$tt__getResiduesFromCDS(CdsService.groovy:164)
	at org.bbop.apollo.FeatureService.$tt__getResiduesWithAlterations(FeatureService.groovy:2862)
	at org.bbop.apollo.FeatureService.$tt__getResiduesWithAlterationsAndFrameshifts(FeatureService.groovy:1069)
	at org.bbop.apollo.SequenceService.$tt__getSequenceForFeature(SequenceService.groovy:524)
	at org.bbop.apollo.SequenceService.$tt__getSequenceForFeatures(SequenceService.groovy:654)
	at org.bbop.apollo.AnnotationEditorController.getSequence(AnnotationEditorController.groovy:985)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.grails.plugins.web.rest.api.ControllersRestApi.forward(ControllersRestApi.groovy:53)
	at org.bbop.apollo.AnnotationEditorController.handleOperation(AnnotationEditorController.groovy:72)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

GFF3 is:

```
##gff-version 3
##sequence-region Group1.1 1 1382403
Group1.1	.	gene	90330	92344	.	-	.	owner=nathandunn@lbl.gov;gene_product=;ID=47af0254-925e-4ba8-b5f7-b6b40d65d241;date_last_modified=2020-04-23;Name=GB42163-RA;date_creation=2020-04-23
Group1.1	.	mRNA	90330	92344	.	-	.	owner=nathandunn@lbl.gov;Parent=47af0254-925e-4ba8-b5f7-b6b40d65d241;gene_product=;ID=a3fb05a4-3945-45de-98c1-54b7a7f31936;orig_id=GB42163-RA;date_last_modified=2020-04-23;Name=GB42163-RA-00001;date_creation=2020-04-23
Group1.1	.	non_canonical_three_prime_splice_site	90563	90563	.	-	.	Parent=a3fb05a4-3945-45de-98c1-54b7a7f31936;ID=a3fb05a4-3945-45de-98c1-54b7a7f31936-non_canonical_three_prime_splice_site-90562;Name=a3fb05a4-3945-45de-98c1-54b7a7f31936-non_canonical_three_prime_splice_site-90562
Group1.1	.	exon	92312	92344	.	-	.	Parent=a3fb05a4-3945-45de-98c1-54b7a7f31936;ID=9c0323ab-bbb4-4c5c-abd2-220768a7bd8c;Name=9c0323ab-bbb4-4c5c-abd2-220768a7bd8c
Group1.1	.	CDS	90562	90440	.	-	0	Parent=a3fb05a4-3945-45de-98c1-54b7a7f31936;ID=833791b6-f33e-4ea6-9d25-f25995f4f4d2;Name=833791b6-f33e-4ea6-9d25-f25995f4f4d2
Group1.1	.	exon	90330	90562	.	-	.	Parent=a3fb05a4-3945-45de-98c1-54b7a7f31936;ID=e6773b26-c4cc-4217-a1bd-52ae27cbd025;Name=e6773b26-c4cc-4217-a1bd-52ae27cbd025
###
```

CDNA Sequence is:

```
>a3fb05a4-3945-45de-98c1-54b7a7f31936 (sequence:mRNA) 266 residues [Group1.1:90330-92344 - strand] [cdna]
TGAAATGGCCGATGATGATACCGGCTACCGTACATGTCACGTTTTTGAAGATCGTGGGAA
GATTTAAGAAGATCTTTGGCACGAGAATGTTGGCTAGACTCTTCGATGGGGTTCAAGTAG
GACGTGAGAATGTGATCGTTGTGGTGGATTTATGTGGGATCTTTGATTTGCCGGTGTTGG
AGATTTGTCTTACAATTTGTAAGATGTGTTGGAGACGCTGTAAAAAATTTGTATCTCGCA
TCTTAAATTTAGCACTAGGAAAGTAG
```

Genomics:

```
>a3fb05a4-3945-45de-98c1-54b7a7f31936 (sequence:mRNA) 2015 residues [Group1.1:90330-92344 - strand] [genomic]
TGAAATGGCCGATGATGATACCGGCTACCGTACGTCGTGGAATAAGTCGAGATATCGAAG
CCGGTGTAAACTGAAACCTCGCTCCCGATGTCGATTAATTTATTGAAGACCAGTTTAACG
GGTCGCCGATTGGAAAAATTGTATTCTTCGTTCAACAGGCTCAGGCTCGTTTCTTTTTTC
TTTTTTCTTTTTTTTGCTCGTTTTTGATTTTTCGAATATTTCGATATACGGCGAGATTGT
TGTTGAGAATATCTATCCCCGTTTGATAAGATTATCTCATTCTCCTTTTATATACACTTA
TTTACTTTTATCCTTGTAACATTTATTTTCTCGCTTTATCCCGGTTTATTGAAAAGAGAA
GATGATGAAATGGTTACCTTATATAGCCAAATAAAAAACACTGCGAATACTCGACGAAGC
GTTTTCAAAACTTCATTACGTGTATATATATATATGTATAAAGTATCACTTGTTTATTTA
AACATCACCGCAATAATTAGAAGTTCGTGCTATTTGAAATGATAAACGATAATTCGAGAG
AATGTACATATATATATAAAAAGCGAATCTGAAACCGTTCAACGAGTCGTATTAAAAAAA
AAAAGAAAGAAAGAAAGGCGAAAGAAACCACGAACACTCTGAACGCGATGAAAAAGTATC
CCTTTCGTATCCTCCGCAGCCCGTTAATCCCGTCCGGGATACAAGGAATGAAACGAAATC
ACTCGAGCCATGCGGGTGTAGGCAACTGGACGCCAACCTCCAATTTCCGTCCGTCCAGTT
TTCTCCTCCGCTTCCGTGCCACCGCCGGTCAATTACGGCGCGCCACGCTGTGTGCACCGC
GCTGCACGTAGCAATCCTATTTATCAATGCCACGAATCCGCGGCTACGTGTGTCCCGCGT
CTGCGCGGCCCGTACGCGATATTTCCTCCCGCGAGCCCCTCCATCGGCCCAGAACATCCG
AACCGACCGGCCGCGGTGGACGTCGGTAAATCGTCCCTCCTTCAATTGGAAACAATTCTC
CCCGCGATAGTACCGCGTTTCGAATTCGCGCGAATTGTGCGCCGTTTATCTCCCCGTGAG
ATTCCTCCTTCCTTCGTTTTGGATGGAAATATCGTGTCGTGATTGTTCTTTCGTTTTTCT
CTTTTCTTTTTTGTTTTTTGATTTGTTGTTATAGGTAACGAAACGATGCAATTATTTATA
TATAAAGTATTGCGCGAAATGGTCGGTTTCGTACGGGTTGAGAGTTGGAATTGGATGTGC
GGTGGAAATTCCGTATTCGGAATTATTGTTGTGTTCGATTACGGTGGTGGATTCACGGAG
GAAGAATTTTCGAAGATTGTTAAATGTTGTAAATATCGTAATTTTTCTTTCTTTTTTTGA
TTATTGGATAATTTTGTTAGCGATACGATTTATAAAATATTGTGTAAATTATAAAATATT
ATAGACAAGAGACATTTAAAATTATTATTCTGTTATAGTAAATTCGCGAAAGAATTTTCG
AAATAGTTGTTGCAAGATTTTTGTTGAATAATTTTTATGGAAATTTTTTTTTTCTTTCGA
TTGTTAAGTAACTTTTGTTGTTCCTTTTTATTACGAAACGATGCACGAGAAAGTATTTAT
AGAATATTGTGCAAAATTGTTTTATTGTTGCGTTCAATATATATGGATTCAATCGAAAAA
TCAAAAATCGAATCGAAGAAAAGTTTTCGCTTAAGAAAAATTTCAACATCATCTTTTATT
TAATTTTTATCGTTGGGACAGTTTTGGAATTGTCGACTAACCATGTCACGTTTTTGAAGA
TCGTGGGAAGATTTAAGAAGATCTTTGGCACGAGAATGTTGGCTAGACTCTTCGATGGGG
TTCAAGTAGGACGTGAGAATGTGATCGTTGTGGTGGATTTATGTGGGATCTTTGATTTGC
CGGTGTTGGAGATTTGTCTTACAATTTGTAAGATGTGTTGGAGACGCTGTAAAAAATTTG
TATCTCGCATCTTAAATTTAGCACTAGGAAAGTAG

```

**Comment by nathandunn** [comment]
can not replicate locally
