### ISSUE TITLE
Apollo via Docker - psql: FATAL:  Peer authentication failed for user "apollo"

### ISSUE THREAD

**Issue by fbemm** [GMOD/Apollo#2471]
I am simply trying to fire up Apollo via Docker with:

`docker run --rm -v /webapollo/jbrowse:/data -v /webapollo/postgres:/var/lib/postgresql quay.io/gmod/apollo:latest`

But it throws errors after getting the image:

```
 * Starting PostgreSQL 9.6 database server
   ...done.
WEBAPOLLO_HOST_FLAG: 
CHADO_HOST_FLAG: 
Waiting for DB
/var/run/postgresql:5432 - accepting connections
Postgres is up, configuring database
psql: FATAL:  Peer authentication failed for user "apollo"
Apollo database not found, creating...
createdb: database creation failed: ERROR:  database "apollo" already exists
ERROR:  role "apollo" already exists
GRANT
Not using chado!
CATALINA_HOME '/usr/share/tomcat9'
CATALINA_BASE '/var/lib/tomcat9'
APOLLO PATH ''
FIXED_CTX PATH ''
WAR FILE '/var/lib/tomcat9/webapps/.war'
Apr 29, 2020 3:55:39 PM org.apache.catalina.startup.Catalina stopServer
SEVERE: No shutdown port configured. Shut down server through OS signal. Server not shut down.
Kill failed: $CATALINA_PID not set
```

Could you give me a hint where to start debugging this?

**Comment by fbemm** [comment]
Looks the same if I am letting docker built the db inside the container.

**Comment by fbemm** [comment]
https://github.com/GMOD/Apollo/issues/2373#issuecomment-606214286

**Comment by fbemm** [comment]
```
root         1  0.0  0.0   4628   872 ?        Ss   16:04   0:00 /bin/sh -c "/launch.sh"                                                                                                                                                                                                                                                                                                                                                                                               [0/2350]
root         7  0.0  0.0  18376  3124 ?        S    16:04   0:00 bash /launch.sh
postgres    23  0.0  0.3 313340 26104 ?        S    16:04   0:00 /usr/lib/postgresql/9.6/bin/postgres -D /var/lib/postgresql/9.6/main -c config_file=/etc/postgresql/9.6/main/postgresql.conf
postgres    25  0.0  0.1 313472  9588 ?        Ss   16:04   0:00 postgres: 9.6/main: checkpointer process   
postgres    26  0.0  0.0 313340  4220 ?        Ss   16:04   0:00 postgres: 9.6/main: writer process   
postgres    27  0.0  0.1 313340  8980 ?        Ss   16:04   0:00 postgres: 9.6/main: wal writer process   
postgres    28  0.0  0.0 313752  7000 ?        Ss   16:04   0:00 postgres: 9.6/main: autovacuum launcher process   
postgres    29  0.0  0.0 168484  4364 ?        Ss   16:04   0:00 postgres: 9.6/main: stats collector process   
root       106 56.6 20.2 4751404 1648180 ?     Sl   16:04   7:24 /usr/lib/jvm/java-8-openjdk-amd64/bin/java -Djava.util.logging.config.file=/var/lib/tomcat9/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Dorg.apache.catalina.security.SecurityListener.UMASK=0027 -Dignore.endorsed.dirs= -classpath /usr/share/tomcat9/bin/bootstrap.jar:/usr/
postgres   128  0.0  0.1 314264 11248 ?        Ss   16:05   0:00 postgres: 9.6/main: apollo apollo 127.0.0.1(34588) idle
postgres   129  0.0  0.1 314264 11284 ?        Ss   16:05   0:00 postgres: 9.6/main: apollo apollo 127.0.0.1(34590) idle
postgres   130  0.0  0.1 314264 11288 ?        Ss   16:05   0:00 postgres: 9.6/main: apollo apollo 127.0.0.1(34592) idle
postgres   131  0.0  0.2 315188 16748 ?        Ss   16:05   0:00 postgres: 9.6/main: apollo apollo 127.0.0.1(34594) idle
postgres   132  1.1  0.2 318372 23340 ?        Ss   16:05   0:07 postgres: 9.6/main: apollo apollo 127.0.0.1(34596) idle
postgres   185  0.0  0.1 314264 11412 ?        Ss   16:10   0:00 postgres: 9.6/main: apollo apollo 127.0.0.1(34602) idle
postgres   186  0.0  0.1 314264 11416 ?        Ss   16:10   0:00 postgres: 9.6/main: apollo apollo 127.0.0.1(34604) idle
postgres   187  0.0  0.1 314264 11412 ?        Ss   16:10   0:00 postgres: 9.6/main: apollo apollo 127.0.0.1(34606) idle
postgres   188  0.0  0.1 314484 15788 ?        Ss   16:10   0:00 postgres: 9.6/main: apollo apollo 127.0.0.1(34608) idle
postgres   189  1.2  0.2 316728 18436 ?        Ss   16:10   0:05 postgres: 9.6/main: apollo apollo 127.0.0.1(34610) idle

```

**Comment by fbemm** [comment]
Seems as Apollo is not up yet. @nathandunn how long is this taking under normal circumstances?

**Comment by nathandunn** [comment]
@fbemm  You didn't expose a port:

    docker run --rm -p 8888:8080 -v /webapollo/jbrowse:/data -v /webapollo/postgres:/var/lib/postgresql quay.io/gmod/apollo:latest

Connect to http://localhost:8888/

Does that work?

**Comment by fbemm** [comment]
Had tried that before. From the logs it looks like the chado db is not even set up.

**Comment by fbemm** [comment]
I tried it on anther machine, same errors, but there it works. Seems as it simply takes a long time to spin up WebApollo on a VM (sitting behind a proxy).

**Comment by nathandunn** [comment]
Okay .. . I'll give it a try

**Comment by nathandunn** [comment]
@fbemm  A couple of things to try:

1.   ` docker pull quay.io/gmod/apollo:latest` . . . to see if there is a newer version
1.   Remove all local images related to this

**Comment by nathandunn** [comment]
using the command (and creating the database directory at my entry point):

    docker run --rm -p 8888:8080 -v /opt/apollo/:/data -v database:/var/lib/postgresql quay.io/gmod/apollo:latest

from above I'm able to login to:

http://localhost:8888/annotator/index

![image](https://user-images.githubusercontent.com/751274/80640493-5352b980-8a18-11ea-9505-59b21197029e.png)

**Comment by nathandunn** [comment]
Actually, I had not done a docker pull . . . retesting now

**Comment by nathandunn** [comment]
More recent also works fine for me and I get the same output (that is albeit confusing):

```
docker run --rm -p 8888:8080 -v /opt/apollo/:/data -v database:/var/lib/postgresql quay.io/gmod/apollo:latest

 * Starting PostgreSQL 9.6 database server
   ...done.
WEBAPOLLO_HOST_FLAG: 
CHADO_HOST_FLAG: 
Waiting for DB
/var/run/postgresql:5432 - accepting connections
Postgres is up, configuring database
psql: FATAL:  Peer authentication failed for user "apollo"
Apollo database not found, creating...
createdb: database creation failed: ERROR:  database "apollo" already exists
ERROR:  role "apollo" already exists
GRANT
Not using chado!
CATALINA_HOME '/usr/share/tomcat9'
CATALINA_BASE '/var/lib/tomcat9'
APOLLO PATH ''
FIXED_CTX PATH ''
WAR FILE '/var/lib/tomcat9/webapps/.war'
Apr 29, 2020 7:59:07 PM org.apache.catalina.startup.Catalina stopServer
SEVERE: No shutdown port configured. Shut down server through OS signal. Server not shut down.
Kill failed: $CATALINA_PID not set
<2>Cannot find specified temporary folder at [/var/lib/tomcat9/temp]
<6>Server version name:   Apache Tomcat/9.0.16 (Ubuntu)
<6>Server built:          Sep 11 2019 19:47:51 UTC
<6>Server version number: 9.0.16.0
<6>OS Name:               Linux
<6>OS Version:            4.19.76-linuxkit
<6>Architecture:          amd64
<6>Java Home:             /usr/lib/jvm/java-8-openjdk-amd64/jre
<6>JVM Version:           1.8.0_252-8u252-b09-1~18.04-b09
<6>JVM Vendor:            Private Build
```

**Comment by nathandunn** [comment]
@fbemm  Oh, so it seems to work. 

It should take less than a minute, usually about 30 seconds

There are two potential problems that could cause non-responsiveness:

- docker has insufficient memory (if its slow) or space, or a duplicate instance is running from within the container accidentaly
- your database mount is incorrect or not writeable (but also not seeing any errors)

**Comment by fbemm** [comment]
I think I found at least a hint:

`Not phoning home due to error: groovy.json.JsonException: Unable to process url: https://s3.amazonaws.com/apollo-usage-2.6.0-snapshot/ping.json?server=ApolloSever-46134221974758041141213341&environment=production&message=running&num_users=1&num_organisms=0`

Looks like the VM some how thinks she has connection to the internet (which in parts is correct) but the call from above will not work, since I am sitting behind a proxy.

Is there a way to switch the phoning home off?

**Comment by fbemm** [comment]
Docs --> `apollo.phone.phoneHome = false`

Is there a way to pass that to the Docker run command by exposing it via ENV?

**Comment by nathandunn** [comment]
@fbemm  I added the option in the latest docker environment in #259cd99 but I don't think it will make a difference. 

I'm not sure what your setup is, but I have some recommended reading within the docs from prior users setup and our own experiences:

- https://genomearchitect.readthedocs.io/en/latest/Configure.html?highlight=proxy#apache-proxy
- https://genomearchitect.readthedocs.io/en/latest/Configure.html?highlight=proxy#apache-nginx-configuration
- https://genomearchitect.readthedocs.io/en/latest/OpenIDConnectAuthentication.html?highlight=proxy
- https://genomearchitect.readthedocs.io/en/latest/Configure.html?highlight=proxy#adding-using-proxies

Let me know what you find.

**Comment by nathandunn** [comment]
I'm wondering if its possible to connect to the server from inside the proxy.   

More details about your proxy setup might be helpful.

**Comment by fbemm** [comment]
```
WEBAPOLLO_PHONE_HOME false

Configuring Shiro ...

Shiro Configured
Starting Quartz Scheduler in QuartzFactoryBean
2020-05-04 06:14:04,026 [Catalina-utility-2] WARN  apollo.UserService  - User exists admin@local.host and can not be added again.
b2020-05-04 06:16:13,315 [Actor Thread 1] WARN  apollo.PhoneHomeService  - Not phoning home due to error: groovy.json.JsonException: Unable to process url: https://s3.amazonaws.com/apollo-usage-2.6.0-snapshot/ping.json?server=ApolloSever-599391402178523483280848332&environment=production&message=start
```

It looks as the phone service is still on.

Checking on nginx now.

**Comment by nathandunn** [comment]
Okay, I am seeing that as well.  Working on a fix. 

However, would be surprised if it is failing based on that, since the code is catching any error, reporting it and then continuing:

https://github.com/GMOD/Apollo/blob/develop/grails-app/services/org/bbop/apollo/PhoneHomeService.groovy#L68

If it gets as far as phoning home, its likely to be an issue with connecting via the proxy.

**Comment by nathandunn** [comment]
I fixed the phoneHome bug here #be31b81f7d0668916bf92463a758506757cc5ada

**Comment by fbemm** [comment]
Options works now, spin up is faster but it still stops at the same step:

```
Starting Quartz Scheduler in QuartzFactoryBean
Not phoning home
2020-05-04 18:55:22,480 [main] WARN  apollo.UserService  - User exists admin@local.host and can not be added again.
Not phoning home
<6>Deployment of web application archive [/var/lib/tomcat9/webapps/.war] has finished in [48,986] ms
<6>Starting ProtocolHandler ["http-nio-8080"]
<6>Server startup in [49,078] milliseconds
<6>Deploying web application directory [/var/lib/tomcat9/webapps/ROOT]
...
Starting Quartz Scheduler in QuartzFactoryBean
Not phoning home
2020-05-04 18:56:13,927 [Catalina-utility-1] WARN  apollo.UserService  - User exists admin@local.host and can not be added again.
Not phoning home
<6>Deployment of web application directory [/var/lib/tomcat9/webapps/ROOT] has finished in [41,458] ms
```

**Comment by nathandunn** [comment]
It should be up and working at this point. as this looks like normal output.

1. Are you able to go into the docker image and verify that tomcat is running and 8080 is open?    
1. What command are you using to run it? 
1. How are you trying to reach it?

**Comment by fbemm** [comment]
2. `docker run -e WEBAPOLLO_PHONE_HOME=false -p 8080:8080 gmod/apollo:latest`

**Comment by fbemm** [comment]
3. I am simply trying to do a `curl localhost:8080` for starters on the host where the container is running

**Comment by fbemm** [comment]
1.
```

USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   4628   924 ?        Ss   19:58   0:00 /bin/sh -c "/launch.sh"
root         7  0.0  0.0  18376  3116 ?        S    19:58   0:00 bash /launch.sh
postgres    24  0.0  0.3 313340 26092 ?        S    19:58   0:00 /usr/lib/postgresql/9.6/bin/postgres -D /var/lib/postgresql/9.6/main -c config_file=/etc/postgresql/9.6/main/postgresql.conf
postgres    36  0.0  0.0 313340  4264 ?        Ss   19:58   0:00 postgres: 9.6/main: checkpointer process   
postgres    37  0.0  0.0 313340  4264 ?        Ss   19:58   0:00 postgres: 9.6/main: writer process   
postgres    38  0.0  0.0 313340  4264 ?        Ss   19:58   0:00 postgres: 9.6/main: wal writer process   
postgres    39  0.0  0.0 313752  7088 ?        Ss   19:58   0:00 postgres: 9.6/main: autovacuum launcher process   
postgres    40  0.0  0.0 168484  3468 ?        Ss   19:58   0:00 postgres: 9.6/main: stats collector process   
root       119 77.3 20.3 4752020 1661184 ?     Sl   19:59   2:40 /usr/lib/jvm/java-8-openjdk-amd64/bin/java -Djava.util.logging.config.file=/var/lib/tomcat9/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Dorg.apache.catalina.security.SecurityListener.UMASK=0027 -Dignore.endorsed.dirs= -classpath /usr/share/tomcat9/bin/bootstrap.jar:/usr/
postgres   140  0.0  0.1 314272 11636 ?        Ss   19:59   0:00 postgres: 9.6/main: apollo apollo 127.0.0.1(33744) idle
postgres   141  0.0  0.1 314264 11376 ?        Ss   19:59   0:00 postgres: 9.6/main: apollo apollo 127.0.0.1(33746) idle
postgres   142  0.0  0.1 314264 11380 ?        Ss   19:59   0:00 postgres: 9.6/main: apollo apollo 127.0.0.1(33748) idle
postgres   143  0.0  0.1 314264 11376 ?        Ss   19:59   0:00 postgres: 9.6/main: apollo apollo 127.0.0.1(33750) idle
postgres   144  0.9  0.2 316476 16588 ?        Ss   19:59   0:01 postgres: 9.6/main: apollo apollo 127.0.0.1(33752) idle
root       152  0.1  0.0  18504  3456 pts/0    Ss   19:59   0:00 bash
postgres   207  0.0  0.1 314264 11424 ?        Ss   20:00   0:00 postgres: 9.6/main: apollo apollo 127.0.0.1(33754) idle
postgres   208  0.0  0.1 314264 11428 ?        Ss   20:00   0:00 postgres: 9.6/main: apollo apollo 127.0.0.1(33756) idle
postgres   209  0.0  0.1 314264 11424 ?        Ss   20:00   0:00 postgres: 9.6/main: apollo apollo 127.0.0.1(33758) idle
postgres   210  0.0  0.1 314264 11488 ?        Ss   20:00   0:00 postgres: 9.6/main: apollo apollo 127.0.0.1(33760) idle
postgres   211  1.3  0.2 316724 16608 ?        Ss   20:00   0:01 postgres: 9.6/main: apollo apollo 127.0.0.1(33762) idle
root       245  0.0  0.0  34404  2900 pts/0    R+   20:02   0:00 ps aux
```

At the point where the container is hanging there is no tomcat running.

`echo $CATALINA_PID` stays empty.

**Comment by fbemm** [comment]
If I do a `curl localhost:8080` within the container it stays empty.

**Comment by nathandunn** [comment]
And your full output looks exactly [like this](https://github.com/GMOD/Apollo/issues/2471#issue-609172033)?

**Comment by nathandunn** [comment]
I get the same thing internally or externally:

```
docker exec -it b82d0c69527b /bin/bash
root@b82d0c69527b:/# curl -Iv http://localhost:8080/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> HEAD / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 302 
HTTP/1.1 302 
< Location: http://localhost:8080/annotator/index
Location: http://localhost:8080/annotator/index
< Transfer-Encoding: chunked
Transfer-Encoding: chunked
< Date: Mon, 04 May 2020 20:08:43 GMT
Date: Mon, 04 May 2020 20:08:43 GMT

< 
* Connection #0 to host localhost left intact
root@b82d0c69527b:/# curl -Iv http://localhost:8080/
```

**Comment by nathandunn** [comment]
Its redirecting to annotator /index

**Comment by fbemm** [comment]
Think I found something:

```
04-May-2020 20:05:12.649 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
04-May-2020 20:05:12.663 SEVERE [main] org.apache.catalina.util.LifecycleBase.handleSubClassException Failed to initialize component [Connector[HTTP/1.1-8080]]
 org.apache.catalina.LifecycleException: Protocol handler initialization failed
        at org.apache.catalina.connector.Connector.initInternal(Connector.java:983)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
        at org.apache.catalina.core.StandardService.initInternal(StandardService.java:535)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
        at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:1055)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
        at org.apache.catalina.startup.Catalina.load(Catalina.java:589)
        at org.apache.catalina.startup.Catalina.load(Catalina.java:612)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:306)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:491)
Caused by: java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:220)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:85)
        at org.apache.tomcat.util.net.NioEndpoint.initServerSocket(NioEndpoint.java:236)
        at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:210)
        at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1085)
        at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:1098)
        at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:557)
        at org.apache.coyote.http11.AbstractHttp11Protocol.init(AbstractHttp11Protocol.java:74)
        at org.apache.catalina.connector.Connector.initInternal(Connector.java:980)
        ... 13 more
```

**Comment by nathandunn** [comment]
I'm not exactly sure what this is:

```
root       119 77.3 20.3 4752020 1661184 ?     Sl   19:59   2:40 /usr/lib/jvm/java-8-openjdk-amd64/bin/java -Djava.util.logging.config.file=/var/lib/tomcat9/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Dorg.apache.catalina.security.SecurityListener.UMASK=0027 -Dignore.endorsed.dirs= -classpath /usr/share/tomcat9/bin/bootstrap.jar:/usr/
```

but I'm guessing that is tomcat, though I've never seen that incarnation of it.

**Comment by nathandunn** [comment]
Ah . . . yeah that's it.

It will do this sometimes depending on how you run docker. 

I've had to remove all of my docker images (or at least most of them) and then re-run it and it should work.

**Comment by fbemm** [comment]
I did a `docker container prune` and deleted all related images with `docker rmi`. Pulled from scratch but it ends at the same stage.

**Comment by fbemm** [comment]
What is interesting -> Browser URL now has a `/annotator/index` appended

**Comment by nathandunn** [comment]
That is correct.  It redirects their by default from `/` -> `/annotator/index` which indicates that you hit the proper end-point. 

I'm curious if you do:

    wget http://localhost:8080/annotator/index

and 

    cat index 

What you see.  If it looks like a bunch of html, then it is definitely working. 

(attached): 

```
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Annotator</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="apple-touch-icon" href="/Apollo-staging/assets/apple-touch-icon-c915103363017d14cea9c2a46ea12166.png">
<link rel="apple-touch-icon" sizes="114x114" href="/Apollo-staging/assets/apple-touch-icon-retina-21d524e96ee946f16c9b8fb4ea0c3f6e.png">
<link rel="stylesheet" href="/Apollo-staging/assets/annotator-e59f4dcb500c6447451291f47b48fc06.css"/>
<script src="/Apollo-staging/assets/application-a3c3e8f921d59509949d29765e94603f.js" type="text/javascript" ></script>
<link rel="shortcut icon" type="image/x-icon" href="/Apollo-staging/assets/webapollo_favicon-2f9cd4444838d27f01c1fdf8fe1d1226.ico"/>



<script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date();
        a = s.createElement(o),
            m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
</script>

<script>
    
    ga('create', 'UA-62921593-1', 'auto', {'name': 'Server0'});
    ga('Server0.send', 'pageview');
    
</script>
<script>
</script>

...
```

**Comment by fbemm** [comment]
Ok that works. Means that WebApollo is running. Then it's likely to be the nginx reverse proxy.

**Comment by nathandunn** [comment]
Yeah setting up that reverse proxy can be weird but if you follow the doc and are still stuck I would post to the forum as this is a common problem. 

Nathan

**Comment by fbemm** [comment]
Got it. Think it was a combination of the docker issue and a missing entry in the proxy settings;

Thanks a lot @nathandunn !
