### ISSUE TITLE
apollo.TrackService  - File does not exist

### ISSUE THREAD

**Issue by fbemm** [GMOD/Apollo#2484]
I am running WebApollo from Docker (latest from today).

When trying to create a new annotation nothing happens and the logs show the following.

The respective directory (/data/temporary) is 777.

The tomcat user has write access.

```
2020-05-06 10:38:20,480 [http-nio-8080-exec-10] WARN  apollo.TrackService  - File /data/temporary/apollo_data/45-VCAR does not exist
2020-05-06 10:38:20,481 [http-nio-8080-exec-10] WARN  apollo.TrackService  - File /data/temporary/apollo_data/45-VCAR can not be read
2020-05-06 10:38:20,482 [http-nio-8080-exec-10] WARN  apollo.TrackService  - File /data/temporary/apollo_data/45-VCAR can not be written to
2020-05-06 10:38:20,483 [http-nio-8080-exec-10] WARN  apollo.TrackService  - File /data/temporary/apollo_data/45-VCAR/extendedTrackList.json does not exist
2020-05-06 10:38:20,484 [http-nio-8080-exec-10] WARN  apollo.TrackService  - File /data/temporary/apollo_data/45-VCAR/extendedTrackList.json can not be read
2020-05-06 10:38:20,484 [http-nio-8080-exec-10] WARN  apollo.TrackService  - File /data/temporary/apollo_data/45-VCAR/extendedTrackList.json can not be written to
```

**Comment by fbemm** [comment]
https://github.com/GMOD/Apollo/issues/2198
https://github.com/GMOD/Apollo/issues/2159

**Comment by fbemm** [comment]
common_data_path is set to "/tmp". Also shown in the UI.

Looks like the subfolders are never created when adding an organism.

**Comment by nathandunn** [comment]
Oh, you don't want to set it to '/tmp'.  Data there gets deleted by the underlying system.  

You may also want to mount the volume `/data/temporary/apollo` to make sure it doesn't go away (depending on how you define your docker instance)

To clarify:

(1) are you able to upload a genome and see it? 
(2) are you able to add a track to it and see the track? 
(3) are you able to add annotations to that genome?

**Comment by fbemm** [comment]
I did the following to test things:

1. `mkdir jbrowse common postgres`
2. `chmod 777 common`
3. Unziped the volvox example into `jbrowse`
4.  `docker run -p 8080:8080 -v $PWD/jbrowse:/data -v $PWD/postgres:/var/lib/postgresql -v $PWD/common:/common gmod/apollo:latest`
5. Logged into WebApollo & changed common path to /common
6. Imported the volvox example from `/data/volvox` (genome & tracks are showing correctly)
7. Try to pick a gene and create a new annotation

What I get is this in the docker logs:

```
2020-05-06 19:14:01,204 [http-nio-8080-exec-7] WARN  apollo.TrackService  - File /common/65-VCAR does not exist
2020-05-06 19:14:01,204 [http-nio-8080-exec-7] WARN  apollo.TrackService  - File /common/65-VCAR can not be read
2020-05-06 19:14:01,205 [http-nio-8080-exec-7] WARN  apollo.TrackService  - File /common/65-VCAR can not be written to
2020-05-06 19:14:01,205 [http-nio-8080-exec-7] WARN  apollo.TrackService  - File /common/65-VCAR/extendedTrackList.json does not exist
2020-05-06 19:14:01,205 [http-nio-8080-exec-7] WARN  apollo.TrackService  - File /common/65-VCAR/extendedTrackList.json can not be read
2020-05-06 19:14:01,206 [http-nio-8080-exec-7] WARN  apollo.TrackService  - File /common/65-VCAR/extendedTrackList.json can not be written to
```
 
The folder is not created neither is the json file. 

7. Logged into the container
8. su -s /bin/bash tomcat
9. cd /common
10. touch test (works)

**Comment by fbemm** [comment]
The only thing that is created is `/data/apollo_data/test_file`

**Comment by nathandunn** [comment]
This worked for me.    I generally wouldn't recommend changing the internal `/common/` directory as its unnecessary, but it shouldn't matter (and it worked as expected). 

For (6) you are uploading it right (upload new genome) and adding the `volvox.fa` or `volvox.fa.zip`  download [from here](https://genomearchitect.readthedocs.io/en/latest/Apollo2Build.html?highlight=sample#adding-sample-data) ?

For (9) it looks like root is running tomcat, but again, shouldn't matter.   You should just stay as root.   I am assuming you are connecting as `docker exec -it <container-hash> /bin/bash`
For (10) what do you see when you type `ls -la` in `/common`

This is what I see:

```
root@0e44298ab5ac:/common# ls -la
total 4
drwxr-xr-x 3 root root   96 May  6 20:19 .
drwxr-xr-x 1 root root 4096 May  6 20:25 ..
drwxr-x--- 6 root root  192 May  6 20:28 65-v2
```

For (11) maybe repeat the step for test as root:

```
root@0e44298ab5ac:/common# ls -ltrca
total 4
drwxr-xr-x 1 root root 4096 May  6 20:25 ..
drwxr-x--- 6 root root  192 May  6 20:28 65-v2
-rw-r--r-- 1 root root    0 May  6 20:33 test
drwxr-xr-x 4 root root  128 May  6 20:33 .
```

Also for (11) can you confirm that you can see test at your mount point (where `$PWD/common` is) ?  

If you touch a test file in the $PWD/common mounted directory, do you see the file within docker under `/common`?

Sometimes you have to specify in the top-level file-system that you the current directory is available as mount-point, though usually it complains at the outset if not.

**Comment by fbemm** [comment]
For (6), I just pointed WebApollo to the unzipped directory /data/vcar. Is it necessary to use the UI uploader? I thought one can use existing JBrowse directories. Maybe this is my mistake!?

**Comment by fbemm** [comment]
This is the full log message from the container:

```
2020-05-07 10:51:24,354 [http-nio-8080-exec-3] WARN  apollo.TrackService  - File /common/5717-VCAR does not exist
2020-05-07 10:51:24,355 [http-nio-8080-exec-3] WARN  apollo.TrackService  - File /common/5717-VCAR can not be read
2020-05-07 10:51:24,355 [http-nio-8080-exec-3] WARN  apollo.TrackService  - File /common/5717-VCAR can not be written to
2020-05-07 10:51:24,355 [http-nio-8080-exec-3] WARN  apollo.TrackService  - File /common/5717-VCAR/extendedTrackList.json does not exist
2020-05-07 10:51:24,355 [http-nio-8080-exec-3] WARN  apollo.TrackService  - File /common/5717-VCAR/extendedTrackList.json can not be read
2020-05-07 10:51:24,356 [http-nio-8080-exec-3] WARN  apollo.TrackService  - File /common/5717-VCAR/extendedTrackList.json can not be written to
2020-05-07 10:51:24,562 [http-nio-8080-exec-6] ERROR errors.GrailsExceptionResolver  - IOException occurred when processing request: [GET] /12880722614966429471737258064/jbrowse/plugins/WebApollo/jslib/websocket/spring-websocket.js
Broken pipe. Stacktrace follows:
java.io.IOException: Broken pipe
        at org.bbop.apollo.JbrowseController.passthrough(JbrowseController.groovy:615)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-05-07 10:51:24,567 [http-nio-8080-exec-6] ERROR errors.GrailsExceptionResolver  - IllegalStateException occurred when processing request: [GET] /12880722614966429471737258064/jbrowse/plugins/WebApollo/jslib/websocket/spring-websocket.js
getOutputStream() has already been called for this response. Stacktrace follows:
org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: getOutputStream() has already been called for this response
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: getOutputStream() has already been called for this response
        at java.io.FilterWriter.flush(FilterWriter.java:100)
        ... 12 more
```

**Comment by fbemm** [comment]
Started from scratch leaving the common path as it is:

```
2020-05-07 11:42:50,224 [http-nio-8080-exec-5] INFO  apollo.UserController  - updateTrackListPreference
2020-05-07 11:42:50,234 [http-nio-8080-exec-5] INFO  apollo.UserController  - Added userOrganismPreference false
2020-05-07 11:42:51,197 [http-nio-8080-exec-4] WARN  apollo.TrackService  - File /data/temporary/apollo_data/33-VCAR does not exist
2020-05-07 11:42:51,198 [http-nio-8080-exec-4] WARN  apollo.TrackService  - File /data/temporary/apollo_data/33-VCAR can not be read
2020-05-07 11:42:51,199 [http-nio-8080-exec-4] WARN  apollo.TrackService  - File /data/temporary/apollo_data/33-VCAR can not be written to
2020-05-07 11:42:51,199 [http-nio-8080-exec-4] WARN  apollo.TrackService  - File /data/temporary/apollo_data/33-VCAR/extendedTrackList.json does not exist
2020-05-07 11:42:51,199 [http-nio-8080-exec-4] WARN  apollo.TrackService  - File /data/temporary/apollo_data/33-VCAR/extendedTrackList.json can not be read
2020-05-07 11:42:51,199 [http-nio-8080-exec-4] WARN  apollo.TrackService  - File /data/temporary/apollo_data/33-VCAR/extendedTrackList.json can not be written to
2020-05-07 11:42:55,805 [http-nio-8080-exec-7] INFO  apollo.UserController  - updateTrackListPreference
2020-05-07 11:42:55,810 [http-nio-8080-exec-7] INFO  apollo.UserController  - Added userOrganismPreference true
2020-05-07 11:42:56,462 [http-nio-8080-exec-10] WARN  apollo.TrackService  - File /data/temporary/apollo_data/33-VCAR does not exist
2020-05-07 11:42:56,463 [http-nio-8080-exec-10] WARN  apollo.TrackService  - File /data/temporary/apollo_data/33-VCAR can not be read
2020-05-07 11:42:56,463 [http-nio-8080-exec-10] WARN  apollo.TrackService  - File /data/temporary/apollo_data/33-VCAR can not be written to
2020-05-07 11:42:56,464 [http-nio-8080-exec-10] WARN  apollo.TrackService  - File /data/temporary/apollo_data/33-VCAR/extendedTrackList.json does not exist
2020-05-07 11:42:56,464 [http-nio-8080-exec-10] WARN  apollo.TrackService  - File /data/temporary/apollo_data/33-VCAR/extendedTrackList.json can not be read
2020-05-07 11:42:56,464 [http-nio-8080-exec-10] WARN  apollo.TrackService  - File /data/temporary/apollo_data/33-VCAR/extendedTrackList.json can not be written to
```

**Comment by fbemm** [comment]
Once again this is how I start:

`docker run -p 8080:8080 -v $PWD/jbrowse:/data -v $PWD/postgres:/var/lib/postgresql -e WEBAPOLLO_PHONE_HOME=false gmod/apollo:latest`

This is how the data structure looks like in $PWD:

```
.
├── jbrowse
│   ├── amel
│   │   ├── amel.css
│   │   ├── bam
│   │   ├── bigwig
│   │   ├── css
│   │   ├── custom.css
│   │   ├── names
│   │   ├── seq
│   │   ├── trackList.json
│   │   └── tracks
│   ├── apollo_data
│   │   └── test_file
│   ├── temporary
│   │   └── apollo_data
│   └── vcar
│       ├── names
│       ├── raw
│       ├── seq
│       ├── trackList.json
│       ├── tracks
│       └── tracks.conf
└── postgres
    └── 9.6
        └── main

19 directories, 6 files
```

**Comment by nathandunn** [comment]
> For (6), I just pointed WebApollo to the unzipped directory /data/vcar. Is it necessary to use the UI uploader? I thought one can use existing JBrowse directories. Maybe this is my mistake!?

I think you were correct here, especially after I look at your directory structure.  

I'm assuming you are using: 
![image](https://user-images.githubusercontent.com/751274/81308217-61b35d80-9036-11ea-8a7c-f34fc5fdfbbd.png)

**Comment by nathandunn** [comment]
nothing execption in [these log files](https://github.com/GMOD/Apollo/issues/2484#issuecomment-625180314)

**Comment by fbemm** [comment]
> > For (6), I just pointed WebApollo to the unzipped directory /data/vcar. Is it necessary to use the UI uploader? I thought one can use existing JBrowse directories. Maybe this is my mistake!?
> 
> I think you were correct here, especially after I look at your directory structure.
> 
> I'm assuming you are using:
> ![image](https://user-images.githubusercontent.com/751274/81308217-61b35d80-9036-11ea-8a7c-f34fc5fdfbbd.png)

Yes, this is how I added the volvox example.

**Comment by fbemm** [comment]
> nothing execption in [these log files](https://github.com/GMOD/Apollo/issues/2484#issuecomment-625180314)

I thought that. Somehow just using the "Add New Organism" way does not seem to create the temporary files. You said this is happening for you using my commands?

**Comment by nathandunn** [comment]
I'm not seeing your results. `Add New Organism` doesn't create new files, just reads the JBrowse directory.

To start from scratch did you do:

- `rm -rf $PWD/postgres/*`
- `docker prune -a `
- `docker pull gmod/apollo:latest`
- ```docker run -p 8080:8080 -v $PWD/jbrowse:/data -v $PWD/postgres:/var/lib/postgresql -e WEBAPOLLO_PHONE_HOME=false gmod/apollo:latest```

**Comment by fbemm** [comment]
> > Started from scratch leaving the common path as it is:
> 
> ```
> 2020-05-07 11:42:50,224 [http-nio-8080-exec-5] INFO  apollo.UserController  - updateTrackListPreference
> 2020-05-07 11:42:50,234 [http-nio-8080-exec-5] INFO  apollo.UserController  - Added userOrganismPreference false
> 2020-05-07 11:42:51,197 [http-nio-8080-exec-4] WARN  apollo.TrackService  - File /data/temporary/apollo_data/33-VCAR does not exist
> 2020-05-07 11:42:51,198 [http-nio-8080-exec-4] WARN  apollo.TrackService  - File /data/temporary/apollo_data/33-VCAR can not be read
> ...
> ```
> 
> Is this what you get on startup?

Yes right away, without even trying to create a new annotation.

**Comment by nathandunn** [comment]
You may also wish to look through your jbrowse data directory for the file `extendedTrackList.json` but my guess is that those are actually in your container, but we can see.

**Comment by fbemm** [comment]
> I'm not seeing your results. `Add New Organism` doesn't create new files, just reads the JBrowse directory.
> 
> To start from scratch did you do:
> 
>     * `rm -rf $PWD/postgres/*`
> 
>     * `docker prune -a `
> 
>     * `docker pull gmod/apollo:latest`
> 
>     * `docker run -p 8080:8080 -v $PWD/jbrowse:/data -v $PWD/postgres:/var/lib/postgresql -e WEBAPOLLO_PHONE_HOME=false gmod/apollo:latest`

```
rm -rf $PWD/postgres/*
docker system prune -a
docker pull gmod/apollo:latest
docker run -p 8080:8080 -v $PWD/jbrowse:/data -v $PWD/postgres:/var/lib/postgresql -e WEBAPOLLO_PHONE_HOME=false gmod/apollo:latest
```

**Comment by fbemm** [comment]
> `extendedTrackList.json`

The volvox example data does not contain such a file. I thought that the temprary data folder is created by Apollo including that file.

**Comment by nathandunn** [comment]
> The volvox example data does not contain such a file. I thought that the temprary data folder is created by Apollo including that file.

That is correct.  Just wanted to double-check. 

Were you able to do the above command starting with removing the postgres/* directory?

**Comment by nathandunn** [comment]
I should mention (though I'm sure its obvious), that you should stop all containers first.

**Comment by fbemm** [comment]
Did a full run again:

```
docker system prune -a
mkdir /webapollo
cd /webapollo
mkdir jbrowse postgres
docker pull gmod/apollo:latest
docker run -p 8080:8080 -v /webapollo/jbrowse:/data -v /webapollo/postgres:/var/lib/postgresql -e WEBAPOLLO_PHONE_HOME=false gmod/apollo:latest
```

Of note, /webapollo is now on the VM I am working on and not a NAS drive.

Still:

```
2020-05-07 15:18:14,187 [http-nio-8080-exec-10] INFO  apollo.UserController  - updateTrackListPreference
2020-05-07 15:18:14,208 [http-nio-8080-exec-10] INFO  apollo.UserController  - Added userOrganismPreference false
2020-05-07 15:18:15,569 [http-nio-8080-exec-1] WARN  apollo.TrackService  - File /data/temporary/apollo_data/33-VCAR does not exist
2020-05-07 15:18:15,570 [http-nio-8080-exec-1] WARN  apollo.TrackService  - File /data/temporary/apollo_data/33-VCAR can not be read
2020-05-07 15:18:15,570 [http-nio-8080-exec-1] WARN  apollo.TrackService  - File /data/temporary/apollo_data/33-VCAR can not be written to
2020-05-07 15:18:15,570 [http-nio-8080-exec-1] WARN  apollo.TrackService  - File /data/temporary/apollo_data/33-VCAR/extendedTrackList.json does not exist
2020-05-07 15:18:15,571 [http-nio-8080-exec-1] WARN  apollo.TrackService  - File /data/temporary/apollo_data/33-VCAR/extendedTrackList.json can not be read
2020-05-07 15:18:15,571 [http-nio-8080-exec-1] WARN  apollo.TrackService  - File /data/temporary/apollo_data/33-VCAR/extendedTrackList.json can not be written to
```

**Comment by nathandunn** [comment]
what is in `/webapollo/jbrowse` ?

**Comment by fbemm** [comment]
```
.
├── apollo_data
│   └── test_file
├── temporary
│   └── apollo_data
└── vcar
    ├── names
    ├── raw
    ├── seq
    ├── trackList.json
    ├── tracks
    └── tracks.conf

8 directories, 3 files
```

**Comment by nathandunn** [comment]
is that what you see before you add an organism?

**Comment by fbemm** [comment]
What is added is:

```
├── temporary
│   └── apollo_data
```

Everything else is there after deployment.

**Comment by nathandunn** [comment]
After this step:

```
docker run -p 8080:8080 -v /webapollo/jbrowse:/data -v /webapollo/postgres:/var/lib/postgresql -e WEBAPOLLO_PHONE_HOME=false gmod/apollo:latest
```

but before you add an organism, what is in the `/webapollo/jbrowse` and `/webapollo/postgres` directories?

**Comment by fbemm** [comment]
This is where I start:

```
/webapollo# tree -L 3
.
├── jbrowse
│   └── vcar
│       ├── names
│       ├── raw
│       ├── seq
│       ├── trackList.json
│       ├── tracks
│       └── tracks.conf
└── postgres

7 directories, 2 files
```

Then I do:
`
docker run -p 8080:8080 -v /webapollo/jbrowse:/data -v /webapollo/postgres:/var/lib/postgresql -e WEBAPOLLO_PHONE_HOME=false gmod/apollo:latest`

Which gives me:
```

.
├── jbrowse
│   ├── apollo_data
│   │   └── test_file
│   ├── temporary
│   │   └── apollo_data
│   └── vcar
│       ├── names
│       ├── raw
│       ├── seq
│       ├── trackList.json
│       ├── tracks
│       └── tracks.conf
└── postgres
    └── 9.6
        └── main

12 directories, 3 files
```

So correction here, the temporary folder is there before I add an organism.

Than adding through the UI gives:
```

.
├── jbrowse
│   ├── apollo_data
│   │   └── test_file
│   ├── temporary
│   │   └── apollo_data
│   └── vcar
│       ├── names
│       ├── raw
│       ├── seq
│       ├── trackList.json
│       ├── tracks
│       └── tracks.conf
└── postgres
    └── 9.6
        └── main

12 directories, 3 files
```

And right after adding, I get the first errors:```


2020-05-07 15:42:40,431 [http-nio-8080-exec-5] WARN  apollo.TrackService  - File /data/temporary/apollo_data/33-VCAR does not exist
2020-05-07 15:42:40,432 [http-nio-8080-exec-5] WARN  apollo.TrackService  - File /data/temporary/apollo_data/33-VCAR can not be read
2020-05-07 15:42:40,432 [http-nio-8080-exec-5] WARN  apollo.TrackService  - File /data/temporary/apollo_data/33-VCAR can not be written to
2020-05-07 15:42:40,432 [http-nio-8080-exec-5] WARN  apollo.TrackService  - File /data/temporary/apollo_data/33-VCAR/extendedTrackList.json does not exist
2020-05-07 15:42:40,432 [http-nio-8080-exec-5] WARN  apollo.TrackService  - File /data/temporary/apollo_data/33-VCAR/extendedTrackList.json can not be read
2020-05-07 15:42:40,433 [http-nio-8080-exec-5] WARN  apollo.TrackService  - File /data/temporary/apollo_data/33-VCAR/extendedTrackList.json can not be written to
```

**Comment by nathandunn** [comment]
I'm going to guess that if you do this without `vcar` in the `jbrowse` directory you don't see this error.   For example, if you did this with ONLY volvox.

(1) Can you confirm that there is no error if you ONLY add volvox? 

If you don't see this error, then something in your vcar directory is causing it to look into a temporary data directory.

(2) When you add the vcar can you confirm that this is what you are doing? 

![image](https://user-images.githubusercontent.com/751274/81316164-1605b180-9040-11ea-8e70-8ea85ed0da34.png)

If the answers to (1) and (2) are both yes, is it possible for you to send me your vcar file?   Either here or directly to my email (nathandunn   at  lbl dot gov)

**Comment by fbemm** [comment]
Ok so vcar is volvox! I just renamed it. But it is the sample volvox data.

**Comment by nathandunn** [comment]
Ah okay.  And the answer for (1) and (2) are yes?

**Comment by fbemm** [comment]
Just downloaded, unzipped and added it again as volvox, same result.

**Comment by fbemm** [comment]
(1) no -> the volvox data is what I am trying to get to work
(2) yes -> this is how I added volvox

**Comment by fbemm** [comment]
```
docker ps
CONTAINER ID        IMAGE                COMMAND                   CREATED             STATUS              PORTS                    NAMES
e6a1292f5e69        gmod/apollo:latest   "/bin/sh -c \"/launch…"   About an hour ago   Up About an hour    0.0.0.0:8080->8080/tcp   wizardly_pare
docker stop e6a1292f5e69
docker system prune -a
rm -rf /webapollo
mkdir /webapollo
cd /webapollo
mkdir jbrowse postgres
cd jbrowse
wget https://s3.amazonaws.com/apollo-data/volvox.tgz
tar xf volvox.tgz
cd ..
docker pull gmod/apollo:latest
docker run -p 8080:8080 -v /webapollo/jbrowse:/data -v /webapollo/postgres:/var/lib/postgresql -e WEBAPOLLO_PHONE_HOME=false gmod/apollo:latest
```

![Screenshot from 2020-05-07 18-52-15](https://user-images.githubusercontent.com/8361254/81322234-f4361a00-9093-11ea-9cf7-770df6262db9.png)

**Comment by nathandunn** [comment]
Okay.  I'm getting the same thing on a vanilla Ubuntu 18.  I will take a look. 

Sorry for the long slog to get here.

**Comment by fbemm** [comment]
My way of supporting WebApollo ;) ... which saved my butt gazillions of times!

**Comment by nathandunn** [comment]
@fbemm  I am getting that error, but its not preventing from adding annotations, which makes sense. 

How are you adding annotations? 

Can you show me the:
-  tomcat logs generated from creating an annotation (my guess is that you won't see anything generated)
- web console log generated from creating an annotation (network traffic XHR and WS traffic)
- screenshot of track prior to adding and method (dragging, or right-clicking)
- after you add it . . if you don't see anything after 10-15 seconds, try refreshing and seeing if it showed up
- can you show me the annotator panel after your refresh? 

The most common issue is that proxies tend to screw up the proxy pass so you don't see it right away (and so you need to refresh).

From my EC2 instance:

![image](https://user-images.githubusercontent.com/751274/81324397-c5945100-904b-11ea-8543-3046c6ec142f.png)

Feel free to play with this instance run with your instructions to see if you see any differences in behavior from your instance:  http://ec2-54-208-148-176.compute-1.amazonaws.com:8080/annotator/index

**Comment by fbemm** [comment]
(1) Tomcat logs stay as they are
![after-add-with-right-click](https://user-images.githubusercontent.com/8361254/81326331-f8653600-9099-11ea-80b7-e640eaaf876b.png)

(2) Webconsole

![console](https://user-images.githubusercontent.com/8361254/81326256-da97d100-9099-11ea-8db8-b212f82c1d5d.png)

(3) Prior to Add Annotation via Right-Click

![prior-to-add](https://user-images.githubusercontent.com/8361254/81326275-e1264880-9099-11ea-8950-9e2ec082395d.png)

(4) Prior to Add Annotation via Right-Click

![after-add-with-right-click](https://user-images.githubusercontent.com/8361254/81326348-fef3ad80-9099-11ea-8353-4c27cebfd1bd.png)

Logs are comparable between AWS and my VM until adding an annotation. Looks as simply nothing is happening.

AWS Log:

![aws](https://user-images.githubusercontent.com/8361254/81326503-3a8e7780-909a-11ea-9f1e-dee1f853dbab.png)

VM Log:

![vm](https://user-images.githubusercontent.com/8361254/81326520-40845880-909a-11ea-87fb-dcc374d00e98.png)

**Comment by fbemm** [comment]
nginx logs & errors are also not showing anything when I try to add an annotation.

**Comment by nathandunn** [comment]
Its definitely not connecting to the websocket, which is why you aren't seeing anything appear right away.  It should use a backup long-polling, but I feel like that has been less reliable than getting web sockets working. 

Does it work for my EC2 instance then?

Is nothing is annotated on a refreshing you page on your instance? (steps 4 and 5 from above)

**Comment by nathandunn** [comment]
Were you able to make your way through this? 

https://genomearchitect.readthedocs.io/en/latest/Configure.html?highlight=proxy#nginx-proxy-from-version-1-4-on

**Comment by fbemm** [comment]
It works on the EC2 instance. But on my local VM it just stays silent is not working, even after refreshing the page.

**Comment by nathandunn** [comment]
Okay.   I'm about 95% sure its the nginx proxy of websockets then.   If you haven't configured it here: https://genomearchitect.readthedocs.io/en/latest/Configure.html?highlight=proxy#nginx-proxy-from-version-1-4-on 

that is probably the issue.   If you have more details on your proxy configuration that would be helpful.   That and/or posting it here: https://groups.google.com/a/lbl.gov/forum/#!forum/apollo as there are many variations on this theme.

**Comment by fbemm** [comment]
@nathandunn I fixed it. If am not mistaken, it was the time out settings for the proxy that killed it. I initially used the one from the docs but now added more precise parameters and that solved the problem. 

```
      # Timeouts
      proxy_connect_timeout 999999;
      proxy_send_timeout 999999;
      proxy_read_timeout 999999;

      # Buffers
      proxy_buffer_size 4k;
      proxy_buffers 4 32k;
      proxy_busy_buffers_size 64k;
      proxy_temp_file_write_size 64k;
```

What a debug tour. Thanks for sticking with me. I still have a bug, the links generated for sharing contain the local ip address and fail to resolve, but I guess this is also linked to the proxy settings.

**Comment by nathandunn** [comment]
Excellent.  Well, close this one if its all working and open another issue for the loadLinks when you have an idea of what you want there (I imagine some setting for generating the base URL?).
