### ISSUE TITLE
add/edit/delete attributes

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#250]
2015-04-12 22:15:56,853 [Actor Thread 9] ERROR apollo.AnnotationEditorController  - METHOD NOT found addNonReservedProperties
2015-04-12 22:15:56,854 [clientInboundChannel-3] ERROR springwebsocket.GrailsSimpAnnotationMethodMessageHandler  - Unhandled exception
groovy.lang.MissingPropertyException: No such property: messaged for class: org.bbop.apollo.AnnotationException
Possible solutions: message
	at org.bbop.apollo.AnnotationEditorController.sendError(AnnotationEditorController.groovy:621)
	at org.bbop.apollo.AnnotationEditorController.annotationEditor(AnnotationEditorController.groovy:611)

**Comment by nathandunn** [comment]
need to wire "addNonReservedProperties" and "deleteNonReservedProperties"

**Comment by nathandunn** [comment]
- addNonReservedProperties
- updateNonReservedProperties
- deleteNonReservedProperties 

. . . for some reason not saving nonReservedProperties correctly *should be tag=value*

**Comment by monicacecilia** [comment]
Yeppers... this is working well. :dancer:
