### ISSUE TITLE
Trouble loading organism from command line

### ISSUE THREAD

**Issue by ajulian0416** [GMOD/Apollo#2568]
I can load an organism from the GUI, but when I try to load an organism from the command line with:

/home/'xxx'/opt/Apollo-2.6.2/docs/web_services/examples/groovy/add_organism.groovy \
-name E_hellem_v2 \
-genus Encephalitozoon \ 
-species hellem \
-url http://localhost:8080/apollo \
-directory /media/FatCat/Apollo/data/E_hellem_v2 \
-username 'xxx' \
-password 'xxx'

I get the following error. Looking forward to your help.

Cheers 

org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
General error during conversion: Error grabbing Grapes -- [download failed: org.apache.httpcomponents#httpclient;4.2.1!httpclient.jar, download failed: org.apache.httpcomponents#httpcore;4.2.1!httpcore.jar, download failed: commons-lang#commons-lang;2.4!commons-lang.jar]

java.lang.RuntimeException: Error grabbing Grapes -- [download failed: org.apache.httpcomponents#httpclient;4.2.1!httpclient.jar, download failed: org.apache.httpcomponents#httpcore;4.2.1!httpcore.jar, download failed: commons-lang#commons-lang;2.4!commons-lang.jar]
	at groovy.grape.GrapeIvy.getDependencies(GrapeIvy.groovy:455)
	at groovy.grape.GrapeIvy.resolve(GrapeIvy.groovy:625)
	at groovy.grape.GrapeIvy.resolve(GrapeIvy.groovy:592)
	at groovy.grape.GrapeIvy.grab(GrapeIvy.groovy:256)
	at groovy.grape.Grape$1.run(Grape.java:174)
	at groovy.grape.Grape$1.run(Grape.java:160)
	at java.security.AccessController.doPrivileged(Native Method)
	at groovy.grape.Grape.grab(Grape.java:160)
	at groovy.grape.GrabAnnotationTransformation.visit(GrabAnnotationTransformation.java:377)
	at org.codehaus.groovy.transform.ASTTransformationVisitor.lambda$addPhaseOperationsForGlobalTransforms$4(ASTTransformationVisitor.java:337)
	at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:901)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:671)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:635)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:389)
	at groovy.lang.GroovyClassLoader.lambda$parseClass$3(GroovyClassLoader.java:332)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:330)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:526)
	at groovy.lang.GroovyShell.run(GroovyShell.java:359)
	at groovy.lang.GroovyShell.run(GroovyShell.java:349)
	at groovy.ui.GroovyMain.processOnce(GroovyMain.java:652)
	at groovy.ui.GroovyMain.run(GroovyMain.java:398)
	at groovy.ui.GroovyMain.access$1400(GroovyMain.java:68)
	at groovy.ui.GroovyMain$GroovyCommand.process(GroovyMain.java:322)
	at groovy.ui.GroovyMain.processArgs(GroovyMain.java:142)
	at groovy.ui.GroovyMain.main(GroovyMain.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:111)
	at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:129)

1 error

**Comment by nathandunn** [comment]
I think there are a few options:

1. this this fixing the groovy configuration: https://stackoverflow.com/a/17606499/1739366 
2. write a shell script that does the same thing (or I can if need be)
3. use pipy apollo: https://pypi.org/project/apollo/

```
arrow organisms  add_organism -h
Usage: arrow organisms add_organism [OPTIONS] COMMON_NAME DIRECTORY

  Add an organism

  Output:

      a dictionary with information about the new organism

Options:
  --blatdb TEXT      Server-side path to 2bit index of the genome for Blat
  --genus TEXT       Genus
  --species TEXT     Species
  --public           Should the organism be public or not
  --metadata TEXT    JSON formatted arbitrary metadata
  --suppress_output  Suppress output of all organisms (true / false) (default
                     false)

  -h, --help         Show this message and exit.
```

I would recommend using the apollo library

**Comment by ajulian0416** [comment]
Your first link resolved my issue.

![image](https://user-images.githubusercontent.com/72114871/107841576-8ab10d80-6d81-11eb-93f6-ff3c52a13bd0.png)

Thank you for your help!
