### ISSUE TITLE
Canot build from Develop branch

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#2588]
* Provide what you were doing and what you expected to see.  Screenshots, directory, config files are a plus if relevant.
I have been able to build but cannot.  I am currently testing off the develop branch ( [commit 3888f793819bce](https://github.com/GMOD/Apollo/commit/3888f793819bce746d4396e5b8b28d82ec10e1a0) ) 

```
Grails not found using grailsw
Using gradlew
Gradle version: 2.11
Node Version: 8
Npm Version: 6
Yarn Version: 1
javac 1.8.0_275 found
javac installed
| Application cleaned.
...
...
...
...
...
...
...
Gathering system information ...done.
NOTE: Legacy scripts wig-to-json.pl and bam-to-json.pl have been removed from setup. Their functionality has been superseded by add-bam-track.pl and add-bw-track.pl. If you require the old versions, please use JBrowse 1.12.3 or earlier.
Installing node.js dependencies and building with webpack ...done.
Installing Perl prerequisites ... failed.  See setup.log file for error messages. As a first troubleshooting step, make sure development libraries and header files for GD, Zlib, and libpng are installed and try again.

Formatting Volvox example data ... failed.  See setup.log file for error messages.

Formatting Yeast example data ... failed.  See setup.log file for error messages.
:javac
Note: /Users/chrislocal/gir-repos/Apollo/src/gwt/org/bbop/apollo/gwt/client/TrackPanel.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:gwtc FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gwtc'.
> Java returned: 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4 mins 35.895 secs
***************************************
NOTE: Please set the memory for your servlet container (tomcat, jetty, etc.) or Apollo may not start correctly: http://genomearchitect.readthedocs.io/en/latest/Troubleshooting.html#suggested-tomcat-memory-settings
***************************************


```

**Comment by nathandunn** [comment]
@childers  Sorry for the delay. 

Things to try:

1. clean and rebuild.  I currently have to do this when deploying

    ./apollo clean-app &&  ./apollo deploy

2. if you have changes to the gwtc code, they will sometimes break. I would do this:

    ./gradlew gwtc --info --stacktrace

3. what was the original command you ran?

**Comment by childers** [comment]
1. I normally use ```./apollo clean-all; ./apollo deploy```
2. I don't think I changed the gwtc code, but I had modified the login pages based on Agency requirements.  These changes were working fine on the older version of the code.  I only modified one page, and added assets.
```$ ./gradlew gwtc --info --stacktrace
Starting Build
Settings evaluated using settings file '/Users/chrislocal/gir-repos/Apollo/settings.gradle'.
Projects loaded. Root project using build file '/Users/chrislocal/gir-repos/Apollo/build.gradle'.
Included projects: [root project 'nathanApolloMaster']
Evaluating root project 'nathanApolloMaster' using build file '/Users/chrislocal/gir-repos/Apollo/build.gradle'.
Final JBrowse settings [git:[url:https://github.com/GMOD/jbrowse, tag:1.16.10-release, alwaysRecheck:true], plugins:[WebApollo:[included:true], NeatHTMLFeatures:[included:true], NeatCanvasFeatures:[included:true], RegexSequenceSearch:[included:true], HideTrackLabels:[included:true], NAL_CSS:[git:https://github.com/NAL-i5K/NAL_CSS, branch:supports_1.16.5-release, alwaysPull:true, alwaysRecheck:true], ColorByType:[git:https://github.com/NAL-i5K/ColorByType, branch:master, alwaysPull:true, alwaysRecheck:true]]]
Final plugins [WebApollo:[included:true], NeatHTMLFeatures:[included:true], NeatCanvasFeatures:[included:true], RegexSequenceSearch:[included:true], HideTrackLabels:[included:true], NAL_CSS:[git:https://github.com/NAL-i5K/NAL_CSS, branch:supports_1.16.5-release, alwaysPull:true, alwaysRecheck:true], ColorByType:[git:https://github.com/NAL-i5K/ColorByType, branch:master, alwaysPull:true, alwaysRecheck:true]]
All projects evaluated.
Selected primary task 'gwtc' from project :
Tasks to be executed: [task ':javac', task ':gwtc']
:javac (Thread[main,5,main]) started.
:javac
Executing task ':javac' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
:javac (Thread[main,5,main]) completed. Took 0.082 secs.
:gwtc (Thread[main,5,main]) started.
:gwtc
Executing task ':gwtc' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
[ant:java] Compiling module org.bbop.apollo.gwt.Annotator
[ant:java]    Computing all possible rebind results for 'org.bbop.apollo.gwt.client.LoginDialog.Binder'
[ant:java]       Rebinding org.bbop.apollo.gwt.client.LoginDialog.Binder
[ant:java]          Invoking generator com.google.gwt.uibinder.rebind.UiBinderGenerator
[ant:java]             [ERROR] The prefix "bhtml" for element "bhtml:Strong" is not bound.
[ant:java]             [ERROR] Error parsing XML (line 22): The prefix "bhtml" for element "bhtml:Strong" is not bound.
[ant:java]    [ERROR] Errors in 'org/bbop/apollo/gwt/client/LoginDialog.java'
[ant:java]       [ERROR] Line 27: Failed to resolve 'org.bbop.apollo.gwt.client.LoginDialog.Binder' via deferred binding
[ant:java]    [WARN] For the following type(s), generated source was never committed (did you forget to call commit()?)
[ant:java]       [WARN] org.bbop.apollo.gwt.client.LoginDialog_BinderImpl
[ant:java]    Computing all possible rebind results for 'org.bbop.apollo.gwt.client.SequencePanel_SequencePanelUiBinderImpl.Template'
[ant:java]       Rebinding org.bbop.apollo.gwt.client.SequencePanel_SequencePanelUiBinderImpl.Template
[ant:java]          Invoking generator com.google.gwt.safehtml.rebind.SafeHtmlTemplatesGenerator
[ant:java]             Constructing interface org.bbop.apollo.gwt.client.SequencePanel_SequencePanelUiBinderImpl.Template
[ant:java]                Generating method body for html3()
[ant:java]                   [WARN] Template with variable in CSS attribute context: The template code generator cannot guarantee HTML-safety of the template -- please inspect manually or use SafeStyles to specify arguments in a CSS attribute context
:gwtc FAILED
:gwtc (Thread[main,5,main]) completed. Took 6.39 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gwtc'.
> Java returned: 1

* Try:
Run with --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':gwtc'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:45)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: /Users/chrislocal/gir-repos/Apollo/build.xml:35: Java returned: 1
	at org.apache.tools.ant.taskdefs.Java.execute(Java.java:111)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.gradle.api.tasks.ant.AntTarget.executeAntTarget(AntTarget.java:37)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:227)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 60 more


BUILD FAILED

Total time: 9.932 secs
Stopped 0 compiler daemon(s).
```
3. I ran ```./apollo clean-all; ./apollo deploy```

**Comment by nathandunn** [comment]
Chris,

Its definitely an error in LoginDialog.ui.xml

However, I think its an easy fix, as in you might be missing a header.

Can you post the LoginDialog.ui.xml (or provide a pointer to it?)? 

Nathan

**Comment by childers** [comment]
I'm trying to find that in the apollo repo but don't see it. I've also searched in my local instance with no luck.  Can you paste a relative path to it?

**Comment by nathandunn** [comment]
https://github.com/GMOD/Apollo/blob/develop/src/gwt/org/bbop/apollo/gwt/client/LoginDialog.ui.xml

. . 
src/gwt/org/bbop/apollo/gwt/client

**Comment by nathandunn** [comment]
@childers  Oh, if its this, I can definitely see the error: https://github.com/NAL-i5K/Apollo/blob/master/src/gwt/org/bbop/apollo/gwt/client/LoginDialog.ui.xml

**Comment by nathandunn** [comment]
I'll add a quick PR to fix it.  Not sure what got dropped

**Comment by nathandunn** [comment]
@childers 

Its just missing a line in the header.  I can't create a PR, but its pretty straightforward:

```
diff --git a/src/gwt/org/bbop/apollo/gwt/client/LoginDialog.ui.xml b/src/gwt/org/bbop/apollo/gwt/client/LoginDialog.ui.xml
index eb02b6c94..dbcab01a4 100644
--- a/src/gwt/org/bbop/apollo/gwt/client/LoginDialog.ui.xml
+++ b/src/gwt/org/bbop/apollo/gwt/client/LoginDialog.ui.xml
@@ -1,6 +1,7 @@
 <ui:UiBinder xmlns:ui='urn:ui:com.google.gwt.uibinder'
              xmlns:b="urn:import:org.gwtbootstrap3.client.ui"
-        >
+             xmlns:bhtml="urn:import:org.gwtbootstrap3.client.ui.html"
+>
 
 
     <ui:style>
```

**Comment by nathandunn** [comment]
i.e.,:

```
<ui:UiBinder xmlns:ui='urn:ui:com.google.gwt.uibinder'
             xmlns:b="urn:import:org.gwtbootstrap3.client.ui"
             xmlns:bhtml="urn:import:org.gwtbootstrap3.client.ui.html"
>
```

**Comment by childers** [comment]
That one line is exactly what I needed.  Thank you!
