### ISSUE TITLE
new install error?

### ISSUE THREAD

**Issue by jaspwn** [GMOD/Apollo#2655]
Hi,
I've just recently had to reinstall apollo/arrow on a new machine and I am encountering and error when I try to run `arrow init`

It seemed all the dependecies installed fine and I have looked at the lines in the files that are causing the errors but I cannot see what or how to fix them.

Any help would be much appreciated.

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/arrow", line 5, in <module>
    from arrow.cli import arrow
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/arrow/cli.py", line 9, in <module>
    from .apollo import get_apollo_instance
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/arrow/apollo.py", line 3, in <module>
    from apollo import ApolloInstance
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/apollo/__init__.py", line 4, in <module>
    from apollo import (annotations, cannedcomments, cannedkeys,
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/apollo/annotations/__init__.py", line 10, in <module>
    from BCBio import GFF
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/BCBio/GFF/__init__.py", line 3, in <module>
    from BCBio.GFF.GFFParser import GFFParser, DiscoGFFParser, GFFExaminer, parse, parse_simple
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/BCBio/GFF/GFFParser.py", line 34, in <module>
    from Bio.Seq import UnknownSeq
ImportError: cannot import name 'UnknownSeq' from 'Bio.Seq' (/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/Bio/Seq.py)
```

**Comment by jaspwn** [comment]
So I went through the errors again and realised `UnknownSeq` is the issue. Seems it is a deprecated class in, the biopython package I could see that I was running a newer version `1.81` on my new install compared to my old install `1.79`

**Comment by jaspwn** [comment]
And I’ve realised I posted this to Apollo and not python-apollo

nothing to see here
