### ISSUE TITLE
Range Error when adding BAM track

### ISSUE THREAD

**Issue by eds35016** [GMOD/Apollo#2663]
I am running Apollo 2.7.0 via Docker and I am trying to add a BAM track manually via the add-bam-track.pl script. I was able to add several other BAM tracks fine, but with this particular file I seem to get the following error message:

![image](https://github.com/GMOD/Apollo/assets/88348319/8ce52829-aa63-4e9c-bd6d-fd3fae981983)

The BAM and index files both appear to be fine, however, this particular BAM file is slightly larger in size (~3.5 GB vs ~1 GB for the other files). The web browser console contained the following error:

`1.bundle.js:1 RangeError: Trying to access beyond buffer length
    at D (https://statgen.ncsu.edu/19334647861613004714/jbrowse/dist/0.bundle.js:8:11235)
    at u.readInt32LE (https://statgen.ncsu.edu/19334647861613004714/jbrowse/dist/0.bundle.js:8:13858)
    at e.<anonymous> (https://statgen.ncsu.edu/19334647861613004714/jbrowse/dist/0.bundle.js:193:306347)
    at l (https://statgen.ncsu.edu/19334647861613004714/jbrowse/dist/0.bundle.js:45:130574)
    at Generator._invoke (https://statgen.ncsu.edu/19334647861613004714/jbrowse/dist/0.bundle.js:45:130362)
    at forEach.t.<computed> [as next] (https://statgen.ncsu.edu/19334647861613004714/jbrowse/dist/0.bundle.js:45:130997)
    at r (https://statgen.ncsu.edu/19334647861613004714/jbrowse/dist/0.bundle.js:45:151677)
    at a (https://statgen.ncsu.edu/19334647861613004714/jbrowse/dist/0.bundle.js:45:151876) RangeError: Trying to access beyond buffer length
    at D (0.bundle.js:8:11235)
    at u.readInt32LE (0.bundle.js:8:13858)
    at e.<anonymous> (0.bundle.js:193:306347)
    at l (0.bundle.js:45:130574)
    at Generator._invoke (0.bundle.js:45:130362)
    at forEach.t.<computed> [as next] (0.bundle.js:45:130997)
    at r (0.bundle.js:45:151677)
    at a (0.bundle.js:45:151876)`

Any help would be greatly appreciated!

Apollo Version: 2.7.0
Grails version: 2.5.5
Groovy version: 2.4.4
JVM version: 1.8.0_352
Servlet Container Version: Apache Tomcat/9.0.31 (Ubuntu)
JBrowse config: 1.16.11-release

**Comment by eds35016** [comment]
I haven't figured out what the actual source of the issue is yet, but I have an inkling that it is likely due to a data problem on my end.

I was able to get the track to display properly in Apollo by removing unmapped reads and the header information with samtools through `samtools view -b Lymphnodes.sorted.bam > Lymphnodes.subset.bam`. This workaround seems to solve the issue.
