### ISSUE TITLE
Wrong database parameters used in production mode 

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#286]
I was trying to test out production mode and noticed that it seemed to be using H2 despite what settings I gave it via apollo-config.groovy file. For example, using the sample-mysql-apollo-config.groovy i get this weird error that says it is using the mysql driver but accessing a H2 connection string:

    16-Apr-2015 18:13:47.701 SEVERE [localhost-startStop-2] org.apache.tomcat.jdbc.pool.ConnectionPool.init Unable to create initial connections of pool.
     java.sql.SQLException: Driver:com.mysql.jdbc.Driver@4502324d returned null for URL:jdbc:h2:prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:296)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:182)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:701)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:635)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:486)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:144)

The postgres config seems to be problematic as well, and it ends up using an H2 database instead without throwing errors.

Would definitely like confirmation if i'm just doing something crazy.

Tested on macOSX and Ubuntu 14 simply by copying the sample configs to apollo-config.groovy, editing user/pass in them, and running "apollo deploy"

**Comment by nathandunn** [comment]
Did you use "./apollo deploy"?

Nathan

**Comment by cmdcolin** [comment]
yep. I am wondering if DataSource.groovy conflicts with it somehow?

**Comment by nathandunn** [comment]
it copies "apollo-config.groovy" into src/groovy or src/java . .  it then gets compiled and war'ed and is picked up instead of the default config.  Look at what the binary does.

**Comment by littlebunch** [comment]
I had the exact same issue but it went away after I started using the apollo script rather than grails war.  I must admit external configs have always been a bit tricky for me.
Gary

**Comment by nathandunn** [comment]
Yeah, my goal is that the binary script is what works.  A developer can then go in and take out the parts that they need to do / modify the various tasks.  

I’ve used this config over-ride method quite a few times in other projects, though, and works quite well.  

Nathan

**Comment by cmdcolin** [comment]
I still have some problems with this. I mean conceptually i understand that it's supposed to find those parameters in the apollo-config in prod mode but it doesn't seem to. I do get it working on postgres in development so I'm not sure what the deal is

I found this thread on stackoverflow with a similar issue perhaps, but i didn't really understand the resolution http://stackoverflow.com/questions/25713465/grails-keeps-accessing-h2-instead-of-postgres?rq=1

**Comment by nathandunn** [comment]
Skype me on Monday . . . 

I removed AppDefaults from the Config.groovy because its not correct if you are still using it. 

Nathan

**Comment by cmdcolin** [comment]
Sounds good :)

**Comment by nathandunn** [comment]
works on mac and icebox . . .  apollo-config not being picked in "classpath" on ubuntu when deployed as as war file.  

Other possible differences, Colin is working with OpenJDK 6, updating to 7.   

Other working environments use the Oracle version 7.  I am running Ubuntu on 12 . . . and it works fine.

**Comment by nathandunn** [comment]
Trying install with Oracle's Java via:  http://www.webupd8.org/2012/01/install-oracle-java-jdk-7-in-ubuntu-via.html

**Comment by cmdcolin** [comment]
I tried out java 7 (and 8) from oracle via the webupd8 installer

My orginal post was using the sample-mysql-apollo-config.groovy but here is the error using sample-postgres-apollo-config.groovy


    Configuring Shiro ...

    Shiro Configured
    2015-04-20 13:00:43,591 [http-bio-8080-exec-4] ERROR pool.ConnectionPool  - Unable to create initial connections of pool.
    org.h2.jdbc.JdbcSQLException: Error opening database: "Could not save properties /var/lib/tomcat7/prodDb.lock.db" [8000-176]
            at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
            at org.h2.message.DbException.get(DbException.java:167)
            at org.h2.store.FileLock.getExceptionFatal(FileLock.java:457)
            at org.h2.store.FileLock.save(FileLock.java:226)
            at org.h2.store.FileLock.lockFile(FileLock.java:353)
            at org.h2.store.FileLock.lock(FileLock.java:136)
            at org.h2.engine.Database.open(Database.java:622)
            at org.h2.engine.Database.openDatabase(Database.java:260)
            at org.h2.engine.Database.<init>(Database.java:254)
            at org.h2.engine.Engine.openSession(Engine.java:57)
            at org.h2.engine.Engine.openSession(Engine.java:164)
            at org.h2.engine.Engine.createSessionAndValidate(Engine.java:142)
            at org.h2.engine.Engine.createSession(Engine.java:125)
            at org.h2.engine.Engine.createSession(Engine.java:27)
            at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:331)
            at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
            at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
            at org.h2.Driver.connect(Driver.java:74)
            at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:278)
            at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:182)
            at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:701)
            at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:635)
            at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:486)
            at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:144)
            at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:116)
            at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:103)


Here is more of the error from using the sample-mysql-apollo-config.groovy


    Configuring Shiro ...

    Shiro Configured
    2015-04-20 13:13:39,063 [localhost-startStop-2] ERROR pool.ConnectionPool  - Unable to create initial connections of pool.
    java.sql.SQLException: Driver:com.mysql.jdbc.Driver@1dfc2eb5 returned null for URL:jdbc:h2:prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:296)
            at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:182)
            at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:701)
            at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:635)
            at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:486)
            at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:144)
            at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:116)
            at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:103)
            at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:127)
            at org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy.afterPropertiesSet(LazyConnectionDataSourceProxy.java:162)
            at org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy.<init>(LazyConnectionDataSourceProxy.java:106)
            at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
            at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
            at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
            at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:148)
            at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:125)
            at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:270)
            at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1115)
            at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018)
            at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
            at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
            at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:302)
            at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
            at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:298)
            at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
            at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:328)



This is using ubuntu 14 with oracle java 7


The mac osx production mode actually did work though so we are suspecting some sort of classpath error

**Comment by nathandunn** [comment]
That's good. . . . weird, but good.  Looks like its starting up with mysql, but it is picking up the wrong one somewhere.    I would look in Config.groovy.

**Comment by nathandunn** [comment]
to see if it isn't picking up another one first.

**Comment by cmdcolin** [comment]
It looks like removing the outer "grails" section of the sample configs fixes this problem. Tested on both ubuntu and mac...

If i look at some other sites it doesn't use a grails outer wrapper either

http://johnrellis.blogspot.com/2010/11/grails-quick-tip-external-configs.html

**Comment by nathandunn** [comment]
Its because its either development / grails instead of grails / development.  They just end up moving it around, but its still there it looks like.

Nathan

**Comment by cmdcolin** [comment]
That part of the article is where he is talking about the config.groovy. The external one below had no grails wrapper.

And as I noted, this definitely seems to fix the bug. I tried a bunch of stuff and this is the only thing to fix it...

**Comment by nathandunn** [comment]
I *think* its because its applying it to all environments, but we can look at t tomorrow.  

Nathan
