### ISSUE TITLE
Unable to delete more than one exon at a time.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#299]
1. I selected three exons (holding down Shift key) and attempted to delete them. First, Apollo only deleted the left-most exon. 
2. I selected the remaining two exons for deletion. Right-click + delete, then Apollo gave the error <code>"Cannot read property 'className' of undefined"</code>
3. After this happened, I was unable to add any other annotations to Uc-A. I had to refresh the page (which landed me on a different group), and navigated back to the scaffold of interest. The gene model I modified only had one more exon missing. 
4. I tried deleting multiple exons again, and Apollo only deleted the left-most one. I am unable to "Undo" functions, so I cannot check further.
5. I again tried selecting two and the same error appeared (see big red box in the image).
6. My conclusion is that Apollo is no longer able to delete more than one exon at a time.

![screen shot 2015-04-19 at 12 15 31 pm](https://cloud.githubusercontent.com/assets/1714621/7220900/16271142-e68e-11e4-9675-e1d8b8304d08.png)

From the console:
<code>
TypeError: Cannot read property 'className' of undefined
    at declare.renderExonSegments (http://icebox.lbl.gov/WebApollo2/jbrowse/plugins/WebApollo/js/View/Track/AnnotTrack.js:167:39)
    at declare.handleSubFeatures (http://icebox.lbl.gov/WebApollo2/jbrowse/plugins/WebApollo/js/View/Track/DraggableHTMLFeatures.js:568:39)
    at declare.renderFeature (http://icebox.lbl.gov/WebApollo2/jbrowse/src/JBrowse/View/Track/HTMLFeatures.js:1111:18)
    at inherited (http://icebox.lbl.gov/WebApollo2/jbrowse/src/dojo/_base/declare.js:189:42)
    at declare.renderFeature (http://icebox.lbl.gov/WebApollo2/jbrowse/plugins/WebApollo/js/View/Track/DraggableHTMLFeatures.js:316:28)
    at declare.renderFeature (http://icebox.lbl.gov/WebApollo2/jbrowse/plugins/WebApollo/js/View/Track/AnnotTrack.js:485:81)
    at declare.addFeatureToBlock (http://icebox.lbl.gov/WebApollo2/jbrowse/src/JBrowse/View/Track/HTMLFeatures.js:669:28)
    at null.<anonymous> (http://icebox.lbl.gov/WebApollo2/jbrowse/src/JBrowse/View/Track/HTMLFeatures.js:619:26)
    at http://icebox.lbl.gov/WebApollo2/jbrowse/src/dojo/_base/lang.js:375:55
    at declare.getFeatures (http://icebox.lbl.gov/WebApollo2/jbrowse/plugins/WebApollo/js/Store/SeqFeature/ScratchPad.js:91:17) TypeError: Cannot read property 'className' of undefineddeclare._handleError @ /WebApollo2/jbrowse/src/JBrowse/View/Track/BlockBased.js:448
/WebApollo2/jbrowse/plugins/WebApollo/js/View/Track/AnnotTrack.js:401 unknown command: undefined
</code>

**Comment by monicacecilia** [comment]
p.s: it works like a charm on 1.0.4

**Comment by nathandunn** [comment]
The "className" is because its not updating correctly (some of the time).  This is the update code failing (which is also a failure).   A refresh will make it appear correctly. 

It also complains that features are already deleted when multiple.

Will need to write an integration test for this.   

Note: I did not *ALWAYS* get the className error.

**Comment by monicacecilia** [comment]
working as expected. thanks!
this deserves a celebration! :dancer:
