### ISSUE TITLE
WebSocket error->Unable to add or edit features on UcA area->Document (nginx and apache)

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#343]
The gnomes of the interwebs do not seem to be on our side today.

Errors I am receiving:

<code>WebSocket connection to 'ws://icebox.lbl.gov/Apollo2/stomp/966/h90o3k69/websocket' failed: WebSocket is closed before the connection is established.</code>

<code>Uncaught com.google.gwt.json.client.JSONException: Error parsing JSON: SyntaxError: Unexpected token</code>

<code>Uncaught Error: INVALID_STATE_ERR</code>

**Comment by nathandunn** [comment]
Yeah, you have to test though 8080 right now or you can wait to test this.   Nginx on icebox is not properly configured.  Its on my list of things to do today.

Nathan

**Comment by nathandunn** [comment]
Bizarre, only error is this, which would indicate web sockets:

Organism to string:  {"id":4,"commonName":"Honey1","genus":"Apis","species":"mellifera","directory":"/data/jbrowse/data-amel-demo"}
May 04, 2015 10:45:15 AM org.apache.coyote.AbstractProcessor setErrorState
INFO: An error occurred in processing while on a non-container thread. The connection will be closed immediately
java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
        at org.apache.coyote.http11.InternalOutputBuffer.realWriteBytes(InternalOutputBuffer.java:215)
        at org.apache.tomcat.util.buf.ByteChunk.flushBuffer(ByteChunk.java:480)
        at org.apache.coyote.http11.InternalOutputBuffer.flush(InternalOutputBuffer.java:119)
        at org.apache.coyote.http11.AbstractHttp11Processor.action(AbstractHttp11Processor.java:800)
        at org.apache.coyote.Response.action(Response.java:172)
        at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:363)
        at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:331)
        at org.apache.catalina.connector.Response.flushBuffer(Response.java:580)
        at org.apache.catalina.connector.ResponseFacade.flushBuffer(ResponseFacade.java:306)
        at org.springframework.http.server.ServletServerHttpResponse.flush(ServletServerHttpResponse.java:90)
        at org.springframework.web.socket.sockjs.transport.session.AbstractHttpSockJsSession.writeFrameInternal(AbstractHttpSockJsSession.java:342)
        at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.writeFrame(AbstractSockJsSession.java:337)
        at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.sendHeartbeat(AbstractSockJsSession.java:384)
        at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession$2.run(AbstractSockJsSession.java:402)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by nathandunn** [comment]
@monicacecilia  Indicated that it worked fine on firefox.   Partly probably a caching issue as it should have degraded back.  However, the "websocket" error is completely correct and is probably causing problems for the USDA folks as well.

**Comment by nathandunn** [comment]
Fixed on icebox . . updated doc in these two commits for both apache and nginx:

https://github.com/GMOD/Apollo/commit/341e43573f462b047ec03c20401dc386f2d5605a
https://github.com/GMOD/Apollo/commit/c382f6c25631e5fefd6e812178df7d8858b76b47

**Comment by nathandunn** [comment]
FYI: @littlebunch  @cmdcolin    @childers @mpoelchau

I provided (& tested) instructions for apache and nginx if you are going to be proxying.  

https://github.com/GMOD/Apollo/blob/master/docs/Configure.md

**Comment by cmdcolin** [comment]
I think the apache proxy should only require the ProxyPass and ProxyPassReverse statements. The other ones might not hurt but they can actually be dangerous (especially the <Proxy *> section, that is for a forward proxy which is definitely not necessary see here http://httpd.apache.org/docs/2.2/mod/mod_proxy.html). The proxypreservehost and cookie path one aren't too bad though.



    ProxyPass "/apollo/stomp"  "ws://localhost:8080/apollo/stomp"
    ProxyPassReverse "/apollo/stomp" "ws://localhost:8080/apollo/stomp"
    ProxyPass  /apollo http://localhost:8080/apollo
    ProxyPassReverse  /apollo http://localhost:8080/apollo

**Comment by nathandunn** [comment]
How about:

    ProxyRequests     off    
    ProxyPreserveHost on
    ProxyPass "/apollo/stomp"  "ws://localhost:8080/apollo/stomp"
    ProxyPassReverse "/apollo/stomp" "ws://localhost:8080/apollo/stomp”
    ProxyPass  /apollo http://localhost:8080/apollo
    ProxyPassReverse  /apollo http://localhost:8080/apollo
    ProxyPassReverseCookiePath  / http://localhost:8080/apollo


You have to have the Cookie Path in there in order to enable the RememberMe Cookie.  

ProxyRequests     off    # I’m pretty sure you have to have this in order to make it secure

I’m not sure about the “PreserverHost”.  I typically don’t have it there, so maybe its un-necessary.   I'm not sure about the "Allow from All".   I *think* you need that, but you have to have it in conjunction with ProxyRequests off.   

    <Proxy *>
         Order deny,allow
         Allow from all
    </Proxy>
        
Working with Apache is like re-inventing the wheel each time so any feedback would be useful.

Nathan

**Comment by monicacecilia** [comment]
Have not seen this error again.
