### ISSUE TITLE
Running multiple instances of WA2 produces error

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#462]
Given that running multiple copies is unlikely this is not super important, but I was still surprised by this error

    2015-07-01 13:09:55,080 [localhost-startStop-8] ERROR context.GrailsContextLoaderListener  - Error initializing Grails: javax.management.InstanceAlreadyExistsException: net.sf.ehcache:type=CacheManager,name=grails-cache-ehcache
    net.sf.ehcache.CacheException: javax.management.InstanceAlreadyExistsException: net.sf.ehcache:type=CacheManager,name=grails-cache-ehcache
        at net.sf.ehcache.management.ManagementService.init(ManagementService.java:246)
            at net.sf.ehcache.event.CacheManagerEventListenerRegistry.init(CacheManagerEventListenerRegistry.java:104)
            at net.sf.ehcache.CacheManager.doInit(CacheManager.java:482)
            at net.sf.ehcache.CacheManager.init(CacheManager.java:395)
            at grails.plugin.cache.ehcache.GrailsEhCacheManagerFactoryBean$ReloadableCacheManager.rebuild(GrailsEhCacheManagerFactoryBean.java:184)
            at grails.plugin.cache.ehcache.EhcacheConfigLoader.reload(EhcacheConfigLoader.groovy:63)
            at grails.plugin.cache.ConfigLoader.reload(ConfigLoader.groovy:42)
            at CacheGrailsPlugin.reloadCaches(CacheGrailsPlugin.groovy:202)
            at CacheGrailsPlugin$_closure3.doCall(CacheGrailsPlugin.groovy:158)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
            at java.util.concurrent.FutureTask.run(FutureTask.java:262)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
            at java.lang.Thread.run(Thread.java:745)
        Caused by: javax.management.InstanceAlreadyExistsException: net.sf.ehcache:type=CacheManager,name=grails-cache-ehcache
            at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
            at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
            at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
            at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
            at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
            at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
            at net.sf.ehcache.management.ManagementService.registerCacheManager(ManagementService.java:265)
            at net.sf.ehcache.management.ManagementService.init(ManagementService.java:233)2015-07-01 13:09:55,080 [localhost-startStop-8] ERROR context.GrailsContextLoaderListener  - Error initializing Grails: javax.management.InstanceAlreadyExistsException: net.sf.ehcache:type=CacheManager,name=grails-cache-ehcache
            net.sf.ehcache.CacheException: javax.management.InstanceAlreadyExistsException: net.sf.ehcache:type=CacheManager,name=grails-cache-ehcache
                at net.sf.ehcache.management.ManagementService.init(ManagementService.java:246)
            at net.sf.ehcache.event.CacheManagerEventListenerRegistry.init(CacheManagerEventListenerRegistry.java:104)
            at net.sf.ehcache.CacheManager.doInit(CacheManager.java:482)
            at net.sf.ehcache.CacheManager.init(CacheManager.java:395)
            at grails.plugin.cache.ehcache.GrailsEhCacheManagerFactoryBean$ReloadableCacheManager.rebuild(GrailsEhCacheManagerFactoryBean.java:184)
            at grails.plugin.cache.ehcache.EhcacheConfigLoader.reload(EhcacheConfigLoader.groovy:63)
            at grails.plugin.cache.ConfigLoader.reload(ConfigLoader.groovy:42)
            at CacheGrailsPlugin.reloadCaches(CacheGrailsPlugin.groovy:202)
            at CacheGrailsPlugin$_closure3.doCall(CacheGrailsPlugin.groovy:158)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
            at java.util.concurrent.FutureTask.run(FutureTask.java:262)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
            at java.lang.Thread.run(Thread.java:745)
        Caused by: javax.management.InstanceAlreadyExistsException: net.sf.ehcache:type=CacheManager,name=grails-cache-ehcache
            at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
            at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
            at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
            at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
            at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
            at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
            at net.sf.ehcache.management.ManagementService.registerCacheManager(ManagementService.java:265)
            at net.sf.ehcache.management.ManagementService.init(ManagementService.java:233)

Might need to be documented in the troubleshooting guide or otherwise fixed

**Comment by monicacecilia** [comment]
oh? @cmdcolin how many is "multiple"?  and do you mean exact copies of the same data? or just several instances of Apollo with different data? and how many species per instance?

**Comment by cmdcolin** [comment]
Two. It is just having two instances deployed on the same tomcat. I had not seen this before maybe two weeks ago, so it might have to do with the fact that ehcache was enabled here 41a14afc8c

**Comment by nathandunn** [comment]
Can you assign it to 2.0.0 important.  It's an easy fix to switch the names and it should work for larger installs.  If you know how to fix it that would be great.  

Nathan

**Comment by cmdcolin** [comment]
Should be fixed now. Fairly common error, documented fix here http://unicolet.blogspot.com/2014/06/ehcache-deploy-multiple-versions-of.html

**Comment by nathandunn** [comment]
@cmdcolin   Can this be closed?  Not sure if there is any additional way for us to test it.

**Comment by cmdcolin** [comment]
Should be fixed as far as i know. Can reopen if anything happens
