### ISSUE TITLE
!!(4h) can not delete isoforms / deletion failure ignored

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#497]
This was working earlier.  Probably introduced in RC2 . . optimization code is a likely culprit just due to nature of associations, but need to create integration test either way to fix! 

====

Code to look at reverting:

- [ ] add / confirm integration test 

=====
- [ ] https://github.com/GMOD/Apollo/pull/460/files#diff-4fce0a6a2c4c13cc38800ed7dcb489f6L9
- [ ] https://github.com/GMOD/Apollo/pull/460/files#diff-4fce0a6a2c4c13cc38800ed7dcb489f6L183
- [ ] https://github.com/GMOD/Apollo/pull/460/files#diff-b5552b4e9fad5ee11f3c83eb66cb01fdL1987
- [ ]  https://github.com/GMOD/Apollo/pull/460/files#diff-093a3cf9e0a83a8d8bbbecc8575e51a9L45 (should just be reverted?) 
- [ ] https://github.com/GMOD/Apollo/pull/460/files#diff-5059381e0b30986d68f9bb0d6cdf6000L400    (I'm not sure that this code does the same stuff)

```
2015-07-23 14:41:24,979 [clientInboundChannel-2] ERROR springwebsocket.GrailsSimpAnnotationMethodMessageHandler  - Unhandled exception
java.lang.reflect.InvocationTargetException
	at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure3_closure4_closure5.doCall(AnnotationEditorController.groovy:826)
	at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure3_closure4.doCall(AnnotationEditorController.groovy:825)
	at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure3.doCall(AnnotationEditorController.groovy:821)
	at groovyx.gpars.group.PGroup$3.call(PGroup.java:289)
	at groovyx.gpars.group.PGroup$4.run(PGroup.java:313)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.dao.InvalidDataAccessApiUsageException: deleted object would be re-saved by cascade (remove deleted object from associations): [org.bbop.apollo.FeatureRelationship#414121]; nested exception is org.hibernate.ObjectDeletedException: deleted object would be re-saved by cascade (remove deleted object from associations): [org.bbop.apollo.FeatureRelationship#414121]
	... 8 more
Caused by: org.hibernate.ObjectDeletedException: deleted object would be re-saved by cascade (remove deleted object from associations): [org.bbop.apollo.FeatureRelationship#414121]
	... 8 more
2015-07-23 14:41:27,338 [http-bio-8080-exec-2] WARN  apollo.AnnotatorController  - Type not found for annotation filter 'null'
2015-07-23 14:41:28,275 [http-bio-8080-exec-7] WARN  apollo.JbrowseController  - File not found: /data/jbrowse/data-amel-demo//tracks.conf
```

**Comment by nathandunn** [comment]
Code to look at reverting:

- [ ] https://github.com/GMOD/Apollo/pull/460/files#diff-4fce0a6a2c4c13cc38800ed7dcb489f6L9
- [ ] https://github.com/GMOD/Apollo/pull/460/files#diff-4fce0a6a2c4c13cc38800ed7dcb489f6L183
- [ ] https://github.com/GMOD/Apollo/pull/460/files#diff-b5552b4e9fad5ee11f3c83eb66cb01fdL1987
- [ ] (should just be reverted): https://github.com/GMOD/Apollo/pull/460/files#diff-093a3cf9e0a83a8d8bbbecc8575e51a9L45
- [ ] https://github.com/GMOD/Apollo/pull/460/files#diff-5059381e0b30986d68f9bb0d6cdf6000L400    (I'm not sure that this code does the same stuff)

**Comment by nathandunn** [comment]
I think that the culprit was a minor (improved) update of hibernate / grails 2.4.5 

Anyway, you can delete an isoform now.
