### ISSUE TITLE
re-enable padding and projection type

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#669]
- [x] re-enable Exon Projection
- [x] re-enable padding on projections
- [x] case A: single NO-chunking
   - [x] no folding: Group 6.10
   - [x] exon (fixed . . but for some reason starts with the larger set)
- [x] case B: single chunking
   - [x] no folding: Group 1.10 and 11.6
   - [x] exon 
- [x] case 1:  trackData.json (NO-chunking), trackData.json (NO-chunking)
   - [x] no folding: Group 6.10 / 4.1 and Group4.1/6.10
   - [x] DO regression test for exon-folding of GroupUn87, Group11.4 in TrackServiceIntegrationSpec
   - [x] exon (Group 6.10 / 4.1 and Group4.1/6.10), (Group 11.4, GroupUn87)
- [x] case 2:  trackData.json (chunking), trackData.json (chunking) (group 1.10 / group 11.6)
   - [x] no folding group1.10 / Group 11.6 works
   - [x] Group 11.6 / 1.10 fails (latter have doesn't work)
   - [x] *exon (alignment fails completely)* - **latter half not showing up**
- [x] case 3:  trackData.json (NO-chunking), trackData.json (chunking) - group 6.10 / group 1.10
   - [x] no folding (drops the 1.10 part) (has big holes here) - grabbing right one, but wrong sequence offset being applied to locations
   - [x] **exon (latter half drops)**
- [x] case 4:  trackData.json (chunking), trackData.json (NO-chunking)- group 1.10 / group 6.10
   - [x] no folding
   - [x] *exon (loses 6.10 part)*
- [x] case 5: small data is lost  (Un1493 works when on RefSeq page) or when projected with others . . . prob just bad length
   - [x] no folding Un1493
   - [x] exon folding Un1493

These are working, but not wired.

**Comment by nathandunn** [comment]
- [ ] fixRefSeq
- [ ] fixTrackData.json
- [ ] fix lf-*.json

**Comment by nathandunn** [comment]
what is returned with an exon projection - the length for the original is 1.38 M:
```
[{"seqChunkSize":20000,"start":0,"name":"{\"padding\":50, \"projection\":\"Exon\", \"referenceTrack\":\"Official Gene Set v3.2\", \"sequenceList\":[{\"name\":\"Group1.1\"}]}:-1..-1","length":487,"end":487}]
```

**Comment by nathandunn** [comment]
Currently it puts things in the incorrect order (the nc-list) . . ht e index is in the wrong place . . . need to check all cases (as above).

**Comment by nathandunn** [comment]
Its not clear if I can use a projected trackData next to a chunk one.

**Comment by nathandunn** [comment]
Need to fix the directory path and then decide and fix on the projections

```
2015-11-13 16:42:28,539 [main] WARN  apollo.FeatureService  - Fix generateTranscript to allow for multiple sequences
| Running 14 integration tests... 62 of 62
| Failure:  exon projections of contiguous tracks should work(org.bbop.apollo.TrackServiceIntegrationSpec)
|  java.io.FileNotFoundException: test/integration/resources/sequences/honeybee-tracks/tracks/Official Gene Set v3.2/GroupUn87/trackData.json (No such file or directory)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at org.bbop.apollo.ProjectionService.$tt__loadTrackJson(ProjectionService.groovy:465)
	at org.bbop.apollo.ProjectionService.$tt__getExonLocations(ProjectionService.groovy:412)
	at org.bbop.apollo.ProjectionService.$tt__getLocationsForDescription(ProjectionService.groovy:373)
	at org.bbop.apollo.ProjectionService.$tt__createMultiSequenceProjection(ProjectionService.groovy:364)
	at org.bbop.apollo.ProjectionService.$tt__getProjection(ProjectionService.groovy:879)
	at org.bbop.apollo.ProjectionService.$tt__getProjection(ProjectionService.groovy:819)
	at org.bbop.apollo.TrackService.$tt__loadTrackData(TrackService.groovy:335)
	at org.bbop.apollo.TrackService.$tt__projectTrackData(TrackService.groovy:571)
	at org.bbop.apollo.TrackServiceIntegrationSpec.exon projections of contiguous tracks should work(TrackServiceIntegrationSpec.groovy:29)
| Completed 62 integration tests, 1 failed in 0m 41s
```
