### ISSUE TITLE
API throwing UnknownAccountException which returns HTML content.

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#703]
E.g.

```console
$ curl -H "Content-Type: application/json" 'http://localhost:8080/apollo/organism/addOrganism' -d '{"commonName":"Test", "directory":"/data/merlin-gff/data", "genus":"", "species":"", "blatdb":"", "publicMode":false, "username": "not-a-real-user", "password": "yourpass"}'
```

returns a large html blob, rather than the expected `{"error":"Not authorized"}`

```
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Error</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
```

**Comment by cmdcolin** [comment]
Are you sure there isn't anything else going on?

Maybe the server crashed!

**Comment by cmdcolin** [comment]
The tomcat logs may have more info too

**Comment by erasche** [comment]
Sorry, meant to attach that stacktrace.

```
webapollo2_1 | 2015-11-17 19:11:09,315 [http-bio-8080-exec-2] ERROR errors.GrailsExceptionResolver  - UnknownAccountException occurred when processing request: [POST] /apollo/organism/addOrganism
webapollo2_1 | No account found for user [not-a-real-user]. Stacktrace follows:
webapollo2_1 | org.apache.shiro.authc.UnknownAccountException: No account found for user [not-a-real-user]
webapollo2_1 |  at org.bbop.apollo.DbRealm.authenticate(DbRealm.groovy:29)
webapollo2_1 |  at org.apache.shiro.grails.RealmWrapper.getAuthenticationInfo(RealmWrapper.groovy:59)
webapollo2_1 |  at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doSingleRealmAuthentication(ModularRealmAuthenticator.java:180)
webapollo2_1 |  at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doAuthenticate(ModularRealmAuthenticator.java:267)
webapollo2_1 |  at org.apache.shiro.authc.AbstractAuthenticator.authenticate(AbstractAuthenticator.java:198)
webapollo2_1 |  at org.apache.shiro.mgt.AuthenticatingSecurityManager.authenticate(AuthenticatingSecurityManager.java:106)
webapollo2_1 |  at org.apache.shiro.mgt.DefaultSecurityManager.login(DefaultSecurityManager.java:270)
webapollo2_1 |  at org.apache.shiro.subject.support.DelegatingSubject.login(DelegatingSubject.java:256)
webapollo2_1 |  at org.bbop.apollo.SecurityFilters$_closure1_closure2_closure3.doCall(SecurityFilters.groovy:23)
webapollo2_1 |  at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
webapollo2_1 |  at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
webapollo2_1 |  at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
webapollo2_1 |  at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
webapollo2_1 |  at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
webapollo2_1 |  at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
webapollo2_1 |  at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
webapollo2_1 |  at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
webapollo2_1 |  at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
webapollo2_1 |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
webapollo2_1 |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
webapollo2_1 |  at java.lang.Thread.run(Thread.java:745)
```

**Comment by cmdcolin** [comment]
Ah I suppose you are right then. Should be web service specific but I'll add a fix. Uncaught exceptions are never nice.

**Comment by erasche** [comment]
Thanks @cmdcolin!

**Comment by nathandunn** [comment]
:+1:

**Comment by nathandunn** [comment]
Nothing to test . . re-open if need be.
