### ISSUE TITLE
Export "GFF3 with Fasta" throws "No such property: sequenceList for class: org.bbop.apollo.IOServiceController"

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#704]
Exporting | Popup Option | Result
--- | --- | ---
GFF3 | GFF3 | :white_check_mark: 
GFF3 | GFF3 with Fasta | :x: (No such property: sequenceList for class: org.bbop.apollo.IOServiceController")
Fasta | Any | :white_check_mark:

**Comment by nathandunn** [comment]
@cmdcolin   It looks like you forgot to fix this after the refactor:

https://github.com/GMOD/Apollo/blob/master/grails-app/controllers/org/bbop/apollo/IOServiceController.groovy#L113

**Comment by nathandunn** [comment]
Looks as though this is part of master branch though.

**Comment by erasche** [comment]
```
webapollo2_1 | groovy.lang.MissingPropertyException: No such property: sequenceList for class: org.bbop.apollo.IOServiceController
webapollo2_1 |  at org.codehaus.groovy.grails.plugins.web.api.ControllerTagLibraryApi.propertyMissing(ControllerTagLibraryApi.java:121)
webapollo2_1 |  at org.bbop.apollo.IOServiceController.propertyMissing(IOServiceController.groovy)
webapollo2_1 |  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
webapollo2_1 |  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
webapollo2_1 |  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
webapollo2_1 |  at java.lang.reflect.Method.invoke(Method.java:606)
webapollo2_1 |  at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
webapollo2_1 |  at groovy.lang.MetaClassImpl.invokeMissingProperty(MetaClassImpl.java:873)
webapollo2_1 |  at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1852)
webapollo2_1 |  at groovy.lang.ExpandoMetaClass.getProperty(ExpandoMetaClass.java:1150)
webapollo2_1 |  at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:3689)
webapollo2_1 |  at groovy.lang.ExpandoMetaClass.getProperty(ExpandoMetaClass.java:1162)
webapollo2_1 |  at org.bbop.apollo.AbstractApolloController.getProperty(AbstractApolloController.groovy)
webapollo2_1 |  at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:47)
webapollo2_1 |  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:231)
webapollo2_1 |  at org.bbop.apollo.IOServiceController._do_write(IOServiceController.groovy:113)
webapollo2_1 |  at org.bbop.apollo.IOServiceController.this$3$_do_write(IOServiceController.groovy)
webapollo2_1 |  at org.bbop.apollo.IOServiceController$this$3$_do_write.callCurrent(Unknown Source)
webapollo2_1 |  at org.bbop.apollo.IOServiceController.write(IOServiceController.groovy)
webapollo2_1 |  at sun.reflect.GeneratedMethodAccessor746.invoke(Unknown Source)
webapollo2_1 |  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
webapollo2_1 |  at java.lang.reflect.Method.invoke(Method.java:606)
webapollo2_1 |  at org.codehaus.groovy.grails.web.servlet.mvc.MixedGrailsControllerHelper.invoke(MixedGrailsControllerHelper.java:154)
webapollo2_1 |  at org.codehaus.groovy.grails.web.servlet.mvc.AbstractGrailsControllerHelper.handleAction(AbstractGrailsControllerHelper.java:375)
webapollo2_1 |  at org.codehaus.groovy.grails.web.servlet.mvc.AbstractGrailsControllerHelper.executeAction(AbstractGrailsControllerHelper.java:252)
webapollo2_1 |  at org.codehaus.groovy.grails.web.servlet.mvc.AbstractGrailsControllerHelper.handleURI(AbstractGrailsControllerHelper.java:205)
webapollo2_1 |  at org.codehaus.groovy.grails.web.servlet.mvc.AbstractGrailsControllerHelper.handleURI(AbstractGrailsControllerHelper.java:126)
webapollo2_1 |  at org.codehaus.groovy.grails.web.servlet.mvc.SimpleGrailsController.handleRequest(SimpleGrailsController.java:72)
webapollo2_1 |  at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
webapollo2_1 |  at org.codehaus.groovy.grails.web.servlet.GrailsDispatcherServlet.doDispatch(GrailsDispatcherServlet.java:347)
webapollo2_1 |  at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:870)
webapollo2_1 |  at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961)
webapollo2_1 |  at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:863)
webapollo2_1 |  at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
webapollo2_1 |  at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:837)
webapollo2_1 |  at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
webapollo2_1 |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
webapollo2_1 |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
webapollo2_1 |  at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
webapollo2_1 |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
webapollo2_1 |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
webapollo2_1 |  at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
webapollo2_1 |  at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
webapollo2_1 |  at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
webapollo2_1 |  at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
webapollo2_1 |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
webapollo2_1 |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
webapollo2_1 |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
webapollo2_1 |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
webapollo2_1 |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
webapollo2_1 |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
webapollo2_1 |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
webapollo2_1 |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
webapollo2_1 |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
webapollo2_1 |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
webapollo2_1 |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
webapollo2_1 |  at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
webapollo2_1 |  at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:486)
webapollo2_1 |  at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:411)
webapollo2_1 |  at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)
webapollo2_1 |  at org.codehaus.groovy.grails.web.mapping.UrlMappingUtils.forwardRequestForUrlMappingInfo(UrlMappingUtils.java:178)
webapollo2_1 |  at org.codehaus.groovy.grails.web.mapping.UrlMappingUtils.forwardRequestForUrlMappingInfo(UrlMappingUtils.java:144)
webapollo2_1 |  at org.codehaus.groovy.grails.web.mapping.UrlMappingUtils.forwardRequestForUrlMappingInfo(UrlMappingUtils.java:135)
webapollo2_1 |  at org.codehaus.groovy.grails.web.mapping.filter.UrlMappingsFilter.doFilterInternal(UrlMappingsFilter.java:216)
webapollo2_1 |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
webapollo2_1 |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
webapollo2_1 |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
webapollo2_1 |  at org.codehaus.groovy.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:69)
webapollo2_1 |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
webapollo2_1 |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
webapollo2_1 |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
webapollo2_1 |  at org.codehaus.groovy.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
webapollo2_1 |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
webapollo2_1 |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
webapollo2_1 |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
webapollo2_1 |  at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
webapollo2_1 |  at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
webapollo2_1 |  at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
webapollo2_1 |  at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
webapollo2_1 |  at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
webapollo2_1 |  at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
webapollo2_1 |  at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
webapollo2_1 |  at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
webapollo2_1 |  at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
webapollo2_1 |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
webapollo2_1 |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
webapollo2_1 |  at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
webapollo2_1 |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
webapollo2_1 |  at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
webapollo2_1 |  at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
webapollo2_1 |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
webapollo2_1 |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
webapollo2_1 |  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
webapollo2_1 |  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
webapollo2_1 |  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
webapollo2_1 |  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
webapollo2_1 |  at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
webapollo2_1 |  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
webapollo2_1 |  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
webapollo2_1 |  at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
webapollo2_1 |  at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
webapollo2_1 |  at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
webapollo2_1 |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
webapollo2_1 |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
webapollo2_1 |  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
webapollo2_1 |  at java.lang.Thread.run(Thread.java:745)

```

**Comment by cmdcolin** [comment]
Woops. Indeed, related to some recent refactor. Thanks for catching.

**Comment by cmdcolin** [comment]
Should be fixed now. It's not blazing fast at getting a full genome fasta but it should be acceptable.

@nathandunn can you check the export gff3 dialog too? it looks a little glitchy

Thanks

**Comment by cmdcolin** [comment]
![test9](https://cloud.githubusercontent.com/assets/6511937/11228552/f4e6c7e0-8d52-11e5-8d03-4bb8327b0dd7.png)

**Comment by nathandunn** [comment]
There are a bunch of issues in 2.0.3 related to cleaning up the gff export box . . we should probably do that then.  If you want to create a separate issue for that, that's fine . . otherwise, I think the first person to open it will probably fix it.

**Comment by cmdcolin** [comment]
This might still have some bugs. The downloaded file is broken and 10 bytes from what i saw

**Comment by nathandunn** [comment]
@cmdcolin  Do you have some more details?

**Comment by nathandunn** [comment]
Not sure why this was changed @cmdcolin  I reverted it back and it works fine.:

diff --git a/grails-app/controllers/org/bbop/apollo/IOServiceController.groovy b/grails-app/controllers/org/bbop/apollo/IOServiceController.groovy
index e3c5cfa..43366a5 100644
--- a/grails-app/controllers/org/bbop/apollo/IOServiceController.groovy
+++ b/grails-app/controllers/org/bbop/apollo/IOServiceController.groovy
@@ -192,8 +192,9 @@ class IOServiceController extends AbstractApolloController {
 
```
         response.setHeader("Content-disposition", "attachment; filename=${downloadFile.fileName}")
         if(params.format=="gzip") {
-            def output = new BufferedOutputStream(new GZIPOutputStream(response.outputStream))
-            output << file.text
+            new GZIPOutputStream(response.outputStream).withWriter{ it << file.text }
+//            def output = new BufferedOutputStream(new GZIPOutputStream(response.outputStream))
+//            output << file.text
```

**Comment by cmdcolin** [comment]
I was getting out of memory errors when doing GFF3+FASTA exports so I tried using the BufferedOutputSream...probably should have tested more, I'd surprised because I thought it was working

**Comment by nathandunn** [comment]
Hmm . . wondering if it was a side-effect of something else.  I'll try redeploying it shortly.

**Comment by monicacecilia** [comment]
I am able to export,  but what's with this odd display? 
That's a new bug. 

![screen shot 2015-12-10 at 1 25 38 pm](https://cloud.githubusercontent.com/assets/1714621/11728963/981cd0e4-9f41-11e5-8aab-23361355ea05.png)

**Comment by nathandunn** [comment]
I think its the only non-bootstrap dialog is the most likely culprit.   Thought we had a bug for it, but I will create one (#726).

**Comment by monicacecilia** [comment]
Reviewed update on #726 :dancer:
