### ISSUE TITLE
Running tests with no apollo-config.groovy (?H2?) causes integration tests errors and failure in .travis

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#739]
- [ ]  running ```./apollo test``` then leads to this error.
- [ ] ```./apollo clean-all``` does not seem to remove ```src/java/apollo-config.groovy```
- [ ] fix error with H2 

May not have to do with the datasource, but some other issue.  

```
| Running 11 integration tests... 4 of 11
| Failure:  we can undo and redo a merge transcript(org.bbop.apollo.FeatureEventServiceIntegrationSpec)
|  org.bbop.apollo.AnnotationException: Feature event list is the wrong size 0
	at org.bbop.apollo.FeatureEventService.$tt__getCurrentFeatureEventIndex(FeatureEventService.groovy:694)
	at org.bbop.apollo.FeatureEventService.$tt__undo(FeatureEventService.groovy:716)
	at org.bbop.apollo.RequestHandlingService.$tt__undo(RequestHandlingService.groovy:2234)
	at org.bbop.apollo.FeatureEventServiceIntegrationSpec.we can undo and redo a merge transcript(FeatureEventServiceIntegrationSpec.groovy:157)
| Completed 62 integration tests, 1 failed in 0m 26s
***
Metrics servlet injected into web.xml
```

**Comment by nathandunn** [comment]
After messing with the config .  . definitely seems to favor error with H2.

**Comment by nathandunn** [comment]
Seems to be fixed.
