### ISSUE TITLE
undo error when eventList is 0

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#795]
To reproduce (this was working in 2.0.0) . . fails in 2.0.1. 

@monicacecilia will add some images showing the history and genes of interest.

```
6-01-16 11:13:22,369 [clientInboundChannel-3] ERROR springwebsocket.GrailsSimpAnnotationMethodMessageHandler  - Unhandled exception
java.lang.reflect.InvocationTargetException
	at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure3_closure4_closure5.doCall(AnnotationEditorController.groovy:1075)
	at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure3_closure4.doCall(AnnotationEditorController.groovy:1074)
	at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure3.doCall(AnnotationEditorController.groovy:1070)
	at groovyx.gpars.group.PGroup$3.call(PGroup.java:289)
	at groovyx.gpars.group.PGroup$4.run(PGroup.java:313)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.bbop.apollo.AnnotationException: Feature event list is the wrong size 0
	at org.bbop.apollo.FeatureEventService.$tt__getCurrentFeatureEventIndex(FeatureEventService.groovy:694)
	at org.bbop.apollo.FeatureEventService.$tt__redo(FeatureEventService.groovy:677)
	at org.bbop.apollo.RequestHandlingService.$tt__redo(RequestHandlingService.groovy:2250)
	... 8 more
```

**Comment by monicacecilia** [comment]
Screen captures

<img width="1183" alt="screen shot 2016-01-16 at 11 21 32 am" src="https://cloud.githubusercontent.com/assets/1714621/12374036/75ff45c6-bc44-11e5-9835-d03de3dfa68b.png">


<img width="798" alt="screen shot 2016-01-16 at 11 21 49 am" src="https://cloud.githubusercontent.com/assets/1714621/12374037/7b9794b6-bc44-11e5-8324-590d612a7d8e.png">

**Comment by nathandunn** [comment]
Redundant with #792

**Comment by nathandunn** [comment]
Another test-case to test I guess.

**Comment by monicacecilia** [comment]
#792 still not working correctly.

**Comment by nathandunn** [comment]
The error in #792 is unrelated to this error so I'll close this for now as this wasn't the cause.

**Comment by nathandunn** [comment]
I closed this, but we're no longer seeing a problem due to this error.  I would prefer consolidating these (unless this has specific use-cases).

**Comment by monicacecilia** [comment]
:dancer: :dancer:
